// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_bootstrap_administration.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const lookupPlatformCoreBootstrapTenant = `-- name: LookupPlatformCoreBootstrapTenant :one
SELECT tenant_id FROM tenant_bootstrap_operations WHERE id=$1 AND source_kind='core'
`

type LookupPlatformCoreBootstrapTenantParams struct {
	OperationID uuid.UUID
}

// The global operation identity is used only by the separately authorized
// Platform entry. All subsequent locks and relations carry its stored Tenant.
func (q *Queries) LookupPlatformCoreBootstrapTenant(ctx context.Context, arg LookupPlatformCoreBootstrapTenantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lookupPlatformCoreBootstrapTenant, arg.OperationID)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const resumeReissuedCoreBootstrap = `-- name: ResumeReissuedCoreBootstrap :execrows
UPDATE tenant_bootstrap_operations o SET status='waiting_for_principal_verification',version=version+1,updated_at=$1
WHERE o.tenant_id=$2 AND o.id=$3 AND o.source_kind='core'
AND o.status IN ('waiting_for_principal_verification','attention_required') AND o.version=$4 AND o.superseded_by IS NULL
AND EXISTS(SELECT 1 FROM tenant_access a WHERE a.tenant_id=o.tenant_id AND a.status='bootstrap_pending')
AND EXISTS(SELECT 1 FROM tenant_invitations i WHERE i.tenant_id=o.tenant_id AND i.id=$5 AND i.bootstrap_operation_id=o.id
 AND i.normalized_email=o.intended_email AND i.status='pending' AND i.delivery_generation=$6 AND i.expires_at>clock_timestamp())
`

type ResumeReissuedCoreBootstrapParams struct {
	Now             pgtype.Timestamptz
	TenantID        uuid.UUID
	OperationID     uuid.UUID
	ExpectedVersion int64
	InvitationID    uuid.UUID
	Generation      int64
}

func (q *Queries) ResumeReissuedCoreBootstrap(ctx context.Context, arg ResumeReissuedCoreBootstrapParams) (int64, error) {
	result, err := q.db.Exec(ctx, resumeReissuedCoreBootstrap,
		arg.Now,
		arg.TenantID,
		arg.OperationID,
		arg.ExpectedVersion,
		arg.InvitationID,
		arg.Generation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
