// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_broker.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendCoreBrokerAuthorityReceipt = `-- name: AppendCoreBrokerAuthorityReceipt :exec
INSERT INTO tenant_broker_authority_receipts(
    consumer_id,broker_sequence,route_id,route_version,producer,source_sequence,epoch,event_id,tenant_id,raw_sha256,
    producer_principal_id,producer_binding_id,producer_principal_version,producer_binding_version,producer_grant_id,producer_grant_version,
    executor_principal_id,executor_binding_id,executor_principal_version,executor_binding_version,executor_grant_id,executor_grant_version,
    execution_grant_id,execution_grant_version)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
    $11,$12,$13,$14,$15,$16,
    $17,$18,$19,$20,$21,$22,
    $23,$24)
`

type AppendCoreBrokerAuthorityReceiptParams struct {
	ConsumerID               uuid.UUID
	BrokerSequence           int64
	RouteID                  uuid.UUID
	RouteVersion             int64
	Producer                 string
	SourceSequence           int64
	Epoch                    uuid.UUID
	EventID                  uuid.UUID
	TenantID                 pgtype.UUID
	RawSha256                []byte
	ProducerPrincipalID      uuid.UUID
	ProducerBindingID        uuid.UUID
	ProducerPrincipalVersion int64
	ProducerBindingVersion   int64
	ProducerGrantID          uuid.UUID
	ProducerGrantVersion     int64
	ExecutorPrincipalID      uuid.UUID
	ExecutorBindingID        uuid.UUID
	ExecutorPrincipalVersion int64
	ExecutorBindingVersion   int64
	ExecutorGrantID          uuid.UUID
	ExecutorGrantVersion     int64
	ExecutionGrantID         pgtype.UUID
	ExecutionGrantVersion    pgtype.Int8
}

func (q *Queries) AppendCoreBrokerAuthorityReceipt(ctx context.Context, arg AppendCoreBrokerAuthorityReceiptParams) error {
	_, err := q.db.Exec(ctx, appendCoreBrokerAuthorityReceipt,
		arg.ConsumerID,
		arg.BrokerSequence,
		arg.RouteID,
		arg.RouteVersion,
		arg.Producer,
		arg.SourceSequence,
		arg.Epoch,
		arg.EventID,
		arg.TenantID,
		arg.RawSha256,
		arg.ProducerPrincipalID,
		arg.ProducerBindingID,
		arg.ProducerPrincipalVersion,
		arg.ProducerBindingVersion,
		arg.ProducerGrantID,
		arg.ProducerGrantVersion,
		arg.ExecutorPrincipalID,
		arg.ExecutorBindingID,
		arg.ExecutorPrincipalVersion,
		arg.ExecutorBindingVersion,
		arg.ExecutorGrantID,
		arg.ExecutorGrantVersion,
		arg.ExecutionGrantID,
		arg.ExecutionGrantVersion,
	)
	return err
}

const appendCoreBrokerDLQ = `-- name: AppendCoreBrokerDLQ :exec
INSERT INTO core_broker_dlq(consumer_id,id,broker_sequence,broker_name,account_name,stream_name,subject,raw_payload,raw_sha256,headers,delivery_count,published_at,last_error)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type AppendCoreBrokerDLQParams struct {
	ConsumerID     uuid.UUID
	ID             uuid.UUID
	BrokerSequence int64
	BrokerName     string
	AccountName    string
	StreamName     string
	Subject        string
	RawPayload     []byte
	RawSha256      []byte
	Headers        []byte
	DeliveryCount  int64
	PublishedAt    pgtype.Timestamptz
	LastError      string
}

func (q *Queries) AppendCoreBrokerDLQ(ctx context.Context, arg AppendCoreBrokerDLQParams) error {
	_, err := q.db.Exec(ctx, appendCoreBrokerDLQ,
		arg.ConsumerID,
		arg.ID,
		arg.BrokerSequence,
		arg.BrokerName,
		arg.AccountName,
		arg.StreamName,
		arg.Subject,
		arg.RawPayload,
		arg.RawSha256,
		arg.Headers,
		arg.DeliveryCount,
		arg.PublishedAt,
		arg.LastError,
	)
	return err
}

const lockCoreBrokerAuthority = `-- name: LockCoreBrokerAuthority :exec
SELECT pg_advisory_xact_lock_shared(hashtextextended('ani-iam:core-broker-authority',0))
`

func (q *Queries) LockCoreBrokerAuthority(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockCoreBrokerAuthority)
	return err
}

const readCoreBootstrapBrokerAuthority = `-- name: ReadCoreBootstrapBrokerAuthority :one
SELECT a.consumer_id, a.broker_sequence, a.route_id, a.route_version, a.producer, a.source_sequence, a.epoch, a.event_id, a.tenant_id, a.raw_sha256, a.producer_principal_id, a.producer_binding_id, a.producer_principal_version, a.producer_binding_version, a.producer_grant_id, a.producer_grant_version, a.executor_principal_id, a.executor_binding_id, a.executor_principal_version, a.executor_binding_version, a.executor_grant_id, a.executor_grant_version, a.execution_grant_id, a.execution_grant_version, a.received_at FROM tenant_broker_authority_receipts a
JOIN core_bootstrap_receipts r ON r.tenant_id=a.tenant_id AND r.event_id=a.event_id
WHERE a.consumer_id=$1 AND a.tenant_id=$2 AND a.event_id=$3
  AND r.operation_id=$4 AND r.payload_fingerprint=$5 AND a.producer=$6 AND a.source_sequence=$7
ORDER BY a.broker_sequence LIMIT 1
`

type ReadCoreBootstrapBrokerAuthorityParams struct {
	ConsumerID         uuid.UUID
	TenantID           pgtype.UUID
	EventID            uuid.UUID
	OperationID        uuid.UUID
	PayloadFingerprint string
	Producer           string
	SourceSequence     int64
}

func (q *Queries) ReadCoreBootstrapBrokerAuthority(ctx context.Context, arg ReadCoreBootstrapBrokerAuthorityParams) (TenantBrokerAuthorityReceipt, error) {
	row := q.db.QueryRow(ctx, readCoreBootstrapBrokerAuthority,
		arg.ConsumerID,
		arg.TenantID,
		arg.EventID,
		arg.OperationID,
		arg.PayloadFingerprint,
		arg.Producer,
		arg.SourceSequence,
	)
	var i TenantBrokerAuthorityReceipt
	err := row.Scan(
		&i.ConsumerID,
		&i.BrokerSequence,
		&i.RouteID,
		&i.RouteVersion,
		&i.Producer,
		&i.SourceSequence,
		&i.Epoch,
		&i.EventID,
		&i.TenantID,
		&i.RawSha256,
		&i.ProducerPrincipalID,
		&i.ProducerBindingID,
		&i.ProducerPrincipalVersion,
		&i.ProducerBindingVersion,
		&i.ProducerGrantID,
		&i.ProducerGrantVersion,
		&i.ExecutorPrincipalID,
		&i.ExecutorBindingID,
		&i.ExecutorPrincipalVersion,
		&i.ExecutorBindingVersion,
		&i.ExecutorGrantID,
		&i.ExecutorGrantVersion,
		&i.ExecutionGrantID,
		&i.ExecutionGrantVersion,
		&i.ReceivedAt,
	)
	return i, err
}

const readCoreBrokerAuthorityReceipt = `-- name: ReadCoreBrokerAuthorityReceipt :one
SELECT consumer_id, broker_sequence, route_id, route_version, producer, source_sequence, epoch, event_id, tenant_id, raw_sha256, producer_principal_id, producer_binding_id, producer_principal_version, producer_binding_version, producer_grant_id, producer_grant_version, executor_principal_id, executor_binding_id, executor_principal_version, executor_binding_version, executor_grant_id, executor_grant_version, execution_grant_id, execution_grant_version, received_at FROM tenant_broker_authority_receipts
WHERE consumer_id=$1 AND broker_sequence=$2
`

type ReadCoreBrokerAuthorityReceiptParams struct {
	ConsumerID     uuid.UUID
	BrokerSequence int64
}

func (q *Queries) ReadCoreBrokerAuthorityReceipt(ctx context.Context, arg ReadCoreBrokerAuthorityReceiptParams) (TenantBrokerAuthorityReceipt, error) {
	row := q.db.QueryRow(ctx, readCoreBrokerAuthorityReceipt, arg.ConsumerID, arg.BrokerSequence)
	var i TenantBrokerAuthorityReceipt
	err := row.Scan(
		&i.ConsumerID,
		&i.BrokerSequence,
		&i.RouteID,
		&i.RouteVersion,
		&i.Producer,
		&i.SourceSequence,
		&i.Epoch,
		&i.EventID,
		&i.TenantID,
		&i.RawSha256,
		&i.ProducerPrincipalID,
		&i.ProducerBindingID,
		&i.ProducerPrincipalVersion,
		&i.ProducerBindingVersion,
		&i.ProducerGrantID,
		&i.ProducerGrantVersion,
		&i.ExecutorPrincipalID,
		&i.ExecutorBindingID,
		&i.ExecutorPrincipalVersion,
		&i.ExecutorBindingVersion,
		&i.ExecutorGrantID,
		&i.ExecutorGrantVersion,
		&i.ExecutionGrantID,
		&i.ExecutionGrantVersion,
		&i.ReceivedAt,
	)
	return i, err
}

const readCoreBrokerDLQPosition = `-- name: ReadCoreBrokerDLQPosition :one
SELECT consumer_id, id, broker_sequence, broker_name, account_name, stream_name, subject, raw_payload, raw_sha256, headers, delivery_count, published_at, last_error, quarantined_at FROM core_broker_dlq
WHERE consumer_id=$1 AND broker_sequence=$2
`

type ReadCoreBrokerDLQPositionParams struct {
	ConsumerID     uuid.UUID
	BrokerSequence int64
}

func (q *Queries) ReadCoreBrokerDLQPosition(ctx context.Context, arg ReadCoreBrokerDLQPositionParams) (CoreBrokerDlq, error) {
	row := q.db.QueryRow(ctx, readCoreBrokerDLQPosition, arg.ConsumerID, arg.BrokerSequence)
	var i CoreBrokerDlq
	err := row.Scan(
		&i.ConsumerID,
		&i.ID,
		&i.BrokerSequence,
		&i.BrokerName,
		&i.AccountName,
		&i.StreamName,
		&i.Subject,
		&i.RawPayload,
		&i.RawSha256,
		&i.Headers,
		&i.DeliveryCount,
		&i.PublishedAt,
		&i.LastError,
		&i.QuarantinedAt,
	)
	return i, err
}

const readCoreBrokerEventAuthority = `-- name: ReadCoreBrokerEventAuthority :one
SELECT consumer_id, broker_sequence, route_id, route_version, producer, source_sequence, epoch, event_id, tenant_id, raw_sha256, producer_principal_id, producer_binding_id, producer_principal_version, producer_binding_version, producer_grant_id, producer_grant_version, executor_principal_id, executor_binding_id, executor_principal_version, executor_binding_version, executor_grant_id, executor_grant_version, execution_grant_id, execution_grant_version, received_at FROM tenant_broker_authority_receipts
WHERE consumer_id=$1 AND event_id=$2
  AND tenant_id IS NOT DISTINCT FROM $3
ORDER BY broker_sequence LIMIT 1
`

type ReadCoreBrokerEventAuthorityParams struct {
	ConsumerID uuid.UUID
	EventID    uuid.UUID
	TenantID   pgtype.UUID
}

func (q *Queries) ReadCoreBrokerEventAuthority(ctx context.Context, arg ReadCoreBrokerEventAuthorityParams) (TenantBrokerAuthorityReceipt, error) {
	row := q.db.QueryRow(ctx, readCoreBrokerEventAuthority, arg.ConsumerID, arg.EventID, arg.TenantID)
	var i TenantBrokerAuthorityReceipt
	err := row.Scan(
		&i.ConsumerID,
		&i.BrokerSequence,
		&i.RouteID,
		&i.RouteVersion,
		&i.Producer,
		&i.SourceSequence,
		&i.Epoch,
		&i.EventID,
		&i.TenantID,
		&i.RawSha256,
		&i.ProducerPrincipalID,
		&i.ProducerBindingID,
		&i.ProducerPrincipalVersion,
		&i.ProducerBindingVersion,
		&i.ProducerGrantID,
		&i.ProducerGrantVersion,
		&i.ExecutorPrincipalID,
		&i.ExecutorBindingID,
		&i.ExecutorPrincipalVersion,
		&i.ExecutorBindingVersion,
		&i.ExecutorGrantID,
		&i.ExecutorGrantVersion,
		&i.ExecutionGrantID,
		&i.ExecutionGrantVersion,
		&i.ReceivedAt,
	)
	return i, err
}

const readCurrentCoreBrokerGrant = `-- name: ReadCurrentCoreBrokerGrant :one
SELECT p.id AS principal_id,b.id AS binding_id,g.id AS grant_id,
       p.version AS principal_version,b.version AS binding_version,g.version AS grant_version,
       r.version AS route_version,r.producer,r.producer_binding_id,r.target_sha256
FROM core_broker_grants g
JOIN core_broker_bindings b ON b.id=g.binding_id AND b.principal_id=g.principal_id
JOIN principals p ON p.id=b.principal_id
JOIN workload_principals w ON w.principal_id=p.id
JOIN core_broker_routes r ON r.id=g.route_id
WHERE b.id=$1 AND r.id=$2 AND g.action=$3
  AND b.nkey_public=$4
  AND b.environment=$5 AND b.trust_domain=$6
  AND w.environment=b.environment AND w.trust_domain=b.trust_domain AND w.owner_type='platform'
  AND p.principal_type='workload' AND p.status='active'
  AND b.status='active' AND g.status='active' AND r.status='active'
  AND b.broker_name=$7 AND b.account_name=$8
  AND r.broker_name=b.broker_name AND r.account_name=b.account_name
  AND r.stream_name=$9 AND r.subject=$10 AND r.schema_major=$11
  AND r.target_sha256=$12
  AND (g.action<>'publish' OR r.producer_binding_id=b.id)
`

type ReadCurrentCoreBrokerGrantParams struct {
	BindingID    uuid.UUID
	RouteID      uuid.UUID
	Action       string
	NkeyPublic   string
	Environment  string
	TrustDomain  string
	BrokerName   string
	AccountName  string
	StreamName   string
	Subject      string
	SchemaMajor  int32
	TargetSha256 string
}

type ReadCurrentCoreBrokerGrantRow struct {
	PrincipalID       uuid.UUID
	BindingID         uuid.UUID
	GrantID           uuid.UUID
	PrincipalVersion  int64
	BindingVersion    int64
	GrantVersion      int64
	RouteVersion      int64
	Producer          string
	ProducerBindingID uuid.UUID
	TargetSha256      string
}

func (q *Queries) ReadCurrentCoreBrokerGrant(ctx context.Context, arg ReadCurrentCoreBrokerGrantParams) (ReadCurrentCoreBrokerGrantRow, error) {
	row := q.db.QueryRow(ctx, readCurrentCoreBrokerGrant,
		arg.BindingID,
		arg.RouteID,
		arg.Action,
		arg.NkeyPublic,
		arg.Environment,
		arg.TrustDomain,
		arg.BrokerName,
		arg.AccountName,
		arg.StreamName,
		arg.Subject,
		arg.SchemaMajor,
		arg.TargetSha256,
	)
	var i ReadCurrentCoreBrokerGrantRow
	err := row.Scan(
		&i.PrincipalID,
		&i.BindingID,
		&i.GrantID,
		&i.PrincipalVersion,
		&i.BindingVersion,
		&i.GrantVersion,
		&i.RouteVersion,
		&i.Producer,
		&i.ProducerBindingID,
		&i.TargetSha256,
	)
	return i, err
}
