// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_broker_recovery.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendCoreBootstrapBrokerApproval = `-- name: AppendCoreBootstrapBrokerApproval :exec
INSERT INTO tenant_bootstrap_broker_approvals(tenant_id,id,consumer_id,broker_sequence,source_event_id,operation_id,kind,generation,authority_sha256,recovery_id,effect_audit_id,actor_id,reason_code)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type AppendCoreBootstrapBrokerApprovalParams struct {
	TenantID        uuid.UUID
	ID              uuid.UUID
	ConsumerID      uuid.UUID
	BrokerSequence  int64
	SourceEventID   uuid.UUID
	OperationID     uuid.UUID
	Kind            string
	Generation      int64
	AuthoritySha256 string
	RecoveryID      pgtype.UUID
	EffectAuditID   pgtype.UUID
	ActorID         uuid.UUID
	ReasonCode      string
}

func (q *Queries) AppendCoreBootstrapBrokerApproval(ctx context.Context, arg AppendCoreBootstrapBrokerApprovalParams) error {
	_, err := q.db.Exec(ctx, appendCoreBootstrapBrokerApproval,
		arg.TenantID,
		arg.ID,
		arg.ConsumerID,
		arg.BrokerSequence,
		arg.SourceEventID,
		arg.OperationID,
		arg.Kind,
		arg.Generation,
		arg.AuthoritySha256,
		arg.RecoveryID,
		arg.EffectAuditID,
		arg.ActorID,
		arg.ReasonCode,
	)
	return err
}

const hasCoreBootstrapBrokerApproval = `-- name: HasCoreBootstrapBrokerApproval :one
SELECT EXISTS(SELECT 1 FROM tenant_bootstrap_broker_approvals a
 WHERE a.tenant_id=$1 AND a.consumer_id=$2
 AND a.broker_sequence=$3 AND a.source_event_id=$4
 AND a.operation_id=$5 AND a.kind=$6 AND a.generation=$7
 AND a.authority_sha256=$8 AND a.recovery_id IS NOT DISTINCT FROM $9) AS approved
`

type HasCoreBootstrapBrokerApprovalParams struct {
	TenantID        uuid.UUID
	ConsumerID      uuid.UUID
	BrokerSequence  int64
	SourceEventID   uuid.UUID
	OperationID     uuid.UUID
	Kind            string
	Generation      int64
	AuthoritySha256 string
	RecoveryID      pgtype.UUID
}

// The current work loaded under the Tenant lock supplies kind/generation and
// recovery identity; mutable caller input cannot broaden an approval.
func (q *Queries) HasCoreBootstrapBrokerApproval(ctx context.Context, arg HasCoreBootstrapBrokerApprovalParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasCoreBootstrapBrokerApproval,
		arg.TenantID,
		arg.ConsumerID,
		arg.BrokerSequence,
		arg.SourceEventID,
		arg.OperationID,
		arg.Kind,
		arg.Generation,
		arg.AuthoritySha256,
		arg.RecoveryID,
	)
	var approved bool
	err := row.Scan(&approved)
	return approved, err
}
