// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_bootstrap_dispatcher.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendCoreBootstrapAttempt = `-- name: AppendCoreBootstrapAttempt :exec
INSERT INTO core_bootstrap_attempts(tenant_id,operation_id,kind,generation,attempt_number,lease_id,outcome,error_code,started_at,recovery_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type AppendCoreBootstrapAttemptParams struct {
	TenantID      uuid.UUID
	OperationID   uuid.UUID
	Kind          string
	Generation    int64
	AttemptNumber int32
	LeaseID       uuid.UUID
	Outcome       string
	ErrorCode     string
	StartedAt     pgtype.Timestamptz
	RecoveryID    pgtype.UUID
}

func (q *Queries) AppendCoreBootstrapAttempt(ctx context.Context, arg AppendCoreBootstrapAttemptParams) error {
	_, err := q.db.Exec(ctx, appendCoreBootstrapAttempt,
		arg.TenantID,
		arg.OperationID,
		arg.Kind,
		arg.Generation,
		arg.AttemptNumber,
		arg.LeaseID,
		arg.Outcome,
		arg.ErrorCode,
		arg.StartedAt,
		arg.RecoveryID,
	)
	return err
}

const claimCoreBootstrapJob = `-- name: ClaimCoreBootstrapJob :exec
UPDATE core_bootstrap_jobs SET state='claimed',attempt_count=attempt_count+1,lease_id=$1,lease_started_at=clock_timestamp(),lease_until=clock_timestamp()+interval '30 seconds',updated_at=clock_timestamp()
WHERE tenant_id=$2 AND operation_id=$3 AND kind=$4 AND generation=$5 AND producer=$6
`

type ClaimCoreBootstrapJobParams struct {
	LeaseID     pgtype.UUID
	TenantID    uuid.UUID
	OperationID uuid.UUID
	Kind        string
	Generation  int64
	Producer    string
}

func (q *Queries) ClaimCoreBootstrapJob(ctx context.Context, arg ClaimCoreBootstrapJobParams) error {
	_, err := q.db.Exec(ctx, claimCoreBootstrapJob,
		arg.LeaseID,
		arg.TenantID,
		arg.OperationID,
		arg.Kind,
		arg.Generation,
		arg.Producer,
	)
	return err
}

const createCoreBootstrapJob = `-- name: CreateCoreBootstrapJob :exec
INSERT INTO core_bootstrap_jobs(tenant_id,operation_id,kind,generation,producer,source_event_id)
VALUES($1,$2,$3,$4,$5,$6)
`

type CreateCoreBootstrapJobParams struct {
	TenantID      uuid.UUID
	OperationID   uuid.UUID
	Kind          string
	Generation    int64
	Producer      string
	SourceEventID uuid.UUID
}

func (q *Queries) CreateCoreBootstrapJob(ctx context.Context, arg CreateCoreBootstrapJobParams) error {
	_, err := q.db.Exec(ctx, createCoreBootstrapJob,
		arg.TenantID,
		arg.OperationID,
		arg.Kind,
		arg.Generation,
		arg.Producer,
		arg.SourceEventID,
	)
	return err
}

const discoverCoreBootstrapJobs = `-- name: DiscoverCoreBootstrapJobs :many
WITH eligible AS (
 SELECT r.tenant_id,r.operation_id,'initialize'::text AS kind,1::bigint AS generation,min(r.source_sequence) AS source_sequence
 FROM core_bootstrap_receipts r JOIN tenant_bootstrap_operations o ON o.tenant_id=r.tenant_id AND o.id=r.operation_id
 JOIN tenant_integration_receipts s ON s.producer=r.producer AND s.epoch=r.source_epoch AND s.event_id=r.event_id AND s.kind='bootstrap' AND s.tenant_id=r.tenant_id
 WHERE r.producer=$1 AND o.source_kind='core' AND o.status='pending' AND o.superseded_by IS NULL
 GROUP BY r.tenant_id,r.operation_id
 UNION ALL
 SELECT r.tenant_id,r.operation_id,'expire'::text,i.delivery_generation AS generation,min(r.source_sequence)
 FROM core_bootstrap_receipts r JOIN tenant_bootstrap_operations o ON o.tenant_id=r.tenant_id AND o.id=r.operation_id
 JOIN core_bootstrap_worker_results w ON w.tenant_id=o.tenant_id AND w.operation_id=o.id
 JOIN tenant_invitations i ON i.tenant_id=w.tenant_id AND i.id=w.invitation_id
 WHERE r.producer=$1 AND o.source_kind='core' AND o.status='waiting_for_principal_verification' AND o.superseded_by IS NULL
 AND i.status IN ('pending','expired') AND i.expires_at<=clock_timestamp()
 GROUP BY r.tenant_id,r.operation_id,i.delivery_generation
), candidates AS (
 SELECT e.tenant_id,e.operation_id,e.kind,e.generation,e.source_sequence FROM eligible e
 LEFT JOIN core_bootstrap_jobs j ON j.tenant_id=e.tenant_id AND j.operation_id=e.operation_id AND j.kind=e.kind AND j.generation=e.generation
 WHERE j.tenant_id IS NULL OR (j.state='pending' AND j.available_at<=clock_timestamp())
 UNION
 SELECT j.tenant_id,j.operation_id,j.kind,j.generation,r.source_sequence FROM core_bootstrap_jobs j
 JOIN core_bootstrap_receipts r ON r.tenant_id=j.tenant_id AND r.event_id=j.source_event_id
 WHERE j.producer=$1 AND j.state='claimed' AND j.lease_until<=clock_timestamp()
)
SELECT tenant_id,operation_id,kind,generation FROM candidates ORDER BY source_sequence,tenant_id,kind LIMIT 32
`

type DiscoverCoreBootstrapJobsParams struct {
	Producer string
}

type DiscoverCoreBootstrapJobsRow struct {
	TenantID    uuid.UUID
	OperationID uuid.UUID
	Kind        string
	Generation  int64
}

// Discovery returns only exact work identifiers. All following locks and writes
// carry Tenant/operation/kind and the configured producer.
func (q *Queries) DiscoverCoreBootstrapJobs(ctx context.Context, arg DiscoverCoreBootstrapJobsParams) ([]DiscoverCoreBootstrapJobsRow, error) {
	rows, err := q.db.Query(ctx, discoverCoreBootstrapJobs, arg.Producer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverCoreBootstrapJobsRow{}
	for rows.Next() {
		var i DiscoverCoreBootstrapJobsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.OperationID,
			&i.Kind,
			&i.Generation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishCoreBootstrapJob = `-- name: FinishCoreBootstrapJob :exec
UPDATE core_bootstrap_jobs SET state=$1,available_at=$2,last_error=$3,lease_id=NULL,lease_started_at=NULL,lease_until=NULL,updated_at=clock_timestamp()
WHERE tenant_id=$4 AND operation_id=$5 AND kind=$6 AND generation=$7 AND producer=$8
`

type FinishCoreBootstrapJobParams struct {
	State       string
	AvailableAt pgtype.Timestamptz
	ErrorCode   string
	TenantID    uuid.UUID
	OperationID uuid.UUID
	Kind        string
	Generation  int64
	Producer    string
}

func (q *Queries) FinishCoreBootstrapJob(ctx context.Context, arg FinishCoreBootstrapJobParams) error {
	_, err := q.db.Exec(ctx, finishCoreBootstrapJob,
		arg.State,
		arg.AvailableAt,
		arg.ErrorCode,
		arg.TenantID,
		arg.OperationID,
		arg.Kind,
		arg.Generation,
		arg.Producer,
	)
	return err
}

const lockCoreBootstrapJob = `-- name: LockCoreBootstrapJob :one
SELECT tenant_id, operation_id, kind, producer, source_event_id, state, attempt_count, lease_id, lease_started_at, lease_until, available_at, last_error, created_at, updated_at, generation, cycle_start_attempt, recovery_id,COALESCE(lease_until>clock_timestamp(),false)::boolean AS lease_current,available_at<=clock_timestamp() AS due,clock_timestamp()::timestamptz AS observed_at
FROM core_bootstrap_jobs WHERE tenant_id=$1 AND operation_id=$2 AND kind=$3 AND generation=$4 AND producer=$5 FOR UPDATE
`

type LockCoreBootstrapJobParams struct {
	TenantID    uuid.UUID
	OperationID uuid.UUID
	Kind        string
	Generation  int64
	Producer    string
}

type LockCoreBootstrapJobRow struct {
	TenantID          uuid.UUID
	OperationID       uuid.UUID
	Kind              string
	Producer          string
	SourceEventID     uuid.UUID
	State             string
	AttemptCount      int32
	LeaseID           pgtype.UUID
	LeaseStartedAt    pgtype.Timestamptz
	LeaseUntil        pgtype.Timestamptz
	AvailableAt       pgtype.Timestamptz
	LastError         string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Generation        int64
	CycleStartAttempt int32
	RecoveryID        pgtype.UUID
	LeaseCurrent      bool
	Due               bool
	ObservedAt        pgtype.Timestamptz
}

func (q *Queries) LockCoreBootstrapJob(ctx context.Context, arg LockCoreBootstrapJobParams) (LockCoreBootstrapJobRow, error) {
	row := q.db.QueryRow(ctx, lockCoreBootstrapJob,
		arg.TenantID,
		arg.OperationID,
		arg.Kind,
		arg.Generation,
		arg.Producer,
	)
	var i LockCoreBootstrapJobRow
	err := row.Scan(
		&i.TenantID,
		&i.OperationID,
		&i.Kind,
		&i.Producer,
		&i.SourceEventID,
		&i.State,
		&i.AttemptCount,
		&i.LeaseID,
		&i.LeaseStartedAt,
		&i.LeaseUntil,
		&i.AvailableAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Generation,
		&i.CycleStartAttempt,
		&i.RecoveryID,
		&i.LeaseCurrent,
		&i.Due,
		&i.ObservedAt,
	)
	return i, err
}

const markCoreBootstrapInvitationAttention = `-- name: MarkCoreBootstrapInvitationAttention :execrows
UPDATE tenant_bootstrap_operations o SET status='attention_required',version=version+1,updated_at=$1
WHERE o.tenant_id=$2 AND o.id=$3 AND o.source_kind='core' AND o.status='waiting_for_principal_verification'
AND o.version=$4 AND o.superseded_by IS NULL
AND EXISTS(SELECT 1 FROM tenant_invitations i WHERE i.tenant_id=o.tenant_id AND i.bootstrap_operation_id=o.id AND i.id=$5
 AND i.status='expired' AND i.expires_at<=clock_timestamp())
`

type MarkCoreBootstrapInvitationAttentionParams struct {
	Now             pgtype.Timestamptz
	TenantID        uuid.UUID
	OperationID     uuid.UUID
	ExpectedVersion int64
	InvitationID    uuid.UUID
}

func (q *Queries) MarkCoreBootstrapInvitationAttention(ctx context.Context, arg MarkCoreBootstrapInvitationAttentionParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCoreBootstrapInvitationAttention,
		arg.Now,
		arg.TenantID,
		arg.OperationID,
		arg.ExpectedVersion,
		arg.InvitationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const readCoreBootstrapInvitation = `-- name: ReadCoreBootstrapInvitation :one
SELECT i.tenant_id, i.id, i.normalized_email, i.role_ids, i.locale, i.status, i.token_digest, i.delivery_generation, i.expires_at, i.version, i.created_by, i.created_at, i.updated_at, i.accepted_membership_id, i.accepted_principal_id, i.bootstrap_operation_id FROM core_bootstrap_worker_results w JOIN tenant_invitations i ON i.tenant_id=w.tenant_id AND i.id=w.invitation_id
WHERE w.tenant_id=$1 AND w.operation_id=$2
`

type ReadCoreBootstrapInvitationParams struct {
	TenantID    uuid.UUID
	OperationID uuid.UUID
}

func (q *Queries) ReadCoreBootstrapInvitation(ctx context.Context, arg ReadCoreBootstrapInvitationParams) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, readCoreBootstrapInvitation, arg.TenantID, arg.OperationID)
	var i TenantInvitation
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.NormalizedEmail,
		&i.RoleIds,
		&i.Locale,
		&i.Status,
		&i.TokenDigest,
		&i.DeliveryGeneration,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedMembershipID,
		&i.AcceptedPrincipalID,
		&i.BootstrapOperationID,
	)
	return i, err
}
