// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_bootstrap_receipt.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendCoreBootstrapReceipt = `-- name: AppendCoreBootstrapReceipt :one
INSERT INTO core_bootstrap_receipts(tenant_id,event_id,operation_id,producer,source_sequence,source_epoch,payload_fingerprint,raw_payload,raw_sha256,occurred_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING received_at
`

type AppendCoreBootstrapReceiptParams struct {
	TenantID           uuid.UUID
	EventID            uuid.UUID
	OperationID        uuid.UUID
	Producer           string
	SourceSequence     int64
	SourceEpoch        pgtype.UUID
	PayloadFingerprint string
	RawPayload         []byte
	RawSha256          []byte
	OccurredAt         pgtype.Timestamptz
}

func (q *Queries) AppendCoreBootstrapReceipt(ctx context.Context, arg AppendCoreBootstrapReceiptParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, appendCoreBootstrapReceipt,
		arg.TenantID,
		arg.EventID,
		arg.OperationID,
		arg.Producer,
		arg.SourceSequence,
		arg.SourceEpoch,
		arg.PayloadFingerprint,
		arg.RawPayload,
		arg.RawSha256,
		arg.OccurredAt,
	)
	var received_at pgtype.Timestamptz
	err := row.Scan(&received_at)
	return received_at, err
}

const createCoreBootstrapOperation = `-- name: CreateCoreBootstrapOperation :execrows
INSERT INTO tenant_bootstrap_operations(tenant_id,id,source_kind,intended_email,payload_fingerprint,payload,status,version,created_at,updated_at)
VALUES($1,$2,'core',$3,$4,$5,'pending',1,statement_timestamp(),statement_timestamp())
ON CONFLICT DO NOTHING
`

type CreateCoreBootstrapOperationParams struct {
	TenantID           uuid.UUID
	ID                 uuid.UUID
	IntendedEmail      string
	PayloadFingerprint string
	Payload            []byte
}

func (q *Queries) CreateCoreBootstrapOperation(ctx context.Context, arg CreateCoreBootstrapOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, createCoreBootstrapOperation,
		arg.TenantID,
		arg.ID,
		arg.IntendedEmail,
		arg.PayloadFingerprint,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCoreBootstrapOperation = `-- name: GetCoreBootstrapOperation :one
SELECT tenant_id, id, source_kind, intended_email, intended_principal_id, payload_fingerprint, payload, status, version, recovery_request_id, supersedes, superseded_by, membership_id, principal_id, created_at, updated_at FROM tenant_bootstrap_operations
WHERE tenant_id=$1 AND id=$2 FOR UPDATE
`

type GetCoreBootstrapOperationParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetCoreBootstrapOperation(ctx context.Context, arg GetCoreBootstrapOperationParams) (TenantBootstrapOperation, error) {
	row := q.db.QueryRow(ctx, getCoreBootstrapOperation, arg.TenantID, arg.ID)
	var i TenantBootstrapOperation
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.SourceKind,
		&i.IntendedEmail,
		&i.IntendedPrincipalID,
		&i.PayloadFingerprint,
		&i.Payload,
		&i.Status,
		&i.Version,
		&i.RecoveryRequestID,
		&i.Supersedes,
		&i.SupersededBy,
		&i.MembershipID,
		&i.PrincipalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoreBootstrapReceipt = `-- name: GetCoreBootstrapReceipt :one
SELECT tenant_id, event_id, operation_id, producer, source_sequence, payload_fingerprint, raw_payload, raw_sha256, occurred_at, received_at, source_epoch FROM core_bootstrap_receipts
WHERE tenant_id=$1 AND event_id=$2
`

type GetCoreBootstrapReceiptParams struct {
	TenantID uuid.UUID
	EventID  uuid.UUID
}

func (q *Queries) GetCoreBootstrapReceipt(ctx context.Context, arg GetCoreBootstrapReceiptParams) (CoreBootstrapReceipt, error) {
	row := q.db.QueryRow(ctx, getCoreBootstrapReceipt, arg.TenantID, arg.EventID)
	var i CoreBootstrapReceipt
	err := row.Scan(
		&i.TenantID,
		&i.EventID,
		&i.OperationID,
		&i.Producer,
		&i.SourceSequence,
		&i.PayloadFingerprint,
		&i.RawPayload,
		&i.RawSha256,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.SourceEpoch,
	)
	return i, err
}
