// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_snapshot_rebuild.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const abandonCoreSnapshotAuthority = `-- name: AbandonCoreSnapshotAuthority :exec
UPDATE core_lifecycle_rebuilds SET state='abandoned',abandoned_reason='authority_changed'
WHERE producer=$1 AND snapshot_id=$2 AND state IN ('loading','loaded','catching_up')
`

type AbandonCoreSnapshotAuthorityParams struct {
	Producer   string
	SnapshotID uuid.UUID
}

func (q *Queries) AbandonCoreSnapshotAuthority(ctx context.Context, arg AbandonCoreSnapshotAuthorityParams) error {
	_, err := q.db.Exec(ctx, abandonCoreSnapshotAuthority, arg.Producer, arg.SnapshotID)
	return err
}

const abandonUnavailableCoreSnapshots = `-- name: AbandonUnavailableCoreSnapshots :exec
UPDATE core_lifecycle_rebuilds SET state='abandoned',abandoned_reason=CASE
 WHEN base_generation_id<>$1::uuid THEN 'superseded_generation'
 WHEN state='loading' AND expires_at<=clock_timestamp() THEN 'cursor_expired' ELSE 'authority_changed' END
WHERE producer=$2 AND state IN ('loading','loaded','catching_up')
 AND (base_generation_id<>$1::uuid OR (state='loading' AND expires_at<=clock_timestamp())
 OR ($3::text<>'' AND broker_authority_sha256<>$3))
`

type AbandonUnavailableCoreSnapshotsParams struct {
	GenerationID           uuid.UUID
	Producer               string
	CurrentAuthoritySha256 string
}

func (q *Queries) AbandonUnavailableCoreSnapshots(ctx context.Context, arg AbandonUnavailableCoreSnapshotsParams) error {
	_, err := q.db.Exec(ctx, abandonUnavailableCoreSnapshots, arg.GenerationID, arg.Producer, arg.CurrentAuthoritySha256)
	return err
}

const activateCoreSnapshotShadow = `-- name: ActivateCoreSnapshotShadow :exec
UPDATE core_lifecycle_pipelines SET generation_id=$1,highest_sequence=GREATEST(highest_sequence,$2::bigint) WHERE producer=$3
`

type ActivateCoreSnapshotShadowParams struct {
	GenerationID uuid.UUID
	SourceCut    int64
	Producer     string
}

func (q *Queries) ActivateCoreSnapshotShadow(ctx context.Context, arg ActivateCoreSnapshotShadowParams) error {
	_, err := q.db.Exec(ctx, activateCoreSnapshotShadow, arg.GenerationID, arg.SourceCut, arg.Producer)
	return err
}

const advanceCoreSnapshotPage = `-- name: AdvanceCoreSnapshotPage :exec
UPDATE core_lifecycle_rebuilds SET next_token=$1,last_tenant_id=$2,loaded_items=loaded_items+$3::bigint,
 state=CASE WHEN $1::text='' THEN 'loaded' ELSE 'loading' END
WHERE producer=$4 AND snapshot_id=$5
`

type AdvanceCoreSnapshotPageParams struct {
	NextToken    string
	LastTenantID pgtype.UUID
	ItemCount    int64
	Producer     string
	SnapshotID   uuid.UUID
}

func (q *Queries) AdvanceCoreSnapshotPage(ctx context.Context, arg AdvanceCoreSnapshotPageParams) error {
	_, err := q.db.Exec(ctx, advanceCoreSnapshotPage,
		arg.NextToken,
		arg.LastTenantID,
		arg.ItemCount,
		arg.Producer,
		arg.SnapshotID,
	)
	return err
}

const advanceCoreSnapshotReplay = `-- name: AdvanceCoreSnapshotReplay :exec
UPDATE core_lifecycle_rebuilds SET applied_through=$1,state='catching_up'
WHERE producer=$2 AND snapshot_id=$3
`

type AdvanceCoreSnapshotReplayParams struct {
	AppliedThrough int64
	Producer       string
	SnapshotID     uuid.UUID
}

func (q *Queries) AdvanceCoreSnapshotReplay(ctx context.Context, arg AdvanceCoreSnapshotReplayParams) error {
	_, err := q.db.Exec(ctx, advanceCoreSnapshotReplay, arg.AppliedThrough, arg.Producer, arg.SnapshotID)
	return err
}

const beginCoreSnapshotGeneration = `-- name: BeginCoreSnapshotGeneration :exec
INSERT INTO core_lifecycle_generations(producer,id,snapshot_source_cut) VALUES($1,$2,$3)
`

type BeginCoreSnapshotGenerationParams struct {
	Producer     string
	GenerationID uuid.UUID
	SourceCut    int64
}

func (q *Queries) BeginCoreSnapshotGeneration(ctx context.Context, arg BeginCoreSnapshotGenerationParams) error {
	_, err := q.db.Exec(ctx, beginCoreSnapshotGeneration, arg.Producer, arg.GenerationID, arg.SourceCut)
	return err
}

const beginCoreSnapshotRebuild = `-- name: BeginCoreSnapshotRebuild :exec
INSERT INTO core_lifecycle_rebuilds(producer,snapshot_id,generation_id,base_generation_id,consumer_id,source_cut,broker_after,page_size,expires_at,applied_through,broker_authority_sha256)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$6,$10)
`

type BeginCoreSnapshotRebuildParams struct {
	Producer              string
	SnapshotID            uuid.UUID
	GenerationID          uuid.UUID
	BaseGenerationID      uuid.UUID
	ConsumerID            uuid.UUID
	SourceCut             int64
	BrokerAfter           int64
	PageSize              int32
	ExpiresAt             pgtype.Timestamptz
	BrokerAuthoritySha256 string
}

func (q *Queries) BeginCoreSnapshotRebuild(ctx context.Context, arg BeginCoreSnapshotRebuildParams) error {
	_, err := q.db.Exec(ctx, beginCoreSnapshotRebuild,
		arg.Producer,
		arg.SnapshotID,
		arg.GenerationID,
		arg.BaseGenerationID,
		arg.ConsumerID,
		arg.SourceCut,
		arg.BrokerAfter,
		arg.PageSize,
		arg.ExpiresAt,
		arg.BrokerAuthoritySha256,
	)
	return err
}

const coreSnapshotCoversCurrent = `-- name: CoreSnapshotCoversCurrent :one
SELECT NOT EXISTS(
 SELECT 1 FROM core_lifecycle_projection_rows old LEFT JOIN core_lifecycle_projection_rows replacement
 ON replacement.producer=old.producer AND replacement.tenant_id=old.tenant_id AND replacement.generation_id=$1
 WHERE old.producer=$2 AND old.generation_id=$3
 AND (replacement.tenant_id IS NULL OR replacement.lifecycle_version<old.required_version OR replacement.repair_required
 OR (old.lifecycle_version=replacement.lifecycle_version AND old.status<>replacement.status)
 OR (old.status='disabled' AND replacement.status<>'disabled'))
) AND NOT EXISTS(SELECT 1 FROM core_lifecycle_projection_rows r WHERE r.producer=$2 AND r.generation_id=$1 AND (r.repair_required OR r.lifecycle_version=0)) AS covered
`

type CoreSnapshotCoversCurrentParams struct {
	NewGeneration uuid.UUID
	Producer      string
	OldGeneration uuid.UUID
}

func (q *Queries) CoreSnapshotCoversCurrent(ctx context.Context, arg CoreSnapshotCoversCurrentParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, coreSnapshotCoversCurrent, arg.NewGeneration, arg.Producer, arg.OldGeneration)
	var covered pgtype.Bool
	err := row.Scan(&covered)
	return covered, err
}

const coreSnapshotCursorUnexpired = `-- name: CoreSnapshotCursorUnexpired :one
SELECT $1::timestamptz>clock_timestamp() AS unexpired
`

type CoreSnapshotCursorUnexpiredParams struct {
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CoreSnapshotCursorUnexpired(ctx context.Context, arg CoreSnapshotCursorUnexpiredParams) (bool, error) {
	row := q.db.QueryRow(ctx, coreSnapshotCursorUnexpired, arg.ExpiresAt)
	var unexpired bool
	err := row.Scan(&unexpired)
	return unexpired, err
}

const coreSnapshotRecoveryNeeded = `-- name: CoreSnapshotRecoveryNeeded :one
SELECT EXISTS(SELECT 1 FROM core_lifecycle_projection_rows r WHERE r.producer=$1
 AND r.generation_id=$2 AND r.repair_required)
 OR NOT COALESCE((SELECT b.state='activated' AND b.created_at>clock_timestamp()-interval '1 hour'
 FROM core_lifecycle_rebuilds b WHERE b.producer=$1
 ORDER BY b.created_at DESC,b.snapshot_id DESC LIMIT 1),false) AS needed
`

type CoreSnapshotRecoveryNeededParams struct {
	Producer     string
	GenerationID uuid.UUID
}

func (q *Queries) CoreSnapshotRecoveryNeeded(ctx context.Context, arg CoreSnapshotRecoveryNeededParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, coreSnapshotRecoveryNeeded, arg.Producer, arg.GenerationID)
	var needed pgtype.Bool
	err := row.Scan(&needed)
	return needed, err
}

const getCoreSnapshotPageReceipt = `-- name: GetCoreSnapshotPageReceipt :one
SELECT page_fingerprint FROM core_lifecycle_rebuild_pages WHERE producer=$1 AND snapshot_id=$2 AND request_token=$3
`

type GetCoreSnapshotPageReceiptParams struct {
	Producer     string
	SnapshotID   uuid.UUID
	RequestToken string
}

func (q *Queries) GetCoreSnapshotPageReceipt(ctx context.Context, arg GetCoreSnapshotPageReceiptParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCoreSnapshotPageReceipt, arg.Producer, arg.SnapshotID, arg.RequestToken)
	var page_fingerprint []byte
	err := row.Scan(&page_fingerprint)
	return page_fingerprint, err
}

const insertCoreSnapshotFact = `-- name: InsertCoreSnapshotFact :exec
INSERT INTO core_lifecycle_projection_rows(producer,generation_id,tenant_id,lifecycle_version,required_version,status,reason,repair_required,snapshot_base)
VALUES($1,$2,$3,$4,$4,$5,'',false,true)
`

type InsertCoreSnapshotFactParams struct {
	Producer     string
	GenerationID uuid.UUID
	TenantID     uuid.UUID
	Version      int64
	Status       string
}

func (q *Queries) InsertCoreSnapshotFact(ctx context.Context, arg InsertCoreSnapshotFactParams) error {
	_, err := q.db.Exec(ctx, insertCoreSnapshotFact,
		arg.Producer,
		arg.GenerationID,
		arg.TenantID,
		arg.Version,
		arg.Status,
	)
	return err
}

const listCoreSnapshotIncrements = `-- name: ListCoreSnapshotIncrements :many
SELECT producer, event_id, source_sequence, kind, tenant_id, raw_payload, raw_sha256, domain_fingerprint, occurred_at, received_at, outcome, lifecycle_version, lifecycle_status, lifecycle_reason, lifecycle_effective_at FROM core_integration_receipts WHERE producer=$1 AND kind='lifecycle'
 AND source_sequence>$2 AND source_sequence<=$3
ORDER BY source_sequence LIMIT 500
`

type ListCoreSnapshotIncrementsParams struct {
	Producer        string
	AfterSequence   int64
	ThroughSequence int64
}

func (q *Queries) ListCoreSnapshotIncrements(ctx context.Context, arg ListCoreSnapshotIncrementsParams) ([]CoreIntegrationReceipt, error) {
	rows, err := q.db.Query(ctx, listCoreSnapshotIncrements, arg.Producer, arg.AfterSequence, arg.ThroughSequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreIntegrationReceipt{}
	for rows.Next() {
		var i CoreIntegrationReceipt
		if err := rows.Scan(
			&i.Producer,
			&i.EventID,
			&i.SourceSequence,
			&i.Kind,
			&i.TenantID,
			&i.RawPayload,
			&i.RawSha256,
			&i.DomainFingerprint,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.Outcome,
			&i.LifecycleVersion,
			&i.LifecycleStatus,
			&i.LifecycleReason,
			&i.LifecycleEffectiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCoreSnapshotRebuild = `-- name: LockCoreSnapshotRebuild :one
SELECT producer, snapshot_id, generation_id, base_generation_id, consumer_id, source_cut, broker_after, page_size, expires_at, next_token, last_tenant_id, loaded_items, applied_through, state, created_at, abandoned_reason, broker_authority_sha256,expires_at>clock_timestamp() AS unexpired FROM core_lifecycle_rebuilds
WHERE producer=$1 AND snapshot_id=$2 FOR UPDATE
`

type LockCoreSnapshotRebuildParams struct {
	Producer   string
	SnapshotID uuid.UUID
}

type LockCoreSnapshotRebuildRow struct {
	Producer              string
	SnapshotID            uuid.UUID
	GenerationID          uuid.UUID
	BaseGenerationID      uuid.UUID
	ConsumerID            uuid.UUID
	SourceCut             int64
	BrokerAfter           int64
	PageSize              int32
	ExpiresAt             pgtype.Timestamptz
	NextToken             string
	LastTenantID          pgtype.UUID
	LoadedItems           int64
	AppliedThrough        int64
	State                 string
	CreatedAt             pgtype.Timestamptz
	AbandonedReason       string
	BrokerAuthoritySha256 string
	Unexpired             bool
}

func (q *Queries) LockCoreSnapshotRebuild(ctx context.Context, arg LockCoreSnapshotRebuildParams) (LockCoreSnapshotRebuildRow, error) {
	row := q.db.QueryRow(ctx, lockCoreSnapshotRebuild, arg.Producer, arg.SnapshotID)
	var i LockCoreSnapshotRebuildRow
	err := row.Scan(
		&i.Producer,
		&i.SnapshotID,
		&i.GenerationID,
		&i.BaseGenerationID,
		&i.ConsumerID,
		&i.SourceCut,
		&i.BrokerAfter,
		&i.PageSize,
		&i.ExpiresAt,
		&i.NextToken,
		&i.LastTenantID,
		&i.LoadedItems,
		&i.AppliedThrough,
		&i.State,
		&i.CreatedAt,
		&i.AbandonedReason,
		&i.BrokerAuthoritySha256,
		&i.Unexpired,
	)
	return i, err
}

const markCoreSnapshotActivated = `-- name: MarkCoreSnapshotActivated :exec
UPDATE core_lifecycle_rebuilds SET state='activated' WHERE producer=$1 AND snapshot_id=$2
`

type MarkCoreSnapshotActivatedParams struct {
	Producer   string
	SnapshotID uuid.UUID
}

func (q *Queries) MarkCoreSnapshotActivated(ctx context.Context, arg MarkCoreSnapshotActivatedParams) error {
	_, err := q.db.Exec(ctx, markCoreSnapshotActivated, arg.Producer, arg.SnapshotID)
	return err
}

const readCoreSnapshotCut = `-- name: ReadCoreSnapshotCut :one
SELECT snapshot_source_cut FROM core_lifecycle_generations WHERE producer=$1 AND id=$2
`

type ReadCoreSnapshotCutParams struct {
	Producer     string
	GenerationID uuid.UUID
}

func (q *Queries) ReadCoreSnapshotCut(ctx context.Context, arg ReadCoreSnapshotCutParams) (int64, error) {
	row := q.db.QueryRow(ctx, readCoreSnapshotCut, arg.Producer, arg.GenerationID)
	var snapshot_source_cut int64
	err := row.Scan(&snapshot_source_cut)
	return snapshot_source_cut, err
}

const readPendingCoreSnapshot = `-- name: ReadPendingCoreSnapshot :one
SELECT producer, snapshot_id, generation_id, base_generation_id, consumer_id, source_cut, broker_after, page_size, expires_at, next_token, last_tenant_id, loaded_items, applied_through, state, created_at, abandoned_reason, broker_authority_sha256 FROM core_lifecycle_rebuilds WHERE producer=$1
 AND state IN ('loading','loaded','catching_up') ORDER BY created_at,snapshot_id LIMIT 1
`

type ReadPendingCoreSnapshotParams struct {
	Producer string
}

func (q *Queries) ReadPendingCoreSnapshot(ctx context.Context, arg ReadPendingCoreSnapshotParams) (CoreLifecycleRebuild, error) {
	row := q.db.QueryRow(ctx, readPendingCoreSnapshot, arg.Producer)
	var i CoreLifecycleRebuild
	err := row.Scan(
		&i.Producer,
		&i.SnapshotID,
		&i.GenerationID,
		&i.BaseGenerationID,
		&i.ConsumerID,
		&i.SourceCut,
		&i.BrokerAfter,
		&i.PageSize,
		&i.ExpiresAt,
		&i.NextToken,
		&i.LastTenantID,
		&i.LoadedItems,
		&i.AppliedThrough,
		&i.State,
		&i.CreatedAt,
		&i.AbandonedReason,
		&i.BrokerAuthoritySha256,
	)
	return i, err
}

const recordCoreSnapshotPage = `-- name: RecordCoreSnapshotPage :exec
INSERT INTO core_lifecycle_rebuild_pages(producer,snapshot_id,request_token,page_fingerprint,next_token,item_count)
VALUES($1,$2,$3,$4,$5,$6)
`

type RecordCoreSnapshotPageParams struct {
	Producer        string
	SnapshotID      uuid.UUID
	RequestToken    string
	PageFingerprint []byte
	NextToken       string
	ItemCount       int32
}

func (q *Queries) RecordCoreSnapshotPage(ctx context.Context, arg RecordCoreSnapshotPageParams) error {
	_, err := q.db.Exec(ctx, recordCoreSnapshotPage,
		arg.Producer,
		arg.SnapshotID,
		arg.RequestToken,
		arg.PageFingerprint,
		arg.NextToken,
		arg.ItemCount,
	)
	return err
}
