// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core_dlq_replay.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendCoreDLQAttempt = `-- name: AppendCoreDLQAttempt :exec
INSERT INTO core_broker_dlq_attempts(consumer_id,entry_id,id,attempt_number,raw_sha256,request_hash,actor_id,reason_code,outcome,projection_outcome,error_code,authority_sha256,audit_event_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type AppendCoreDLQAttemptParams struct {
	ConsumerID        uuid.UUID
	EntryID           uuid.UUID
	ID                uuid.UUID
	AttemptNumber     int64
	RawSha256         []byte
	RequestHash       []byte
	ActorID           uuid.UUID
	ReasonCode        string
	Outcome           string
	ProjectionOutcome string
	ErrorCode         string
	AuthoritySha256   string
	AuditEventID      uuid.UUID
}

func (q *Queries) AppendCoreDLQAttempt(ctx context.Context, arg AppendCoreDLQAttemptParams) error {
	_, err := q.db.Exec(ctx, appendCoreDLQAttempt,
		arg.ConsumerID,
		arg.EntryID,
		arg.ID,
		arg.AttemptNumber,
		arg.RawSha256,
		arg.RequestHash,
		arg.ActorID,
		arg.ReasonCode,
		arg.Outcome,
		arg.ProjectionOutcome,
		arg.ErrorCode,
		arg.AuthoritySha256,
		arg.AuditEventID,
	)
	return err
}

const appendCoreDLQContext = `-- name: AppendCoreDLQContext :exec
INSERT INTO core_broker_dlq_context(consumer_id,entry_id,configuration,configuration_sha256)
VALUES($1,$2,$3,$4)
`

type AppendCoreDLQContextParams struct {
	ConsumerID          uuid.UUID
	EntryID             uuid.UUID
	Configuration       []byte
	ConfigurationSha256 []byte
}

func (q *Queries) AppendCoreDLQContext(ctx context.Context, arg AppendCoreDLQContextParams) error {
	_, err := q.db.Exec(ctx, appendCoreDLQContext,
		arg.ConsumerID,
		arg.EntryID,
		arg.Configuration,
		arg.ConfigurationSha256,
	)
	return err
}

const listCoreDLQAttempts = `-- name: ListCoreDLQAttempts :many
SELECT consumer_id, entry_id, id, attempt_number, raw_sha256, request_hash, actor_id, reason_code, outcome, projection_outcome, error_code, authority_sha256, audit_event_id, created_at FROM core_broker_dlq_attempts WHERE consumer_id=$1 AND entry_id=$2
 AND attempt_number>$3 ORDER BY attempt_number LIMIT $4
`

type ListCoreDLQAttemptsParams struct {
	ConsumerID   uuid.UUID
	EntryID      uuid.UUID
	AfterAttempt int64
	PageLimit    int32
}

func (q *Queries) ListCoreDLQAttempts(ctx context.Context, arg ListCoreDLQAttemptsParams) ([]CoreBrokerDlqAttempt, error) {
	rows, err := q.db.Query(ctx, listCoreDLQAttempts,
		arg.ConsumerID,
		arg.EntryID,
		arg.AfterAttempt,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreBrokerDlqAttempt{}
	for rows.Next() {
		var i CoreBrokerDlqAttempt
		if err := rows.Scan(
			&i.ConsumerID,
			&i.EntryID,
			&i.ID,
			&i.AttemptNumber,
			&i.RawSha256,
			&i.RequestHash,
			&i.ActorID,
			&i.ReasonCode,
			&i.Outcome,
			&i.ProjectionOutcome,
			&i.ErrorCode,
			&i.AuthoritySha256,
			&i.AuditEventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreDLQEntries = `-- name: ListCoreDLQEntries :many
SELECT d.id FROM core_broker_dlq d WHERE d.consumer_id=$1 AND d.id>$2
ORDER BY d.id LIMIT $3
`

type ListCoreDLQEntriesParams struct {
	ConsumerID uuid.UUID
	AfterID    uuid.UUID
	PageLimit  int32
}

func (q *Queries) ListCoreDLQEntries(ctx context.Context, arg ListCoreDLQEntriesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCoreDLQEntries, arg.ConsumerID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCoreDLQHumanAuthority = `-- name: LockCoreDLQHumanAuthority :one
SELECT p.id FROM platform_session_grants g
JOIN sessions s ON s.id=g.session_id AND s.principal_id=g.principal_id AND s.audience='boss'
JOIN platform_memberships m ON m.id=g.membership_id AND m.principal_id=g.principal_id
JOIN principals p ON p.id=g.principal_id AND p.principal_type='human'
WHERE p.id=$1 AND s.id=$2 AND g.id=$3
FOR SHARE OF p,s,g,m
`

type LockCoreDLQHumanAuthorityParams struct {
	PrincipalID uuid.UUID
	SessionID   uuid.UUID
	GrantID     uuid.UUID
}

func (q *Queries) LockCoreDLQHumanAuthority(ctx context.Context, arg LockCoreDLQHumanAuthorityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCoreDLQHumanAuthority, arg.PrincipalID, arg.SessionID, arg.GrantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const readCoreDLQContext = `-- name: ReadCoreDLQContext :one
SELECT consumer_id, entry_id, configuration, configuration_sha256, created_at FROM core_broker_dlq_context WHERE consumer_id=$1 AND entry_id=$2
`

type ReadCoreDLQContextParams struct {
	ConsumerID uuid.UUID
	EntryID    uuid.UUID
}

func (q *Queries) ReadCoreDLQContext(ctx context.Context, arg ReadCoreDLQContextParams) (CoreBrokerDlqContext, error) {
	row := q.db.QueryRow(ctx, readCoreDLQContext, arg.ConsumerID, arg.EntryID)
	var i CoreBrokerDlqContext
	err := row.Scan(
		&i.ConsumerID,
		&i.EntryID,
		&i.Configuration,
		&i.ConfigurationSha256,
		&i.CreatedAt,
	)
	return i, err
}

const readCoreDLQEntry = `-- name: ReadCoreDLQEntry :one
SELECT d.consumer_id, d.id, d.broker_sequence, d.broker_name, d.account_name, d.stream_name, d.subject, d.raw_payload, d.raw_sha256, d.headers, d.delivery_count, d.published_at, d.last_error, d.quarantined_at,COALESCE((SELECT max(a.attempt_number) FROM core_broker_dlq_attempts a WHERE a.consumer_id=d.consumer_id AND a.entry_id=d.id),0)::bigint AS last_attempt
FROM core_broker_dlq d WHERE d.consumer_id=$1 AND d.id=$2
`

type ReadCoreDLQEntryParams struct {
	ConsumerID uuid.UUID
	EntryID    uuid.UUID
}

type ReadCoreDLQEntryRow struct {
	ConsumerID     uuid.UUID
	ID             uuid.UUID
	BrokerSequence int64
	BrokerName     string
	AccountName    string
	StreamName     string
	Subject        string
	RawPayload     []byte
	RawSha256      []byte
	Headers        []byte
	DeliveryCount  int64
	PublishedAt    pgtype.Timestamptz
	LastError      string
	QuarantinedAt  pgtype.Timestamptz
	LastAttempt    int64
}

func (q *Queries) ReadCoreDLQEntry(ctx context.Context, arg ReadCoreDLQEntryParams) (ReadCoreDLQEntryRow, error) {
	row := q.db.QueryRow(ctx, readCoreDLQEntry, arg.ConsumerID, arg.EntryID)
	var i ReadCoreDLQEntryRow
	err := row.Scan(
		&i.ConsumerID,
		&i.ID,
		&i.BrokerSequence,
		&i.BrokerName,
		&i.AccountName,
		&i.StreamName,
		&i.Subject,
		&i.RawPayload,
		&i.RawSha256,
		&i.Headers,
		&i.DeliveryCount,
		&i.PublishedAt,
		&i.LastError,
		&i.QuarantinedAt,
		&i.LastAttempt,
	)
	return i, err
}
