// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: first_administrator.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFirstAdministratorCompletion = `-- name: GetFirstAdministratorCompletion :one
SELECT intent_id FROM first_administrator_completions WHERE environment=$1
`

type GetFirstAdministratorCompletionParams struct {
	Environment string
}

func (q *Queries) GetFirstAdministratorCompletion(ctx context.Context, arg GetFirstAdministratorCompletionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFirstAdministratorCompletion, arg.Environment)
	var intent_id uuid.UUID
	err := row.Scan(&intent_id)
	return intent_id, err
}

const getFirstAdministratorIntent = `-- name: GetFirstAdministratorIntent :one
SELECT intent_id, environment, normalized_email, issuer, subject, intent_sha256, supersedes, registered_at, expires_at, audit_event_id FROM first_administrator_intents WHERE intent_id=$1
`

type GetFirstAdministratorIntentParams struct {
	IntentID uuid.UUID
}

func (q *Queries) GetFirstAdministratorIntent(ctx context.Context, arg GetFirstAdministratorIntentParams) (FirstAdministratorIntent, error) {
	row := q.db.QueryRow(ctx, getFirstAdministratorIntent, arg.IntentID)
	var i FirstAdministratorIntent
	err := row.Scan(
		&i.IntentID,
		&i.Environment,
		&i.NormalizedEmail,
		&i.Issuer,
		&i.Subject,
		&i.IntentSha256,
		&i.Supersedes,
		&i.RegisteredAt,
		&i.ExpiresAt,
		&i.AuditEventID,
	)
	return i, err
}

const getFirstAdministratorLeaf = `-- name: GetFirstAdministratorLeaf :one
SELECT i.intent_id, i.environment, i.normalized_email, i.issuer, i.subject, i.intent_sha256, i.supersedes, i.registered_at, i.expires_at, i.audit_event_id FROM first_administrator_intents i
WHERE i.environment=$1
AND NOT EXISTS (SELECT 1 FROM first_administrator_intents s WHERE s.environment=i.environment AND s.supersedes=i.intent_id)
`

type GetFirstAdministratorLeafParams struct {
	Environment string
}

func (q *Queries) GetFirstAdministratorLeaf(ctx context.Context, arg GetFirstAdministratorLeafParams) (FirstAdministratorIntent, error) {
	row := q.db.QueryRow(ctx, getFirstAdministratorLeaf, arg.Environment)
	var i FirstAdministratorIntent
	err := row.Scan(
		&i.IntentID,
		&i.Environment,
		&i.NormalizedEmail,
		&i.Issuer,
		&i.Subject,
		&i.IntentSha256,
		&i.Supersedes,
		&i.RegisteredAt,
		&i.ExpiresAt,
		&i.AuditEventID,
	)
	return i, err
}

const insertFirstAdministratorIntent = `-- name: InsertFirstAdministratorIntent :exec
INSERT INTO first_administrator_intents(intent_id,environment,normalized_email,issuer,subject,intent_sha256,supersedes,registered_at,expires_at,audit_event_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertFirstAdministratorIntentParams struct {
	IntentID        uuid.UUID
	Environment     string
	NormalizedEmail string
	Issuer          string
	Subject         string
	IntentSha256    []byte
	Supersedes      pgtype.UUID
	RegisteredAt    pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	AuditEventID    uuid.UUID
}

func (q *Queries) InsertFirstAdministratorIntent(ctx context.Context, arg InsertFirstAdministratorIntentParams) error {
	_, err := q.db.Exec(ctx, insertFirstAdministratorIntent,
		arg.IntentID,
		arg.Environment,
		arg.NormalizedEmail,
		arg.Issuer,
		arg.Subject,
		arg.IntentSha256,
		arg.Supersedes,
		arg.RegisteredAt,
		arg.ExpiresAt,
		arg.AuditEventID,
	)
	return err
}

const insertFirstAdministratorIntentAudit = `-- name: InsertFirstAdministratorIntentAudit :exec
INSERT INTO iam_audit_events(event_id,authentication_method,boundary,action,target_type,target_id,target_version,result,reason,
request_id,correlation_id,decision_id,source_service,occurred_at,recorded_at,provisioner_role,first_administrator_intent_id)
VALUES($1,'administrator_provisioner','platform','administrator.intent.register','first_administrator_intent',$2,1,'succeeded','REVIEWED_INTENT_REGISTERED',
$3,$3,$4,'ani-iam-provisioner',$5,$5,current_user,$2)
`

type InsertFirstAdministratorIntentAuditParams struct {
	EventID      uuid.UUID
	IntentID     uuid.UUID
	RequestID    string
	IntentDigest string
	Now          pgtype.Timestamptz
}

func (q *Queries) InsertFirstAdministratorIntentAudit(ctx context.Context, arg InsertFirstAdministratorIntentAuditParams) error {
	_, err := q.db.Exec(ctx, insertFirstAdministratorIntentAudit,
		arg.EventID,
		arg.IntentID,
		arg.RequestID,
		arg.IntentDigest,
		arg.Now,
	)
	return err
}

const lockFirstAdministrator = `-- name: LockFirstAdministrator :exec
SELECT pg_advisory_xact_lock(hashtextextended('first-administrator:' || $1::text,0))
`

type LockFirstAdministratorParams struct {
	Environment string
}

func (q *Queries) LockFirstAdministrator(ctx context.Context, arg LockFirstAdministratorParams) error {
	_, err := q.db.Exec(ctx, lockFirstAdministrator, arg.Environment)
	return err
}
