// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invited_account.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendInvitedAccountAudit = `-- name: AppendInvitedAccountAudit :exec
INSERT INTO iam_audit_events(tenant_id,event_id,actor_id,authentication_method,boundary,action,target_type,target_id,target_version,result,reason,request_id,correlation_id,decision_id,source_service,occurred_at,recorded_at,caller_principal_id,caller_binding_id,caller_binding_version,caller_grant_version)
VALUES(NULL,$1,$2,$3,'principal',$4,'invited_account_verification',$5,$6,$7,$8,$9,$10,$11,'ani-iam',$12,$12,$13,$14,$15,$16)
`

type AppendInvitedAccountAuditParams struct {
	ID                   uuid.UUID
	ActorID              pgtype.UUID
	AuthenticationMethod string
	Action               string
	ChallengeID          uuid.UUID
	Version              int64
	Result               string
	Reason               string
	RequestID            string
	CorrelationID        string
	DecisionID           string
	Now                  pgtype.Timestamptz
	CallerID             pgtype.UUID
	BindingID            pgtype.UUID
	BindingVersion       pgtype.Int8
	GrantVersion         pgtype.Int8
}

func (q *Queries) AppendInvitedAccountAudit(ctx context.Context, arg AppendInvitedAccountAuditParams) error {
	_, err := q.db.Exec(ctx, appendInvitedAccountAudit,
		arg.ID,
		arg.ActorID,
		arg.AuthenticationMethod,
		arg.Action,
		arg.ChallengeID,
		arg.Version,
		arg.Result,
		arg.Reason,
		arg.RequestID,
		arg.CorrelationID,
		arg.DecisionID,
		arg.Now,
		arg.CallerID,
		arg.BindingID,
		arg.BindingVersion,
		arg.GrantVersion,
	)
	return err
}

const cancelInactiveInvitedAccountDeliveries = `-- name: CancelInactiveInvitedAccountDeliveries :exec
UPDATE iam_invited_account_outbox o SET status='cancelled',payload_key_version=NULL,payload_ciphertext=NULL,claimed_at=NULL,version=version+1,updated_at=$1
WHERE o.status IN ('pending','claimed','attention_required')
AND EXISTS(SELECT 1 FROM iam_invited_account_verifications c WHERE c.id=o.challenge_id AND c.account_digest=$2 AND c.status<>'pending')
`

type CancelInactiveInvitedAccountDeliveriesParams struct {
	Now           pgtype.Timestamptz
	AccountDigest []byte
}

func (q *Queries) CancelInactiveInvitedAccountDeliveries(ctx context.Context, arg CancelInactiveInvitedAccountDeliveriesParams) error {
	_, err := q.db.Exec(ctx, cancelInactiveInvitedAccountDeliveries, arg.Now, arg.AccountDigest)
	return err
}

const consumeInvitedAccountVerification = `-- name: ConsumeInvitedAccountVerification :execrows
UPDATE iam_invited_account_verifications SET status='consumed',principal_id=$1,completion_key=$2,completion_intent=$3,version=version+1,updated_at=$4
WHERE id=$5 AND version=$6 AND status='pending' AND failed_attempts<5 AND expires_at>$4 AND expires_at>statement_timestamp()
`

type ConsumeInvitedAccountVerificationParams struct {
	PrincipalID     pgtype.UUID
	Key             pgtype.Text
	Intent          []byte
	Now             pgtype.Timestamptz
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) ConsumeInvitedAccountVerification(ctx context.Context, arg ConsumeInvitedAccountVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeInvitedAccountVerification,
		arg.PrincipalID,
		arg.Key,
		arg.Intent,
		arg.Now,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createInvitedAccountDelivery = `-- name: CreateInvitedAccountDelivery :exec
INSERT INTO iam_invited_account_outbox(id,challenge_id,payload_key_version,payload_ciphertext,status,available_at,version,created_at,updated_at)
VALUES($1,$2,$3,$4,'pending',$5,1,$5,$5)
`

type CreateInvitedAccountDeliveryParams struct {
	ID          uuid.UUID
	ChallengeID uuid.UUID
	KeyVersion  pgtype.Text
	Ciphertext  []byte
	Now         pgtype.Timestamptz
}

func (q *Queries) CreateInvitedAccountDelivery(ctx context.Context, arg CreateInvitedAccountDeliveryParams) error {
	_, err := q.db.Exec(ctx, createInvitedAccountDelivery,
		arg.ID,
		arg.ChallengeID,
		arg.KeyVersion,
		arg.Ciphertext,
		arg.Now,
	)
	return err
}

const createInvitedAccountVerification = `-- name: CreateInvitedAccountVerification :exec
INSERT INTO iam_invited_account_verifications(id,account_digest,normalized_email,code_key_version,code_digest,caller_principal_id,request_idempotency_key,status,failed_attempts,version,created_at,updated_at,expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7,'pending',0,1,$8,$8,$9)
`

type CreateInvitedAccountVerificationParams struct {
	ID                uuid.UUID
	AccountDigest     []byte
	Email             pgtype.Text
	KeyVersion        pgtype.Text
	CodeDigest        []byte
	CallerPrincipalID uuid.UUID
	Key               string
	Now               pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
}

func (q *Queries) CreateInvitedAccountVerification(ctx context.Context, arg CreateInvitedAccountVerificationParams) error {
	_, err := q.db.Exec(ctx, createInvitedAccountVerification,
		arg.ID,
		arg.AccountDigest,
		arg.Email,
		arg.KeyVersion,
		arg.CodeDigest,
		arg.CallerPrincipalID,
		arg.Key,
		arg.Now,
		arg.ExpiresAt,
	)
	return err
}

const createInvitedHuman = `-- name: CreateInvitedHuman :exec
INSERT INTO principals(id,principal_type,status,version,created_at,updated_at) VALUES($1,'human','active',1,$2,$2)
`

type CreateInvitedHumanParams struct {
	ID  uuid.UUID
	Now pgtype.Timestamptz
}

func (q *Queries) CreateInvitedHuman(ctx context.Context, arg CreateInvitedHumanParams) error {
	_, err := q.db.Exec(ctx, createInvitedHuman, arg.ID, arg.Now)
	return err
}

const createInvitedVerifiedEmail = `-- name: CreateInvitedVerifiedEmail :exec
INSERT INTO verified_emails(principal_id,normalized_email,verified_at,created_at,updated_at) VALUES($1,$2,$3,$3,$3)
`

type CreateInvitedVerifiedEmailParams struct {
	PrincipalID uuid.UUID
	Email       string
	Now         pgtype.Timestamptz
}

func (q *Queries) CreateInvitedVerifiedEmail(ctx context.Context, arg CreateInvitedVerifiedEmailParams) error {
	_, err := q.db.Exec(ctx, createInvitedVerifiedEmail, arg.PrincipalID, arg.Email, arg.Now)
	return err
}

const expireInvitedAccountVerification = `-- name: ExpireInvitedAccountVerification :execrows
UPDATE iam_invited_account_verifications SET status='expired',version=version+1,updated_at=$1
WHERE id=$2 AND version=$3 AND status='pending' AND expires_at<=statement_timestamp()
`

type ExpireInvitedAccountVerificationParams struct {
	Now             pgtype.Timestamptz
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) ExpireInvitedAccountVerification(ctx context.Context, arg ExpireInvitedAccountVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireInvitedAccountVerification, arg.Now, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failInvitedAccountVerification = `-- name: FailInvitedAccountVerification :execrows
UPDATE iam_invited_account_verifications SET failed_attempts=failed_attempts+1,status=CASE WHEN failed_attempts=4 THEN 'exhausted' ELSE 'pending' END,version=version+1,updated_at=$1
WHERE id=$2 AND version=$3 AND status='pending' AND failed_attempts<5
`

type FailInvitedAccountVerificationParams struct {
	Now             pgtype.Timestamptz
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) FailInvitedAccountVerification(ctx context.Context, arg FailInvitedAccountVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, failInvitedAccountVerification, arg.Now, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findInvitedAccountRequest = `-- name: FindInvitedAccountRequest :one
SELECT id, account_digest, normalized_email, code_key_version, code_digest, caller_principal_id, request_idempotency_key, status, failed_attempts, version, created_at, updated_at, expires_at, principal_id, completion_key, completion_intent FROM iam_invited_account_verifications WHERE request_idempotency_key=$1 FOR UPDATE
`

type FindInvitedAccountRequestParams struct {
	Key string
}

func (q *Queries) FindInvitedAccountRequest(ctx context.Context, arg FindInvitedAccountRequestParams) (IamInvitedAccountVerification, error) {
	row := q.db.QueryRow(ctx, findInvitedAccountRequest, arg.Key)
	var i IamInvitedAccountVerification
	err := row.Scan(
		&i.ID,
		&i.AccountDigest,
		&i.NormalizedEmail,
		&i.CodeKeyVersion,
		&i.CodeDigest,
		&i.CallerPrincipalID,
		&i.RequestIdempotencyKey,
		&i.Status,
		&i.FailedAttempts,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PrincipalID,
		&i.CompletionKey,
		&i.CompletionIntent,
	)
	return i, err
}

const getInvitedAccountVerification = `-- name: GetInvitedAccountVerification :one
SELECT id, account_digest, normalized_email, code_key_version, code_digest, caller_principal_id, request_idempotency_key, status, failed_attempts, version, created_at, updated_at, expires_at, principal_id, completion_key, completion_intent FROM iam_invited_account_verifications WHERE id=$1 FOR UPDATE
`

type GetInvitedAccountVerificationParams struct {
	ID uuid.UUID
}

func (q *Queries) GetInvitedAccountVerification(ctx context.Context, arg GetInvitedAccountVerificationParams) (IamInvitedAccountVerification, error) {
	row := q.db.QueryRow(ctx, getInvitedAccountVerification, arg.ID)
	var i IamInvitedAccountVerification
	err := row.Scan(
		&i.ID,
		&i.AccountDigest,
		&i.NormalizedEmail,
		&i.CodeKeyVersion,
		&i.CodeDigest,
		&i.CallerPrincipalID,
		&i.RequestIdempotencyKey,
		&i.Status,
		&i.FailedAttempts,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PrincipalID,
		&i.CompletionKey,
		&i.CompletionIntent,
	)
	return i, err
}

const invitedAccountEligibility = `-- name: InvitedAccountEligibility :one
SELECT NOT EXISTS(SELECT 1 FROM verified_emails e WHERE e.normalized_email=$1)
 AND NOT EXISTS(SELECT 1 FROM identities p WHERE p.provider='password' AND p.issuer='ani-local' AND p.subject=$1)
 AND (EXISTS(SELECT 1 FROM tenant_invitations t WHERE t.tenant_id=ANY($2::uuid[]) AND t.normalized_email=$1 AND t.status='pending' AND t.expires_at>statement_timestamp())
 OR EXISTS(SELECT 1 FROM platform_invitations p WHERE p.normalized_email=$1 AND p.status='pending' AND p.expires_at>statement_timestamp())) AS eligible
`

type InvitedAccountEligibilityParams struct {
	Email     string
	TenantIds []uuid.UUID
}

func (q *Queries) InvitedAccountEligibility(ctx context.Context, arg InvitedAccountEligibilityParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, invitedAccountEligibility, arg.Email, arg.TenantIds)
	var eligible pgtype.Bool
	err := row.Scan(&eligible)
	return eligible, err
}

const invitedAccountTenantBoundaries = `-- name: InvitedAccountTenantBoundaries :many
SELECT DISTINCT tenant_id FROM tenant_invitations WHERE normalized_email=$1 AND status='pending' AND expires_at>statement_timestamp() ORDER BY tenant_id
`

type InvitedAccountTenantBoundariesParams struct {
	Email string
}

func (q *Queries) InvitedAccountTenantBoundaries(ctx context.Context, arg InvitedAccountTenantBoundariesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, invitedAccountTenantBoundaries, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var tenant_id uuid.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeInvitedAccountVerifications = `-- name: SupersedeInvitedAccountVerifications :exec
UPDATE iam_invited_account_verifications SET status='superseded',version=version+1,updated_at=$1
WHERE account_digest=$2 AND status='pending'
`

type SupersedeInvitedAccountVerificationsParams struct {
	Now           pgtype.Timestamptz
	AccountDigest []byte
}

func (q *Queries) SupersedeInvitedAccountVerifications(ctx context.Context, arg SupersedeInvitedAccountVerificationsParams) error {
	_, err := q.db.Exec(ctx, supersedeInvitedAccountVerifications, arg.Now, arg.AccountDigest)
	return err
}
