// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation_bootstrap.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateInvitationBootstrapAccess = `-- name: ActivateInvitationBootstrapAccess :execrows
UPDATE tenant_access SET status='active',version=version+1,updated_at=$1
WHERE tenant_id=$2 AND status='bootstrap_pending' AND version=$3
`

type ActivateInvitationBootstrapAccessParams struct {
	Now             pgtype.Timestamptz
	TenantID        uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) ActivateInvitationBootstrapAccess(ctx context.Context, arg ActivateInvitationBootstrapAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateInvitationBootstrapAccess, arg.Now, arg.TenantID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeInvitationBootstrap = `-- name: CompleteInvitationBootstrap :execrows
UPDATE tenant_bootstrap_operations o SET status='succeeded',membership_id=$1,principal_id=$2,version=version+1,updated_at=$3
WHERE o.tenant_id=$4 AND o.id=$5 AND o.version=$6
AND o.source_kind='core' AND o.status='waiting_for_principal_verification' AND o.superseded_by IS NULL
AND EXISTS(SELECT 1 FROM tenant_invitations i JOIN verified_emails e ON e.principal_id=i.accepted_principal_id
 WHERE i.tenant_id=o.tenant_id AND i.bootstrap_operation_id=o.id AND i.id=$7
 AND i.status='accepted' AND i.accepted_membership_id=$1 AND i.accepted_principal_id=$2
 AND i.normalized_email=o.intended_email AND e.normalized_email=o.intended_email)
`

type CompleteInvitationBootstrapParams struct {
	MembershipID    pgtype.UUID
	PrincipalID     pgtype.UUID
	Now             pgtype.Timestamptz
	TenantID        uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int64
	InvitationID    uuid.UUID
}

func (q *Queries) CompleteInvitationBootstrap(ctx context.Context, arg CompleteInvitationBootstrapParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeInvitationBootstrap,
		arg.MembershipID,
		arg.PrincipalID,
		arg.Now,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
		arg.InvitationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvitationBootstrapOperation = `-- name: GetInvitationBootstrapOperation :one
SELECT o.tenant_id, o.id, o.source_kind, o.intended_email, o.intended_principal_id, o.payload_fingerprint, o.payload, o.status, o.version, o.recovery_request_id, o.supersedes, o.superseded_by, o.membership_id, o.principal_id, o.created_at, o.updated_at FROM tenant_bootstrap_operations o
JOIN tenant_invitations i ON i.tenant_id=o.tenant_id AND i.bootstrap_operation_id=o.id
WHERE i.tenant_id=$1 AND i.id=$2
FOR UPDATE OF o
`

type GetInvitationBootstrapOperationParams struct {
	TenantID     uuid.UUID
	InvitationID uuid.UUID
}

func (q *Queries) GetInvitationBootstrapOperation(ctx context.Context, arg GetInvitationBootstrapOperationParams) (TenantBootstrapOperation, error) {
	row := q.db.QueryRow(ctx, getInvitationBootstrapOperation, arg.TenantID, arg.InvitationID)
	var i TenantBootstrapOperation
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.SourceKind,
		&i.IntendedEmail,
		&i.IntendedPrincipalID,
		&i.PayloadFingerprint,
		&i.Payload,
		&i.Status,
		&i.Version,
		&i.RecoveryRequestID,
		&i.Supersedes,
		&i.SupersededBy,
		&i.MembershipID,
		&i.PrincipalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
