// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation_password.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendInvitationPasswordDenial = `-- name: AppendInvitationPasswordDenial :exec
INSERT INTO iam_audit_events(event_id,authentication_method,boundary,action,target_type,target_id,target_version,result,reason,request_id,correlation_id,decision_id,source_service,occurred_at,recorded_at,caller_principal_id,caller_binding_id,caller_binding_version,caller_grant_version)
VALUES($1,'anonymous','principal','iam.invitation.authentication.denied','principal',$2,$3,'denied','CREDENTIAL_INVALID',$4,$5,$6,'ani-iam',$7,$7,$8,$9,$10,$11)
`

type AppendInvitationPasswordDenialParams struct {
	ID             uuid.UUID
	TargetID       uuid.UUID
	Version        int64
	RequestID      string
	CorrelationID  string
	DecisionID     string
	Now            pgtype.Timestamptz
	CallerID       pgtype.UUID
	BindingID      pgtype.UUID
	BindingVersion pgtype.Int8
	GrantVersion   pgtype.Int8
}

func (q *Queries) AppendInvitationPasswordDenial(ctx context.Context, arg AppendInvitationPasswordDenialParams) error {
	_, err := q.db.Exec(ctx, appendInvitationPasswordDenial,
		arg.ID,
		arg.TargetID,
		arg.Version,
		arg.RequestID,
		arg.CorrelationID,
		arg.DecisionID,
		arg.Now,
		arg.CallerID,
		arg.BindingID,
		arg.BindingVersion,
		arg.GrantVersion,
	)
	return err
}

const lockInvitationPassword = `-- name: LockInvitationPassword :one
SELECT p.id AS principal_id,p.status AS principal_status,i.id AS identity_id,(i.status='active')::boolean AS identity_active,
e.normalized_email,c.password_hash,c.version AS credential_version,c.locked_until
FROM verified_emails e JOIN principals p ON p.id=e.principal_id AND p.principal_type='human'
JOIN password_credentials c ON c.principal_id=p.id
JOIN identities i ON i.id=c.identity_id AND i.principal_id=p.id AND i.provider='password' AND i.issuer='ani-local'
WHERE e.normalized_email=$1 FOR UPDATE OF c FOR SHARE OF p,i
`

type LockInvitationPasswordParams struct {
	Account string
}

type LockInvitationPasswordRow struct {
	PrincipalID       uuid.UUID
	PrincipalStatus   string
	IdentityID        uuid.UUID
	IdentityActive    bool
	NormalizedEmail   string
	PasswordHash      string
	CredentialVersion int64
	LockedUntil       pgtype.Timestamptz
}

func (q *Queries) LockInvitationPassword(ctx context.Context, arg LockInvitationPasswordParams) (LockInvitationPasswordRow, error) {
	row := q.db.QueryRow(ctx, lockInvitationPassword, arg.Account)
	var i LockInvitationPasswordRow
	err := row.Scan(
		&i.PrincipalID,
		&i.PrincipalStatus,
		&i.IdentityID,
		&i.IdentityActive,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.CredentialVersion,
		&i.LockedUntil,
	)
	return i, err
}

const readInvitationPassword = `-- name: ReadInvitationPassword :one
SELECT p.id AS principal_id,p.status AS principal_status,i.id AS identity_id,(i.status='active')::boolean AS identity_active,
e.normalized_email,c.password_hash,c.version AS credential_version,c.locked_until
FROM verified_emails e JOIN principals p ON p.id=e.principal_id AND p.principal_type='human'
JOIN password_credentials c ON c.principal_id=p.id
JOIN identities i ON i.id=c.identity_id AND i.principal_id=p.id AND i.provider='password' AND i.issuer='ani-local'
WHERE e.normalized_email=$1
`

type ReadInvitationPasswordParams struct {
	Account string
}

type ReadInvitationPasswordRow struct {
	PrincipalID       uuid.UUID
	PrincipalStatus   string
	IdentityID        uuid.UUID
	IdentityActive    bool
	NormalizedEmail   string
	PasswordHash      string
	CredentialVersion int64
	LockedUntil       pgtype.Timestamptz
}

func (q *Queries) ReadInvitationPassword(ctx context.Context, arg ReadInvitationPasswordParams) (ReadInvitationPasswordRow, error) {
	row := q.db.QueryRow(ctx, readInvitationPassword, arg.Account)
	var i ReadInvitationPasswordRow
	err := row.Scan(
		&i.PrincipalID,
		&i.PrincipalStatus,
		&i.IdentityID,
		&i.IdentityActive,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.CredentialVersion,
		&i.LockedUntil,
	)
	return i, err
}
