// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	TenantID      uuid.UUID
	KeyID         uuid.UUID
	PrincipalID   uuid.UUID
	Status        string
	DisplayPrefix string
	SecretDigest  []byte
	NeverExpires  bool
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	Version       int64
}

type IamAuditEvent struct {
	TenantID             pgtype.UUID
	EventID              uuid.UUID
	ActorID              pgtype.UUID
	AuthenticationMethod string
	Boundary             string
	Action               string
	TargetType           string
	TargetID             uuid.UUID
	TargetVersion        int64
	Result               string
	Reason               string
	RequestID            string
	CorrelationID        string
	DecisionID           string
	SourceService        string
	OccurredAt           pgtype.Timestamptz
	RecordedAt           pgtype.Timestamptz
}

type Identity struct {
	ID          uuid.UUID
	PrincipalID uuid.UUID
	Provider    string
	Issuer      string
	Subject     string
	Status      string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type NotificationOutbox struct {
	ID               uuid.UUID
	OperationID      uuid.UUID
	PrincipalID      uuid.UUID
	Intent           string
	DestinationEmail string
	Status           string
	AttemptCount     int32
	AvailableAt      pgtype.Timestamptz
	ClaimedAt        pgtype.Timestamptz
	DeliveredAt      pgtype.Timestamptz
	NotificationID   pgtype.Text
	Version          int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type PasswordAction struct {
	OperationID uuid.UUID
	PrincipalID uuid.UUID
	Purpose     string
	Status      string
	ExpiresAt   pgtype.Timestamptz
	ConsumedAt  pgtype.Timestamptz
	ReplacedBy  pgtype.UUID
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PasswordActionCompletion struct {
	IdempotencyKey    string
	OperationID       uuid.UUID
	PrincipalID       uuid.UUID
	CredentialVersion int64
	CompletedAt       pgtype.Timestamptz
}

type PasswordActionRequest struct {
	OperationID    uuid.UUID
	AccountDigest  []byte
	Audience       string
	PrincipalID    pgtype.UUID
	Purpose        pgtype.Text
	ExpiresAt      pgtype.Timestamptz
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
}

type PasswordCredential struct {
	PrincipalID    uuid.UUID
	IdentityID     uuid.UUID
	PasswordHash   string
	Algorithm      string
	FailedAttempts int32
	LockedUntil    pgtype.Timestamptz
	Version        int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type PermissionCatalog struct {
	Scope    string
	Resource string
	Action   string
}

type Principal struct {
	ID            uuid.UUID
	PrincipalType string
	Status        string
	Version       int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type RefreshToken struct {
	TenantID   uuid.UUID
	ID         uuid.UUID
	FamilyID   uuid.UUID
	Digest     []byte
	Status     string
	IssuedAt   pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	ReplacedBy pgtype.UUID
}

type RefreshTokenFamily struct {
	TenantID  uuid.UUID
	ID        uuid.UUID
	GrantID   uuid.UUID
	Status    string
	Version   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ServicePrincipal struct {
	PrincipalID    uuid.UUID
	TenantID       uuid.UUID
	MembershipID   uuid.UUID
	Name           string
	NormalizedName string
	Version        int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Session struct {
	ID                uuid.UUID
	PrincipalID       uuid.UUID
	Audience          string
	Status            string
	DeviceName        string
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	Version           int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ReauthenticatedAt pgtype.Timestamptz
	AuthnMethods      []string
}

type SessionGrant struct {
	TenantID     uuid.UUID
	ID           uuid.UUID
	SessionID    uuid.UUID
	MembershipID uuid.UUID
	Status       string
	Version      int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type TenantAccess struct {
	TenantID  uuid.UUID
	Status    string
	Version   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TenantLifecycleProjection struct {
	TenantID         uuid.UUID
	Status           string
	LifecycleVersion int64
	EffectiveAt      pgtype.Timestamptz
	ObservedAt       pgtype.Timestamptz
	FreshUntil       pgtype.Timestamptz
}

type TenantMembership struct {
	TenantID    uuid.UUID
	ID          uuid.UUID
	PrincipalID uuid.UUID
	Status      string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TenantRole struct {
	TenantID                uuid.UUID
	ID                      uuid.UUID
	Code                    string
	SystemRole              bool
	SystemDefinitionVersion int64
	Version                 int64
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type TenantRoleBinding struct {
	TenantID     uuid.UUID
	ID           uuid.UUID
	MembershipID uuid.UUID
	RoleID       uuid.UUID
	Version      int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type TenantRolePermission struct {
	TenantID  uuid.UUID
	RoleID    uuid.UUID
	Resource  string
	Action    string
	CreatedAt pgtype.Timestamptz
	Scope     string
}

type VerifiedEmail struct {
	PrincipalID     uuid.UUID
	NormalizedEmail string
	VerifiedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
