// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persistence.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendSecurityAuditEvent = `-- name: AppendSecurityAuditEvent :exec
INSERT INTO iam_audit_events (
    tenant_id,
    event_id,
    actor_id,
    authentication_method,
    boundary,
    action,
    target_type,
    target_id,
    target_version,
    result,
    reason,
    request_id,
    correlation_id,
    decision_id,
    source_service,
    occurred_at,
    recorded_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
`

type AppendSecurityAuditEventParams struct {
	TenantID             uuid.UUID
	EventID              uuid.UUID
	ActorID              uuid.UUID
	AuthenticationMethod string
	Boundary             string
	Action               string
	TargetType           string
	TargetID             uuid.UUID
	TargetVersion        int64
	Result               string
	Reason               string
	RequestID            string
	CorrelationID        string
	DecisionID           string
	SourceService        string
	OccurredAt           pgtype.Timestamptz
	RecordedAt           pgtype.Timestamptz
}

func (q *Queries) AppendSecurityAuditEvent(ctx context.Context, arg AppendSecurityAuditEventParams) error {
	_, err := q.db.Exec(ctx, appendSecurityAuditEvent,
		arg.TenantID,
		arg.EventID,
		arg.ActorID,
		arg.AuthenticationMethod,
		arg.Boundary,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetVersion,
		arg.Result,
		arg.Reason,
		arg.RequestID,
		arg.CorrelationID,
		arg.DecisionID,
		arg.SourceService,
		arg.OccurredAt,
		arg.RecordedAt,
	)
	return err
}

const createTenantMembership = `-- name: CreateTenantMembership :exec
INSERT INTO tenant_memberships (
    tenant_id,
    id,
    principal_id,
    status,
    version,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateTenantMembershipParams struct {
	TenantID    uuid.UUID
	ID          uuid.UUID
	PrincipalID uuid.UUID
	Status      string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateTenantMembership(ctx context.Context, arg CreateTenantMembershipParams) error {
	_, err := q.db.Exec(ctx, createTenantMembership,
		arg.TenantID,
		arg.ID,
		arg.PrincipalID,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTenantMembership = `-- name: GetTenantMembership :one
SELECT id, principal_id, status, version, created_at, updated_at
FROM tenant_memberships
WHERE tenant_id = $1
  AND id = $2
`

type GetTenantMembershipParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetTenantMembershipRow struct {
	ID          uuid.UUID
	PrincipalID uuid.UUID
	Status      string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetTenantMembership(ctx context.Context, arg GetTenantMembershipParams) (GetTenantMembershipRow, error) {
	row := q.db.QueryRow(ctx, getTenantMembership, arg.TenantID, arg.ID)
	var i GetTenantMembershipRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantMembershipStatus = `-- name: UpdateTenantMembershipStatus :one
UPDATE tenant_memberships
SET status = $1,
    version = version + 1,
    updated_at = $2
WHERE tenant_id = $3
  AND id = $4
  AND version = $5
RETURNING id, principal_id, status, version, created_at, updated_at
`

type UpdateTenantMembershipStatusParams struct {
	Status          string
	UpdatedAt       pgtype.Timestamptz
	TenantID        uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int64
}

type UpdateTenantMembershipStatusRow struct {
	ID          uuid.UUID
	PrincipalID uuid.UUID
	Status      string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateTenantMembershipStatus(ctx context.Context, arg UpdateTenantMembershipStatusParams) (UpdateTenantMembershipStatusRow, error) {
	row := q.db.QueryRow(ctx, updateTenantMembershipStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i UpdateTenantMembershipStatusRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
