// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_audit_query.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformAuditEvent = `-- name: GetPlatformAuditEvent :one
SELECT e.tenant_id, e.event_id, e.actor_id, e.authentication_method, e.boundary, e.action, e.target_type, e.target_id, e.target_version, e.result, e.reason, e.request_id, e.correlation_id, e.decision_id, e.source_service, e.occurred_at, e.recorded_at, e.caller_principal_id, e.caller_binding_id, e.caller_binding_version, e.caller_grant_version, e.provisioner_role, e.bootstrap_manifest_id, e.first_administrator_intent_id, (CASE WHEN e.authentication_method IN ('workload_provisioner','administrator_provisioner') THEN 'initialization'
 WHEN p.principal_type='workload' THEN 'workload' WHEN p.principal_type='human' THEN 'principal' ELSE 'anonymous' END)::text AS actor_type
FROM iam_audit_events e LEFT JOIN principals p ON p.id=e.actor_id
WHERE e.event_id=$1
`

type GetPlatformAuditEventParams struct {
	EventID uuid.UUID
}

type GetPlatformAuditEventRow struct {
	TenantID                   pgtype.UUID
	EventID                    uuid.UUID
	ActorID                    pgtype.UUID
	AuthenticationMethod       string
	Boundary                   string
	Action                     string
	TargetType                 string
	TargetID                   uuid.UUID
	TargetVersion              int64
	Result                     string
	Reason                     string
	RequestID                  string
	CorrelationID              string
	DecisionID                 string
	SourceService              string
	OccurredAt                 pgtype.Timestamptz
	RecordedAt                 pgtype.Timestamptz
	CallerPrincipalID          pgtype.UUID
	CallerBindingID            pgtype.UUID
	CallerBindingVersion       pgtype.Int8
	CallerGrantVersion         pgtype.Int8
	ProvisionerRole            pgtype.Text
	BootstrapManifestID        pgtype.UUID
	FirstAdministratorIntentID pgtype.UUID
	ActorType                  string
}

func (q *Queries) GetPlatformAuditEvent(ctx context.Context, arg GetPlatformAuditEventParams) (GetPlatformAuditEventRow, error) {
	row := q.db.QueryRow(ctx, getPlatformAuditEvent, arg.EventID)
	var i GetPlatformAuditEventRow
	err := row.Scan(
		&i.TenantID,
		&i.EventID,
		&i.ActorID,
		&i.AuthenticationMethod,
		&i.Boundary,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.TargetVersion,
		&i.Result,
		&i.Reason,
		&i.RequestID,
		&i.CorrelationID,
		&i.DecisionID,
		&i.SourceService,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.CallerPrincipalID,
		&i.CallerBindingID,
		&i.CallerBindingVersion,
		&i.CallerGrantVersion,
		&i.ProvisionerRole,
		&i.BootstrapManifestID,
		&i.FirstAdministratorIntentID,
		&i.ActorType,
	)
	return i, err
}

const listPlatformAuditEvents = `-- name: ListPlatformAuditEvents :many
SELECT e.tenant_id, e.event_id, e.actor_id, e.authentication_method, e.boundary, e.action, e.target_type, e.target_id, e.target_version, e.result, e.reason, e.request_id, e.correlation_id, e.decision_id, e.source_service, e.occurred_at, e.recorded_at, e.caller_principal_id, e.caller_binding_id, e.caller_binding_version, e.caller_grant_version, e.provisioner_role, e.bootstrap_manifest_id, e.first_administrator_intent_id, (CASE WHEN e.authentication_method IN ('workload_provisioner','administrator_provisioner') THEN 'initialization'
 WHEN p.principal_type='workload' THEN 'workload' WHEN p.principal_type='human' THEN 'principal' ELSE 'anonymous' END)::text AS actor_type
FROM iam_audit_events e LEFT JOIN principals p ON p.id=e.actor_id
WHERE ($1::uuid='00000000-0000-0000-0000-000000000000'::uuid OR e.tenant_id=$1)
 AND ($2::text='' OR e.action=$2)
 AND ($3::text='' OR e.result=$3)
 AND ($4::uuid='00000000-0000-0000-0000-000000000000'::uuid OR e.event_id<$4)
ORDER BY e.event_id DESC LIMIT $5
`

type ListPlatformAuditEventsParams struct {
	TenantID  uuid.UUID
	Action    string
	Result    string
	BeforeID  uuid.UUID
	PageLimit int32
}

type ListPlatformAuditEventsRow struct {
	TenantID                   pgtype.UUID
	EventID                    uuid.UUID
	ActorID                    pgtype.UUID
	AuthenticationMethod       string
	Boundary                   string
	Action                     string
	TargetType                 string
	TargetID                   uuid.UUID
	TargetVersion              int64
	Result                     string
	Reason                     string
	RequestID                  string
	CorrelationID              string
	DecisionID                 string
	SourceService              string
	OccurredAt                 pgtype.Timestamptz
	RecordedAt                 pgtype.Timestamptz
	CallerPrincipalID          pgtype.UUID
	CallerBindingID            pgtype.UUID
	CallerBindingVersion       pgtype.Int8
	CallerGrantVersion         pgtype.Int8
	ProvisionerRole            pgtype.Text
	BootstrapManifestID        pgtype.UUID
	FirstAdministratorIntentID pgtype.UUID
	ActorType                  string
}

func (q *Queries) ListPlatformAuditEvents(ctx context.Context, arg ListPlatformAuditEventsParams) ([]ListPlatformAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformAuditEvents,
		arg.TenantID,
		arg.Action,
		arg.Result,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformAuditEventsRow{}
	for rows.Next() {
		var i ListPlatformAuditEventsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.EventID,
			&i.ActorID,
			&i.AuthenticationMethod,
			&i.Boundary,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TargetVersion,
			&i.Result,
			&i.Reason,
			&i.RequestID,
			&i.CorrelationID,
			&i.DecisionID,
			&i.SourceService,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.CallerPrincipalID,
			&i.CallerBindingID,
			&i.CallerBindingVersion,
			&i.CallerGrantVersion,
			&i.ProvisionerRole,
			&i.BootstrapManifestID,
			&i.FirstAdministratorIntentID,
			&i.ActorType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
