// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_mutations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomPlatformRole = `-- name: CreateCustomPlatformRole :exec
INSERT INTO platform_roles(id,code,display_name,system_role,system_definition_version,version,created_at,updated_at)
VALUES($1,$2,$3,false,1,1,$4,$4)
`

type CreateCustomPlatformRoleParams struct {
	ID          uuid.UUID
	Code        string
	DisplayName string
	Now         pgtype.Timestamptz
}

func (q *Queries) CreateCustomPlatformRole(ctx context.Context, arg CreateCustomPlatformRoleParams) error {
	_, err := q.db.Exec(ctx, createCustomPlatformRole,
		arg.ID,
		arg.Code,
		arg.DisplayName,
		arg.Now,
	)
	return err
}

const deleteCustomPlatformRole = `-- name: DeleteCustomPlatformRole :execrows
DELETE FROM platform_roles WHERE id=$1 AND version=$2 AND NOT system_role
`

type DeleteCustomPlatformRoleParams struct {
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) DeleteCustomPlatformRole(ctx context.Context, arg DeleteCustomPlatformRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomPlatformRole, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCustomPlatformRolePermissions = `-- name: DeleteCustomPlatformRolePermissions :exec
DELETE FROM platform_role_permissions p USING platform_roles r WHERE p.role_id=r.id AND r.id=$1 AND NOT r.system_role
`

type DeleteCustomPlatformRolePermissionsParams struct {
	RoleID uuid.UUID
}

func (q *Queries) DeleteCustomPlatformRolePermissions(ctx context.Context, arg DeleteCustomPlatformRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, deleteCustomPlatformRolePermissions, arg.RoleID)
	return err
}

const findPlatformMutation = `-- name: FindPlatformMutation :one
SELECT request_hash,result,created_at,expires_at FROM platform_mutation_results
WHERE actor_principal_id=$1 AND operation=$2 AND idempotency_key=$3
`

type FindPlatformMutationParams struct {
	ActorID        uuid.UUID
	Operation      string
	IdempotencyKey string
}

type FindPlatformMutationRow struct {
	RequestHash []byte
	Result      []byte
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) FindPlatformMutation(ctx context.Context, arg FindPlatformMutationParams) (FindPlatformMutationRow, error) {
	row := q.db.QueryRow(ctx, findPlatformMutation, arg.ActorID, arg.Operation, arg.IdempotencyKey)
	var i FindPlatformMutationRow
	err := row.Scan(
		&i.RequestHash,
		&i.Result,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const platformRoleReferenced = `-- name: PlatformRoleReferenced :one
SELECT EXISTS(SELECT 1 FROM platform_role_bindings b WHERE b.role_id=$1
UNION ALL SELECT 1 FROM platform_invitation_roles i WHERE i.role_id=$1) AS referenced
`

type PlatformRoleReferencedParams struct {
	RoleID uuid.UUID
}

func (q *Queries) PlatformRoleReferenced(ctx context.Context, arg PlatformRoleReferencedParams) (bool, error) {
	row := q.db.QueryRow(ctx, platformRoleReferenced, arg.RoleID)
	var referenced bool
	err := row.Scan(&referenced)
	return referenced, err
}

const savePlatformMutation = `-- name: SavePlatformMutation :exec
INSERT INTO platform_mutation_results(actor_principal_id,operation,idempotency_key,request_hash,result,created_at,expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type SavePlatformMutationParams struct {
	ActorID        uuid.UUID
	Operation      string
	IdempotencyKey string
	RequestHash    []byte
	Result         []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) SavePlatformMutation(ctx context.Context, arg SavePlatformMutationParams) error {
	_, err := q.db.Exec(ctx, savePlatformMutation,
		arg.ActorID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.Result,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const updateCustomPlatformRole = `-- name: UpdateCustomPlatformRole :execrows
UPDATE platform_roles SET display_name=$1,version=version+1,updated_at=$2
WHERE id=$3 AND version=$4 AND NOT system_role
`

type UpdateCustomPlatformRoleParams struct {
	DisplayName     string
	Now             pgtype.Timestamptz
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateCustomPlatformRole(ctx context.Context, arg UpdateCustomPlatformRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCustomPlatformRole,
		arg.DisplayName,
		arg.Now,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePlatformTargetTenantAccess = `-- name: UpdatePlatformTargetTenantAccess :one
UPDATE tenant_access SET status=$1,version=version+1,updated_at=$2
WHERE tenant_id=$3 AND version=$4 RETURNING tenant_id, status, version, created_at, updated_at
`

type UpdatePlatformTargetTenantAccessParams struct {
	Status          string
	Now             pgtype.Timestamptz
	TenantID        uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdatePlatformTargetTenantAccess(ctx context.Context, arg UpdatePlatformTargetTenantAccessParams) (TenantAccess, error) {
	row := q.db.QueryRow(ctx, updatePlatformTargetTenantAccess,
		arg.Status,
		arg.Now,
		arg.TenantID,
		arg.ExpectedVersion,
	)
	var i TenantAccess
	err := row.Scan(
		&i.TenantID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
