// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_password.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const lockPlatformPassword = `-- name: LockPlatformPassword :one
SELECT p.id AS principal_id,p.status AS principal_status,i.id AS identity_id,(i.status='active')::boolean AS identity_active,
 e.normalized_email,COALESCE(m.id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS membership_id,
 COALESCE(m.status,'removed')::text AS membership_status,c.password_hash,c.version AS credential_version,c.locked_until
FROM verified_emails e JOIN principals p ON p.id=e.principal_id AND p.principal_type='human'
JOIN password_credentials c ON c.principal_id=p.id JOIN identities i ON i.id=c.identity_id AND i.principal_id=p.id AND i.provider='password'
LEFT JOIN platform_memberships m ON m.principal_id=p.id AND m.status<>'removed'
WHERE e.normalized_email=$1 FOR UPDATE OF c FOR SHARE OF p,i
`

type LockPlatformPasswordParams struct {
	Account string
}

type LockPlatformPasswordRow struct {
	PrincipalID       uuid.UUID
	PrincipalStatus   string
	IdentityID        uuid.UUID
	IdentityActive    bool
	NormalizedEmail   string
	MembershipID      uuid.UUID
	MembershipStatus  string
	PasswordHash      string
	CredentialVersion int64
	LockedUntil       pgtype.Timestamptz
}

func (q *Queries) LockPlatformPassword(ctx context.Context, arg LockPlatformPasswordParams) (LockPlatformPasswordRow, error) {
	row := q.db.QueryRow(ctx, lockPlatformPassword, arg.Account)
	var i LockPlatformPasswordRow
	err := row.Scan(
		&i.PrincipalID,
		&i.PrincipalStatus,
		&i.IdentityID,
		&i.IdentityActive,
		&i.NormalizedEmail,
		&i.MembershipID,
		&i.MembershipStatus,
		&i.PasswordHash,
		&i.CredentialVersion,
		&i.LockedUntil,
	)
	return i, err
}

const readPlatformPassword = `-- name: ReadPlatformPassword :one
SELECT p.id AS principal_id,p.status AS principal_status,i.id AS identity_id,(i.status='active')::boolean AS identity_active,
 e.normalized_email,COALESCE(m.id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS membership_id,
 COALESCE(m.status,'removed')::text AS membership_status,c.password_hash,c.version AS credential_version,c.locked_until
FROM verified_emails e JOIN principals p ON p.id=e.principal_id AND p.principal_type='human'
JOIN password_credentials c ON c.principal_id=p.id JOIN identities i ON i.id=c.identity_id AND i.principal_id=p.id AND i.provider='password'
LEFT JOIN platform_memberships m ON m.principal_id=p.id AND m.status<>'removed'
WHERE e.normalized_email=$1
`

type ReadPlatformPasswordParams struct {
	Account string
}

type ReadPlatformPasswordRow struct {
	PrincipalID       uuid.UUID
	PrincipalStatus   string
	IdentityID        uuid.UUID
	IdentityActive    bool
	NormalizedEmail   string
	MembershipID      uuid.UUID
	MembershipStatus  string
	PasswordHash      string
	CredentialVersion int64
	LockedUntil       pgtype.Timestamptz
}

func (q *Queries) ReadPlatformPassword(ctx context.Context, arg ReadPlatformPasswordParams) (ReadPlatformPasswordRow, error) {
	row := q.db.QueryRow(ctx, readPlatformPassword, arg.Account)
	var i ReadPlatformPasswordRow
	err := row.Scan(
		&i.PrincipalID,
		&i.PrincipalStatus,
		&i.IdentityID,
		&i.IdentityActive,
		&i.NormalizedEmail,
		&i.MembershipID,
		&i.MembershipStatus,
		&i.PasswordHash,
		&i.CredentialVersion,
		&i.LockedUntil,
	)
	return i, err
}
