// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_identity_link.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const lockPlatformIdentityLinkAuthentication = `-- name: LockPlatformIdentityLinkAuthentication :one
SELECT s.reauthenticated_at
FROM principals p JOIN platform_memberships m ON m.principal_id=p.id
JOIN platform_session_grants g ON g.membership_id=m.id AND g.principal_id=p.id
JOIN sessions s ON s.id=g.session_id AND s.principal_id=p.id
WHERE p.id=$1 AND p.principal_type='human' AND p.status='active'
AND m.status='active' AND g.id=$2 AND g.status='active' AND g.version=$3
AND s.id=$4 AND s.audience='boss' AND s.status='active'
AND s.idle_expires_at>statement_timestamp() AND s.absolute_expires_at>statement_timestamp()
FOR UPDATE OF p,m,g,s
`

type LockPlatformIdentityLinkAuthenticationParams struct {
	PrincipalID  uuid.UUID
	GrantID      uuid.UUID
	GrantVersion int64
	SessionID    uuid.UUID
}

func (q *Queries) LockPlatformIdentityLinkAuthentication(ctx context.Context, arg LockPlatformIdentityLinkAuthenticationParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lockPlatformIdentityLinkAuthentication,
		arg.PrincipalID,
		arg.GrantID,
		arg.GrantVersion,
		arg.SessionID,
	)
	var reauthenticated_at pgtype.Timestamptz
	err := row.Scan(&reauthenticated_at)
	return reauthenticated_at, err
}
