// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_login.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendPlatformHumanAudit = `-- name: AppendPlatformHumanAudit :exec
INSERT INTO iam_audit_events(event_id,actor_id,authentication_method,boundary,action,target_type,target_id,target_version,result,reason,
request_id,correlation_id,decision_id,source_service,occurred_at,recorded_at,caller_principal_id,caller_binding_id,caller_binding_version,caller_grant_version)
VALUES($1,$2,$3,'platform',$4,$5,$6,$7,
$8,$9,$10,$11,$12,'ani-iam',$13,$14,$15,$16,$17,$18)
`

type AppendPlatformHumanAuditParams struct {
	EventID              uuid.UUID
	ActorID              pgtype.UUID
	AuthenticationMethod string
	Action               string
	TargetType           string
	TargetID             uuid.UUID
	TargetVersion        int64
	Result               string
	Reason               string
	RequestID            string
	CorrelationID        string
	DecisionID           string
	OccurredAt           pgtype.Timestamptz
	RecordedAt           pgtype.Timestamptz
	CallerPrincipalID    pgtype.UUID
	CallerBindingID      pgtype.UUID
	CallerBindingVersion pgtype.Int8
	CallerGrantVersion   pgtype.Int8
}

func (q *Queries) AppendPlatformHumanAudit(ctx context.Context, arg AppendPlatformHumanAuditParams) error {
	_, err := q.db.Exec(ctx, appendPlatformHumanAudit,
		arg.EventID,
		arg.ActorID,
		arg.AuthenticationMethod,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetVersion,
		arg.Result,
		arg.Reason,
		arg.RequestID,
		arg.CorrelationID,
		arg.DecisionID,
		arg.OccurredAt,
		arg.RecordedAt,
		arg.CallerPrincipalID,
		arg.CallerBindingID,
		arg.CallerBindingVersion,
		arg.CallerGrantVersion,
	)
	return err
}

const completeFirstAdministratorIntent = `-- name: CompleteFirstAdministratorIntent :exec
INSERT INTO first_administrator_completions(environment,intent_id,principal_id,audit_event_id,completed_at)
VALUES($1,$2,$3,$4,$5)
`

type CompleteFirstAdministratorIntentParams struct {
	Environment  string
	IntentID     uuid.UUID
	PrincipalID  uuid.UUID
	AuditEventID uuid.UUID
	Now          pgtype.Timestamptz
}

func (q *Queries) CompleteFirstAdministratorIntent(ctx context.Context, arg CompleteFirstAdministratorIntentParams) error {
	_, err := q.db.Exec(ctx, completeFirstAdministratorIntent,
		arg.Environment,
		arg.IntentID,
		arg.PrincipalID,
		arg.AuditEventID,
		arg.Now,
	)
	return err
}

const createPlatformHuman = `-- name: CreatePlatformHuman :exec
INSERT INTO principals(id,principal_type,status,version,created_at,updated_at)
VALUES($1,'human','active',1,$2,$2)
`

type CreatePlatformHumanParams struct {
	ID  uuid.UUID
	Now pgtype.Timestamptz
}

func (q *Queries) CreatePlatformHuman(ctx context.Context, arg CreatePlatformHumanParams) error {
	_, err := q.db.Exec(ctx, createPlatformHuman, arg.ID, arg.Now)
	return err
}

const createPlatformMembership = `-- name: CreatePlatformMembership :exec
INSERT INTO platform_memberships(id,principal_id,status,version,created_at,updated_at)
VALUES($1,$2,'active',1,$3,$3)
`

type CreatePlatformMembershipParams struct {
	ID          uuid.UUID
	PrincipalID uuid.UUID
	Now         pgtype.Timestamptz
}

func (q *Queries) CreatePlatformMembership(ctx context.Context, arg CreatePlatformMembershipParams) error {
	_, err := q.db.Exec(ctx, createPlatformMembership, arg.ID, arg.PrincipalID, arg.Now)
	return err
}

const createPlatformRefreshFamily = `-- name: CreatePlatformRefreshFamily :exec
INSERT INTO platform_refresh_token_families(id,grant_id,status,version,created_at,updated_at)
VALUES($1,$2,'active',1,$3,$3)
`

type CreatePlatformRefreshFamilyParams struct {
	ID      uuid.UUID
	GrantID uuid.UUID
	Now     pgtype.Timestamptz
}

func (q *Queries) CreatePlatformRefreshFamily(ctx context.Context, arg CreatePlatformRefreshFamilyParams) error {
	_, err := q.db.Exec(ctx, createPlatformRefreshFamily, arg.ID, arg.GrantID, arg.Now)
	return err
}

const createPlatformRefreshToken = `-- name: CreatePlatformRefreshToken :exec
INSERT INTO platform_refresh_tokens(id,family_id,digest,status,issued_at,expires_at)
VALUES($1,$2,$3,'active',$4,$5)
`

type CreatePlatformRefreshTokenParams struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	Digest    []byte
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePlatformRefreshToken(ctx context.Context, arg CreatePlatformRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createPlatformRefreshToken,
		arg.ID,
		arg.FamilyID,
		arg.Digest,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const createPlatformRoleBinding = `-- name: CreatePlatformRoleBinding :exec
INSERT INTO platform_role_bindings(id,membership_id,role_id,version,created_at,updated_at)
VALUES($1,$2,$3,1,$4,$4)
`

type CreatePlatformRoleBindingParams struct {
	ID           uuid.UUID
	MembershipID uuid.UUID
	RoleID       uuid.UUID
	Now          pgtype.Timestamptz
}

func (q *Queries) CreatePlatformRoleBinding(ctx context.Context, arg CreatePlatformRoleBindingParams) error {
	_, err := q.db.Exec(ctx, createPlatformRoleBinding,
		arg.ID,
		arg.MembershipID,
		arg.RoleID,
		arg.Now,
	)
	return err
}

const createPlatformSessionGrant = `-- name: CreatePlatformSessionGrant :exec
INSERT INTO platform_session_grants(id,session_id,principal_id,membership_id,status,version,created_at,updated_at)
VALUES($1,$2,$3,$4,'active',1,$5,$5)
`

type CreatePlatformSessionGrantParams struct {
	ID           uuid.UUID
	SessionID    uuid.UUID
	PrincipalID  uuid.UUID
	MembershipID uuid.UUID
	Now          pgtype.Timestamptz
}

func (q *Queries) CreatePlatformSessionGrant(ctx context.Context, arg CreatePlatformSessionGrantParams) error {
	_, err := q.db.Exec(ctx, createPlatformSessionGrant,
		arg.ID,
		arg.SessionID,
		arg.PrincipalID,
		arg.MembershipID,
		arg.Now,
	)
	return err
}

const createPlatformVerifiedEmail = `-- name: CreatePlatformVerifiedEmail :exec
INSERT INTO verified_emails(principal_id,normalized_email,verified_at,created_at,updated_at)
VALUES($1,$2,$3,$3,$3)
`

type CreatePlatformVerifiedEmailParams struct {
	PrincipalID     uuid.UUID
	NormalizedEmail string
	Now             pgtype.Timestamptz
}

func (q *Queries) CreatePlatformVerifiedEmail(ctx context.Context, arg CreatePlatformVerifiedEmailParams) error {
	_, err := q.db.Exec(ctx, createPlatformVerifiedEmail, arg.PrincipalID, arg.NormalizedEmail, arg.Now)
	return err
}

const getPlatformAdministratorRole = `-- name: GetPlatformAdministratorRole :one
SELECT id, code, display_name, system_role, system_definition_version, version, created_at, updated_at FROM platform_roles WHERE code='platform-admin'
`

func (q *Queries) GetPlatformAdministratorRole(ctx context.Context) (PlatformRole, error) {
	row := q.db.QueryRow(ctx, getPlatformAdministratorRole)
	var i PlatformRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.SystemRole,
		&i.SystemDefinitionVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformRolePermissionSet = `-- name: GetPlatformRolePermissionSet :many
SELECT scope,resource,action FROM platform_role_permissions WHERE role_id=$1 ORDER BY scope,resource,action
`

type GetPlatformRolePermissionSetParams struct {
	RoleID uuid.UUID
}

type GetPlatformRolePermissionSetRow struct {
	Scope    string
	Resource string
	Action   string
}

func (q *Queries) GetPlatformRolePermissionSet(ctx context.Context, arg GetPlatformRolePermissionSetParams) ([]GetPlatformRolePermissionSetRow, error) {
	rows, err := q.db.Query(ctx, getPlatformRolePermissionSet, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlatformRolePermissionSetRow{}
	for rows.Next() {
		var i GetPlatformRolePermissionSetRow
		if err := rows.Scan(&i.Scope, &i.Resource, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlatformAdministratorRole = `-- name: InsertPlatformAdministratorRole :exec
INSERT INTO platform_roles(id,code,display_name,system_role,system_definition_version,version,created_at,updated_at)
VALUES($1,'platform-admin',$2,true,1,1,$3,$3)
`

type InsertPlatformAdministratorRoleParams struct {
	ID          uuid.UUID
	DisplayName string
	Now         pgtype.Timestamptz
}

func (q *Queries) InsertPlatformAdministratorRole(ctx context.Context, arg InsertPlatformAdministratorRoleParams) error {
	_, err := q.db.Exec(ctx, insertPlatformAdministratorRole, arg.ID, arg.DisplayName, arg.Now)
	return err
}

const insertPlatformRolePermission = `-- name: InsertPlatformRolePermission :exec
INSERT INTO platform_role_permissions(role_id,scope,resource,action,created_at)
VALUES($1,'platform',$2,$3,$4)
`

type InsertPlatformRolePermissionParams struct {
	RoleID   uuid.UUID
	Resource string
	Action   string
	Now      pgtype.Timestamptz
}

func (q *Queries) InsertPlatformRolePermission(ctx context.Context, arg InsertPlatformRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertPlatformRolePermission,
		arg.RoleID,
		arg.Resource,
		arg.Action,
		arg.Now,
	)
	return err
}

const lockPlatformAdministrator = `-- name: LockPlatformAdministrator :exec
SELECT singleton FROM platform_administrator_guard WHERE singleton FOR UPDATE
`

func (q *Queries) LockPlatformAdministrator(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockPlatformAdministrator)
	return err
}

const lookupFirstAdministratorCandidate = `-- name: LookupFirstAdministratorCandidate :one
SELECT i.intent_id, i.environment, i.normalized_email, i.issuer, i.subject, i.intent_sha256, i.supersedes, i.registered_at, i.expires_at, i.audit_event_id,
    EXISTS(SELECT 1 FROM first_administrator_completions c WHERE c.environment=i.environment)::boolean AS completed,
    EXISTS(SELECT 1 FROM platform_roles r JOIN platform_role_bindings b ON b.role_id=r.id
      JOIN platform_memberships m ON m.id=b.membership_id JOIN principals p ON p.id=m.principal_id
      WHERE r.code='platform-admin' AND r.system_role AND m.status='active' AND p.principal_type='human' AND p.status='active')::boolean AS administrator_present
FROM first_administrator_intents i WHERE i.environment=$1
AND NOT EXISTS(SELECT 1 FROM first_administrator_intents s WHERE s.environment=i.environment AND s.supersedes=i.intent_id)
`

type LookupFirstAdministratorCandidateParams struct {
	Environment string
}

type LookupFirstAdministratorCandidateRow struct {
	IntentID             uuid.UUID
	Environment          string
	NormalizedEmail      string
	Issuer               string
	Subject              string
	IntentSha256         []byte
	Supersedes           pgtype.UUID
	RegisteredAt         pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	AuditEventID         uuid.UUID
	Completed            bool
	AdministratorPresent bool
}

func (q *Queries) LookupFirstAdministratorCandidate(ctx context.Context, arg LookupFirstAdministratorCandidateParams) (LookupFirstAdministratorCandidateRow, error) {
	row := q.db.QueryRow(ctx, lookupFirstAdministratorCandidate, arg.Environment)
	var i LookupFirstAdministratorCandidateRow
	err := row.Scan(
		&i.IntentID,
		&i.Environment,
		&i.NormalizedEmail,
		&i.Issuer,
		&i.Subject,
		&i.IntentSha256,
		&i.Supersedes,
		&i.RegisteredAt,
		&i.ExpiresAt,
		&i.AuditEventID,
		&i.Completed,
		&i.AdministratorPresent,
	)
	return i, err
}

const lookupPlatformOIDC = `-- name: LookupPlatformOIDC :one
SELECT i.id AS identity_id,(i.status='active')::boolean AS identity_active,p.id AS principal_id,p.status AS principal_status,
    COALESCE(m.id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS membership_id,
    COALESCE(m.status,'removed')::text AS membership_status,COALESCE(e.normalized_email,'')::text AS normalized_email
FROM identities i JOIN principals p ON p.id=i.principal_id AND p.principal_type='human'
LEFT JOIN verified_emails e ON e.principal_id=p.id
LEFT JOIN platform_memberships m ON m.principal_id=p.id AND m.status<>'removed'
WHERE i.provider=$1 AND i.issuer=$2 AND i.subject=$3
FOR SHARE OF i,p
`

type LookupPlatformOIDCParams struct {
	Provider string
	Issuer   string
	Subject  string
}

type LookupPlatformOIDCRow struct {
	IdentityID       uuid.UUID
	IdentityActive   bool
	PrincipalID      uuid.UUID
	PrincipalStatus  string
	MembershipID     uuid.UUID
	MembershipStatus string
	NormalizedEmail  string
}

func (q *Queries) LookupPlatformOIDC(ctx context.Context, arg LookupPlatformOIDCParams) (LookupPlatformOIDCRow, error) {
	row := q.db.QueryRow(ctx, lookupPlatformOIDC, arg.Provider, arg.Issuer, arg.Subject)
	var i LookupPlatformOIDCRow
	err := row.Scan(
		&i.IdentityID,
		&i.IdentityActive,
		&i.PrincipalID,
		&i.PrincipalStatus,
		&i.MembershipID,
		&i.MembershipStatus,
		&i.NormalizedEmail,
	)
	return i, err
}

const platformBootstrapIdentityAvailable = `-- name: PlatformBootstrapIdentityAvailable :one
SELECT (NOT EXISTS(SELECT 1 FROM verified_emails WHERE normalized_email=$1)
AND NOT EXISTS(SELECT 1 FROM identities WHERE issuer=$2 AND subject=$3))::boolean AS available
`

type PlatformBootstrapIdentityAvailableParams struct {
	NormalizedEmail string
	Issuer          string
	Subject         string
}

func (q *Queries) PlatformBootstrapIdentityAvailable(ctx context.Context, arg PlatformBootstrapIdentityAvailableParams) (bool, error) {
	row := q.db.QueryRow(ctx, platformBootstrapIdentityAvailable, arg.NormalizedEmail, arg.Issuer, arg.Subject)
	var available bool
	err := row.Scan(&available)
	return available, err
}
