// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_session_query.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listOwnedPlatformSessionGrants = `-- name: ListOwnedPlatformSessionGrants :many
SELECT g.id, g.session_id, g.principal_id, g.audience, g.membership_id, g.status, g.version, g.created_at, g.updated_at FROM platform_session_grants g JOIN sessions s ON s.id=g.session_id AND s.principal_id=g.principal_id AND s.audience='boss'
WHERE s.principal_id=$1 AND g.session_id=$2 ORDER BY g.id
`

type ListOwnedPlatformSessionGrantsParams struct {
	PrincipalID uuid.UUID
	SessionID   uuid.UUID
}

func (q *Queries) ListOwnedPlatformSessionGrants(ctx context.Context, arg ListOwnedPlatformSessionGrantsParams) ([]PlatformSessionGrant, error) {
	rows, err := q.db.Query(ctx, listOwnedPlatformSessionGrants, arg.PrincipalID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformSessionGrant{}
	for rows.Next() {
		var i PlatformSessionGrant
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PrincipalID,
			&i.Audience,
			&i.MembershipID,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
