// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_membership.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advancePlatformMembershipVersion = `-- name: AdvancePlatformMembershipVersion :one
UPDATE platform_memberships SET version=version+1,updated_at=$1
WHERE id=$2 AND version=$3 AND status='active' RETURNING id, principal_id, status, version, created_at, updated_at
`

type AdvancePlatformMembershipVersionParams struct {
	Now             pgtype.Timestamptz
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) AdvancePlatformMembershipVersion(ctx context.Context, arg AdvancePlatformMembershipVersionParams) (PlatformMembership, error) {
	row := q.db.QueryRow(ctx, advancePlatformMembershipVersion, arg.Now, arg.ID, arg.ExpectedVersion)
	var i PlatformMembership
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const advancePlatformMembershipVersionForUnbind = `-- name: AdvancePlatformMembershipVersionForUnbind :one
UPDATE platform_memberships SET version=version+1,updated_at=$1
WHERE id=$2 AND version=$3 RETURNING id, principal_id, status, version, created_at, updated_at
`

type AdvancePlatformMembershipVersionForUnbindParams struct {
	Now             pgtype.Timestamptz
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) AdvancePlatformMembershipVersionForUnbind(ctx context.Context, arg AdvancePlatformMembershipVersionForUnbindParams) (PlatformMembership, error) {
	row := q.db.QueryRow(ctx, advancePlatformMembershipVersionForUnbind, arg.Now, arg.ID, arg.ExpectedVersion)
	var i PlatformMembership
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlatformAdministratorCandidates = `-- name: ListPlatformAdministratorCandidates :many
SELECT DISTINCT m.id AS membership_id,
(EXISTS(SELECT 1 FROM verified_emails e WHERE e.principal_id=p.id)
 AND EXISTS(SELECT 1 FROM identities i WHERE i.principal_id=p.id AND i.status='active'
 AND (($1::text<>'' AND $2::text<>'' AND i.provider=$1 AND i.issuer=$2)
 OR ($3::boolean AND i.provider='password' AND EXISTS(SELECT 1 FROM password_credentials c WHERE c.principal_id=p.id AND c.identity_id=i.id AND (c.locked_until IS NULL OR c.locked_until<=statement_timestamp()))))))::boolean AS login_capable
FROM platform_memberships m JOIN principals p ON p.id=m.principal_id
JOIN platform_role_bindings b ON b.membership_id=m.id JOIN platform_roles r ON r.id=b.role_id
WHERE m.status='active' AND p.status='active' AND p.principal_type='human' AND r.code='platform-admin' AND r.system_role
`

type ListPlatformAdministratorCandidatesParams struct {
	OidcProvider    string
	OidcIssuer      string
	PasswordEnabled bool
}

type ListPlatformAdministratorCandidatesRow struct {
	MembershipID uuid.UUID
	LoginCapable bool
}

func (q *Queries) ListPlatformAdministratorCandidates(ctx context.Context, arg ListPlatformAdministratorCandidatesParams) ([]ListPlatformAdministratorCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listPlatformAdministratorCandidates, arg.OidcProvider, arg.OidcIssuer, arg.PasswordEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformAdministratorCandidatesRow{}
	for rows.Next() {
		var i ListPlatformAdministratorCandidatesRow
		if err := rows.Scan(&i.MembershipID, &i.LoginCapable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlatformMembershipRoleBinding = `-- name: RemovePlatformMembershipRoleBinding :one
DELETE FROM platform_role_bindings WHERE membership_id=$1 AND role_id=$2 RETURNING id, membership_id, role_id, version, created_at, updated_at
`

type RemovePlatformMembershipRoleBindingParams struct {
	MembershipID uuid.UUID
	RoleID       uuid.UUID
}

func (q *Queries) RemovePlatformMembershipRoleBinding(ctx context.Context, arg RemovePlatformMembershipRoleBindingParams) (PlatformRoleBinding, error) {
	row := q.db.QueryRow(ctx, removePlatformMembershipRoleBinding, arg.MembershipID, arg.RoleID)
	var i PlatformRoleBinding
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.RoleID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlatformMembershipStatus = `-- name: UpdatePlatformMembershipStatus :one
UPDATE platform_memberships SET status=$1,version=version+1,updated_at=$2
WHERE id=$3 AND version=$4 AND status<>'removed' RETURNING id, principal_id, status, version, created_at, updated_at
`

type UpdatePlatformMembershipStatusParams struct {
	Status          string
	Now             pgtype.Timestamptz
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdatePlatformMembershipStatus(ctx context.Context, arg UpdatePlatformMembershipStatusParams) (PlatformMembership, error) {
	row := q.db.QueryRow(ctx, updatePlatformMembershipStatus,
		arg.Status,
		arg.Now,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i PlatformMembership
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
