// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_query.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listOwnedHumanSessions = `-- name: ListOwnedHumanSessions :many
SELECT s.id, s.principal_id, s.audience, s.status, s.device_name, s.idle_expires_at, s.absolute_expires_at, s.version, s.created_at, s.updated_at, s.reauthenticated_at, s.authn_methods FROM sessions s
WHERE s.principal_id = $1
  AND s.id > $2
ORDER BY s.id ASC LIMIT $3
`

type ListOwnedHumanSessionsParams struct {
	PrincipalID uuid.UUID
	AfterID     uuid.UUID
	RowLimit    int32
}

func (q *Queries) ListOwnedHumanSessions(ctx context.Context, arg ListOwnedHumanSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listOwnedHumanSessions, arg.PrincipalID, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.Audience,
			&i.Status,
			&i.DeviceName,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReauthenticatedAt,
			&i.AuthnMethods,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedSessionGrants = `-- name: ListOwnedSessionGrants :many
SELECT g.tenant_id, g.id, g.session_id, g.membership_id, g.status, g.version, g.created_at, g.updated_at FROM session_grants g
JOIN sessions s ON s.id = g.session_id
WHERE g.tenant_id = $1
  AND g.session_id = $2
  AND s.principal_id = $3
ORDER BY g.id ASC
`

type ListOwnedSessionGrantsParams struct {
	TenantID    uuid.UUID
	SessionID   uuid.UUID
	PrincipalID uuid.UUID
}

func (q *Queries) ListOwnedSessionGrants(ctx context.Context, arg ListOwnedSessionGrantsParams) ([]SessionGrant, error) {
	rows, err := q.db.Query(ctx, listOwnedSessionGrants, arg.TenantID, arg.SessionID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionGrant{}
	for rows.Next() {
		var i SessionGrant
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.SessionID,
			&i.MembershipID,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
