// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_admin_recovery.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveTenantAdminRecovery = `-- name: ApproveTenantAdminRecovery :execrows
UPDATE tenant_admin_recovery_operations SET status='approved',approver_principal_id=$1,
 approval_reference=$2,approved_at=$3,updated_at=$3,expires_at=$4,version=version+1
WHERE tenant_id=$5 AND id=$6 AND version=$7
 AND status='pending_approval' AND expires_at>$3 AND expires_at>statement_timestamp() AND requester_principal_id<>$1
`

type ApproveTenantAdminRecoveryParams struct {
	ApproverPrincipalID pgtype.UUID
	ApprovalReference   pgtype.Text
	Now                 pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	TenantID            uuid.UUID
	ID                  uuid.UUID
	ExpectedVersion     int64
}

func (q *Queries) ApproveTenantAdminRecovery(ctx context.Context, arg ApproveTenantAdminRecoveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveTenantAdminRecovery,
		arg.ApproverPrincipalID,
		arg.ApprovalReference,
		arg.Now,
		arg.ExpiresAt,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTenantAdminRecovery = `-- name: CreateTenantAdminRecovery :exec
INSERT INTO tenant_admin_recovery_operations(tenant_id,id,target_principal_id,requester_principal_id,reason_code,payload_fingerprint,status,version,created_at,updated_at,expires_at)
VALUES($1,$2,$3,$4,$5,$6,'pending_approval',1,$7,$7,$8)
`

type CreateTenantAdminRecoveryParams struct {
	TenantID             uuid.UUID
	ID                   uuid.UUID
	TargetPrincipalID    uuid.UUID
	RequesterPrincipalID uuid.UUID
	ReasonCode           string
	PayloadFingerprint   string
	Now                  pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
}

func (q *Queries) CreateTenantAdminRecovery(ctx context.Context, arg CreateTenantAdminRecoveryParams) error {
	_, err := q.db.Exec(ctx, createTenantAdminRecovery,
		arg.TenantID,
		arg.ID,
		arg.TargetPrincipalID,
		arg.RequesterPrincipalID,
		arg.ReasonCode,
		arg.PayloadFingerprint,
		arg.Now,
		arg.ExpiresAt,
	)
	return err
}

const executeTenantAdminRecovery = `-- name: ExecuteTenantAdminRecovery :execrows
UPDATE tenant_admin_recovery_operations SET status='executed',executed_at=$1,updated_at=$1,membership_id=$2,version=version+1
WHERE tenant_id=$3 AND id=$4 AND version=$5
 AND status='approved' AND expires_at>$1 AND expires_at>statement_timestamp() AND approval_reference=$6
`

type ExecuteTenantAdminRecoveryParams struct {
	Now               pgtype.Timestamptz
	MembershipID      pgtype.UUID
	TenantID          uuid.UUID
	ID                uuid.UUID
	ExpectedVersion   int64
	ApprovalReference pgtype.Text
}

func (q *Queries) ExecuteTenantAdminRecovery(ctx context.Context, arg ExecuteTenantAdminRecoveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, executeTenantAdminRecovery,
		arg.Now,
		arg.MembershipID,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
		arg.ApprovalReference,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTenantAdminRecovery = `-- name: GetTenantAdminRecovery :one
SELECT tenant_id, id, target_principal_id, requester_principal_id, approver_principal_id, approval_reference, reason_code, payload_fingerprint, status, version, created_at, updated_at, expires_at, approved_at, executed_at, membership_id FROM tenant_admin_recovery_operations WHERE id=$1 FOR UPDATE
`

type GetTenantAdminRecoveryParams struct {
	ID uuid.UUID
}

func (q *Queries) GetTenantAdminRecovery(ctx context.Context, arg GetTenantAdminRecoveryParams) (TenantAdminRecoveryOperation, error) {
	row := q.db.QueryRow(ctx, getTenantAdminRecovery, arg.ID)
	var i TenantAdminRecoveryOperation
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.TargetPrincipalID,
		&i.RequesterPrincipalID,
		&i.ApproverPrincipalID,
		&i.ApprovalReference,
		&i.ReasonCode,
		&i.PayloadFingerprint,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExecutedAt,
		&i.MembershipID,
	)
	return i, err
}

const reserveRestoreRecoveryApproval = `-- name: ReserveRestoreRecoveryApproval :exec
INSERT INTO iam_recovery_approval_references(approval_reference,tenant_id,restore_operation_id,created_at)
VALUES($1,$2,$3,$4)
`

type ReserveRestoreRecoveryApprovalParams struct {
	ApprovalReference string
	TenantID          uuid.UUID
	OperationID       pgtype.UUID
	Now               pgtype.Timestamptz
}

func (q *Queries) ReserveRestoreRecoveryApproval(ctx context.Context, arg ReserveRestoreRecoveryApprovalParams) error {
	_, err := q.db.Exec(ctx, reserveRestoreRecoveryApproval,
		arg.ApprovalReference,
		arg.TenantID,
		arg.OperationID,
		arg.Now,
	)
	return err
}

const tenantAdminRecoveryLoginTarget = `-- name: TenantAdminRecoveryLoginTarget :one
SELECT p.id, EXISTS (
 SELECT 1 FROM verified_emails e JOIN identities i ON i.principal_id=e.principal_id
 WHERE e.principal_id=p.id AND i.status='active'
 AND (($1::text<>'' AND $2::text<>''
       AND i.provider=$1 AND i.issuer=$2)
 OR ($3::boolean AND i.provider='password'
     AND EXISTS (SELECT 1 FROM password_credentials c WHERE c.principal_id=p.id AND c.identity_id=i.id
       AND (c.locked_until IS NULL OR c.locked_until<=$4))))
) AS login_capable
FROM principals p WHERE p.id=$5 AND p.principal_type='human' AND p.status='active' FOR UPDATE OF p
`

type TenantAdminRecoveryLoginTargetParams struct {
	OidcProvider    string
	OidcIssuer      string
	PasswordEnabled bool
	Now             pgtype.Timestamptz
	PrincipalID     uuid.UUID
}

type TenantAdminRecoveryLoginTargetRow struct {
	ID           uuid.UUID
	LoginCapable bool
}

func (q *Queries) TenantAdminRecoveryLoginTarget(ctx context.Context, arg TenantAdminRecoveryLoginTargetParams) (TenantAdminRecoveryLoginTargetRow, error) {
	row := q.db.QueryRow(ctx, tenantAdminRecoveryLoginTarget,
		arg.OidcProvider,
		arg.OidcIssuer,
		arg.PasswordEnabled,
		arg.Now,
		arg.PrincipalID,
	)
	var i TenantAdminRecoveryLoginTargetRow
	err := row.Scan(&i.ID, &i.LoginCapable)
	return i, err
}

const tenantAdminRecoveryMembership = `-- name: TenantAdminRecoveryMembership :one
SELECT tenant_id, id, principal_id, status, version, created_at, updated_at FROM tenant_memberships WHERE tenant_id=$1 AND principal_id=$2 AND status<>'removed' FOR UPDATE
`

type TenantAdminRecoveryMembershipParams struct {
	TenantID    uuid.UUID
	PrincipalID uuid.UUID
}

func (q *Queries) TenantAdminRecoveryMembership(ctx context.Context, arg TenantAdminRecoveryMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, tenantAdminRecoveryMembership, arg.TenantID, arg.PrincipalID)
	var i TenantMembership
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.PrincipalID,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenantAdminRecoveryRole = `-- name: TenantAdminRecoveryRole :one
SELECT tenant_id, id, code, system_role, system_definition_version, version, created_at, updated_at, display_name FROM tenant_roles WHERE tenant_id=$1 AND code='tenant-admin' AND system_role FOR SHARE
`

type TenantAdminRecoveryRoleParams struct {
	TenantID uuid.UUID
}

func (q *Queries) TenantAdminRecoveryRole(ctx context.Context, arg TenantAdminRecoveryRoleParams) (TenantRole, error) {
	row := q.db.QueryRow(ctx, tenantAdminRecoveryRole, arg.TenantID)
	var i TenantRole
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Code,
		&i.SystemRole,
		&i.SystemDefinitionVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}
