// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_roles.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCustomTenantRolePermission = `-- name: AddCustomTenantRolePermission :exec
INSERT INTO tenant_role_permissions(tenant_id,role_id,scope,resource,action,created_at)
VALUES($1,$2,'tenant',$3,$4,$5)
`

type AddCustomTenantRolePermissionParams struct {
	TenantID  uuid.UUID
	RoleID    uuid.UUID
	Resource  string
	Action    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AddCustomTenantRolePermission(ctx context.Context, arg AddCustomTenantRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addCustomTenantRolePermission,
		arg.TenantID,
		arg.RoleID,
		arg.Resource,
		arg.Action,
		arg.CreatedAt,
	)
	return err
}

const clearCustomTenantRolePermissions = `-- name: ClearCustomTenantRolePermissions :exec
DELETE FROM tenant_role_permissions
WHERE tenant_id=$1 AND role_id=$2
`

type ClearCustomTenantRolePermissionsParams struct {
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) ClearCustomTenantRolePermissions(ctx context.Context, arg ClearCustomTenantRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, clearCustomTenantRolePermissions, arg.TenantID, arg.RoleID)
	return err
}

const createCustomTenantRole = `-- name: CreateCustomTenantRole :exec
INSERT INTO tenant_roles (tenant_id,id,code,display_name,system_role,system_definition_version,version,created_at,updated_at)
VALUES ($1,$2,$3,$4,false,1,1,$5,$6)
`

type CreateCustomTenantRoleParams struct {
	TenantID    uuid.UUID
	ID          uuid.UUID
	Code        string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateCustomTenantRole(ctx context.Context, arg CreateCustomTenantRoleParams) error {
	_, err := q.db.Exec(ctx, createCustomTenantRole,
		arg.TenantID,
		arg.ID,
		arg.Code,
		arg.DisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const customTenantRoleReferenced = `-- name: CustomTenantRoleReferenced :one
SELECT EXISTS(SELECT 1 FROM tenant_role_bindings b
WHERE b.tenant_id=$1 AND b.role_id=$2
UNION ALL SELECT 1 FROM tenant_invitation_roles i
WHERE i.tenant_id=$1 AND i.role_id=$2) AS referenced
`

type CustomTenantRoleReferencedParams struct {
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) CustomTenantRoleReferenced(ctx context.Context, arg CustomTenantRoleReferencedParams) (bool, error) {
	row := q.db.QueryRow(ctx, customTenantRoleReferenced, arg.TenantID, arg.RoleID)
	var referenced bool
	err := row.Scan(&referenced)
	return referenced, err
}

const deleteCustomTenantRole = `-- name: DeleteCustomTenantRole :execrows
DELETE FROM tenant_roles
WHERE tenant_id=$1 AND id=$2 AND version=$3 AND NOT system_role
`

type DeleteCustomTenantRoleParams struct {
	TenantID        uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) DeleteCustomTenantRole(ctx context.Context, arg DeleteCustomTenantRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomTenantRole, arg.TenantID, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCustomTenantRole = `-- name: UpdateCustomTenantRole :execrows
UPDATE tenant_roles SET display_name=$1,version=version+1,updated_at=$2
WHERE tenant_id=$3 AND id=$4 AND version=$5 AND NOT system_role
`

type UpdateCustomTenantRoleParams struct {
	DisplayName     string
	UpdatedAt       pgtype.Timestamptz
	TenantID        uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateCustomTenantRole(ctx context.Context, arg UpdateCustomTenantRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCustomTenantRole,
		arg.DisplayName,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
