// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_bootstrap_recovery.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateRecoveryBootstrapAccess = `-- name: ActivateRecoveryBootstrapAccess :one
UPDATE tenant_access SET status='active',version=version+1,updated_at=$1
WHERE tenant_id=$2 AND status='bootstrap_pending'
RETURNING status,version,created_at,updated_at
`

type ActivateRecoveryBootstrapAccessParams struct {
	Now      pgtype.Timestamptz
	TenantID uuid.UUID
}

type ActivateRecoveryBootstrapAccessRow struct {
	Status    string
	Version   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ActivateRecoveryBootstrapAccess(ctx context.Context, arg ActivateRecoveryBootstrapAccessParams) (ActivateRecoveryBootstrapAccessRow, error) {
	row := q.db.QueryRow(ctx, activateRecoveryBootstrapAccess, arg.Now, arg.TenantID)
	var i ActivateRecoveryBootstrapAccessRow
	err := row.Scan(
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const approveTenantBootstrapRecovery = `-- name: ApproveTenantBootstrapRecovery :execrows
UPDATE tenant_bootstrap_recovery_operations SET status='approved',approver_principal_id=$1,
 approval_reference=$2,approved_at=$3,updated_at=$3,expires_at=$4,version=version+1
WHERE tenant_id=$5 AND id=$6 AND version=$7
 AND status='pending_approval' AND expires_at>$3 AND expires_at>statement_timestamp() AND requester_principal_id<>$1
`

type ApproveTenantBootstrapRecoveryParams struct {
	ApproverPrincipalID pgtype.UUID
	ApprovalReference   pgtype.Text
	Now                 pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	TenantID            uuid.UUID
	ID                  uuid.UUID
	ExpectedVersion     int64
}

func (q *Queries) ApproveTenantBootstrapRecovery(ctx context.Context, arg ApproveTenantBootstrapRecoveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveTenantBootstrapRecovery,
		arg.ApproverPrincipalID,
		arg.ApprovalReference,
		arg.Now,
		arg.ExpiresAt,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bootstrapRecoveryVerifiedEmail = `-- name: BootstrapRecoveryVerifiedEmail :one
SELECT normalized_email FROM verified_emails WHERE principal_id=$1
`

type BootstrapRecoveryVerifiedEmailParams struct {
	PrincipalID uuid.UUID
}

func (q *Queries) BootstrapRecoveryVerifiedEmail(ctx context.Context, arg BootstrapRecoveryVerifiedEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, bootstrapRecoveryVerifiedEmail, arg.PrincipalID)
	var normalized_email string
	err := row.Scan(&normalized_email)
	return normalized_email, err
}

const cancelSupersededBootstrapInvitations = `-- name: CancelSupersededBootstrapInvitations :many
UPDATE tenant_invitations SET status='cancelled',version=version+1,updated_at=$1
WHERE tenant_id=$2 AND bootstrap_operation_id=$3 AND status IN ('pending','expired')
RETURNING id,version
`

type CancelSupersededBootstrapInvitationsParams struct {
	Now         pgtype.Timestamptz
	TenantID    uuid.UUID
	OperationID pgtype.UUID
}

type CancelSupersededBootstrapInvitationsRow struct {
	ID      uuid.UUID
	Version int64
}

func (q *Queries) CancelSupersededBootstrapInvitations(ctx context.Context, arg CancelSupersededBootstrapInvitationsParams) ([]CancelSupersededBootstrapInvitationsRow, error) {
	rows, err := q.db.Query(ctx, cancelSupersededBootstrapInvitations, arg.Now, arg.TenantID, arg.OperationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelSupersededBootstrapInvitationsRow{}
	for rows.Next() {
		var i CancelSupersededBootstrapInvitationsRow
		if err := rows.Scan(&i.ID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBootstrapAdministratorRole = `-- name: CreateBootstrapAdministratorRole :exec
INSERT INTO tenant_roles(tenant_id,id,code,display_name,system_role,system_definition_version,version,created_at,updated_at)
VALUES($1,$2,'tenant-admin','Tenant administrator',true,1,1,$3,$3)
`

type CreateBootstrapAdministratorRoleParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	Now      pgtype.Timestamptz
}

func (q *Queries) CreateBootstrapAdministratorRole(ctx context.Context, arg CreateBootstrapAdministratorRoleParams) error {
	_, err := q.db.Exec(ctx, createBootstrapAdministratorRole, arg.TenantID, arg.ID, arg.Now)
	return err
}

const createBootstrapPendingAccess = `-- name: CreateBootstrapPendingAccess :exec
INSERT INTO tenant_access(tenant_id,status,version,created_at,updated_at)
VALUES($1,'bootstrap_pending',1,$2,$2) ON CONFLICT(tenant_id) DO NOTHING
`

type CreateBootstrapPendingAccessParams struct {
	TenantID uuid.UUID
	Now      pgtype.Timestamptz
}

func (q *Queries) CreateBootstrapPendingAccess(ctx context.Context, arg CreateBootstrapPendingAccessParams) error {
	_, err := q.db.Exec(ctx, createBootstrapPendingAccess, arg.TenantID, arg.Now)
	return err
}

const createRecoveredTenantBootstrap = `-- name: CreateRecoveredTenantBootstrap :exec
INSERT INTO tenant_bootstrap_operations(tenant_id,id,source_kind,intended_email,intended_principal_id,payload_fingerprint,payload,status,version,
 recovery_request_id,supersedes,membership_id,principal_id,created_at,updated_at)
VALUES($1,$2,'recovery',$3,$4,$5,$6,'succeeded',1,
 $2,$7,$8,$4,$9,$9)
`

type CreateRecoveredTenantBootstrapParams struct {
	TenantID           uuid.UUID
	ID                 uuid.UUID
	IntendedEmail      string
	PrincipalID        pgtype.UUID
	PayloadFingerprint string
	Payload            []byte
	Supersedes         pgtype.UUID
	MembershipID       pgtype.UUID
	Now                pgtype.Timestamptz
}

func (q *Queries) CreateRecoveredTenantBootstrap(ctx context.Context, arg CreateRecoveredTenantBootstrapParams) error {
	_, err := q.db.Exec(ctx, createRecoveredTenantBootstrap,
		arg.TenantID,
		arg.ID,
		arg.IntendedEmail,
		arg.PrincipalID,
		arg.PayloadFingerprint,
		arg.Payload,
		arg.Supersedes,
		arg.MembershipID,
		arg.Now,
	)
	return err
}

const createTenantBootstrapRecovery = `-- name: CreateTenantBootstrapRecovery :exec
INSERT INTO tenant_bootstrap_recovery_operations(tenant_id,id,target_principal_id,requester_principal_id,reason_code,payload_fingerprint,status,version,created_at,updated_at,expires_at)
VALUES($1,$2,$3,$4,$5,$6,'pending_approval',1,$7,$7,$8)
`

type CreateTenantBootstrapRecoveryParams struct {
	TenantID             uuid.UUID
	ID                   uuid.UUID
	TargetPrincipalID    uuid.UUID
	RequesterPrincipalID uuid.UUID
	ReasonCode           string
	PayloadFingerprint   string
	Now                  pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
}

func (q *Queries) CreateTenantBootstrapRecovery(ctx context.Context, arg CreateTenantBootstrapRecoveryParams) error {
	_, err := q.db.Exec(ctx, createTenantBootstrapRecovery,
		arg.TenantID,
		arg.ID,
		arg.TargetPrincipalID,
		arg.RequesterPrincipalID,
		arg.ReasonCode,
		arg.PayloadFingerprint,
		arg.Now,
		arg.ExpiresAt,
	)
	return err
}

const executeTenantBootstrapRecovery = `-- name: ExecuteTenantBootstrapRecovery :execrows
UPDATE tenant_bootstrap_recovery_operations SET status='executed',executed_at=$1,updated_at=$1,membership_id=$2,version=version+1
WHERE tenant_id=$3 AND id=$4 AND version=$5
 AND status='approved' AND expires_at>$1 AND expires_at>statement_timestamp() AND approval_reference=$6
`

type ExecuteTenantBootstrapRecoveryParams struct {
	Now               pgtype.Timestamptz
	MembershipID      pgtype.UUID
	TenantID          uuid.UUID
	ID                uuid.UUID
	ExpectedVersion   int64
	ApprovalReference pgtype.Text
}

func (q *Queries) ExecuteTenantBootstrapRecovery(ctx context.Context, arg ExecuteTenantBootstrapRecoveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, executeTenantBootstrapRecovery,
		arg.Now,
		arg.MembershipID,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
		arg.ApprovalReference,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCurrentTenantBootstrap = `-- name: GetCurrentTenantBootstrap :one
SELECT tenant_id, id, source_kind, intended_email, intended_principal_id, payload_fingerprint, payload, status, version, recovery_request_id, supersedes, superseded_by, membership_id, principal_id, created_at, updated_at FROM tenant_bootstrap_operations WHERE tenant_id=$1 AND superseded_by IS NULL FOR UPDATE
`

type GetCurrentTenantBootstrapParams struct {
	TenantID uuid.UUID
}

func (q *Queries) GetCurrentTenantBootstrap(ctx context.Context, arg GetCurrentTenantBootstrapParams) (TenantBootstrapOperation, error) {
	row := q.db.QueryRow(ctx, getCurrentTenantBootstrap, arg.TenantID)
	var i TenantBootstrapOperation
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.SourceKind,
		&i.IntendedEmail,
		&i.IntendedPrincipalID,
		&i.PayloadFingerprint,
		&i.Payload,
		&i.Status,
		&i.Version,
		&i.RecoveryRequestID,
		&i.Supersedes,
		&i.SupersededBy,
		&i.MembershipID,
		&i.PrincipalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBootstrapRecovery = `-- name: GetTenantBootstrapRecovery :one
SELECT tenant_id, id, target_principal_id, requester_principal_id, approver_principal_id, approval_reference, reason_code, payload_fingerprint, status, version, created_at, updated_at, expires_at, approved_at, executed_at, membership_id FROM tenant_bootstrap_recovery_operations WHERE id=$1 FOR UPDATE
`

type GetTenantBootstrapRecoveryParams struct {
	ID uuid.UUID
}

func (q *Queries) GetTenantBootstrapRecovery(ctx context.Context, arg GetTenantBootstrapRecoveryParams) (TenantBootstrapRecoveryOperation, error) {
	row := q.db.QueryRow(ctx, getTenantBootstrapRecovery, arg.ID)
	var i TenantBootstrapRecoveryOperation
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.TargetPrincipalID,
		&i.RequesterPrincipalID,
		&i.ApproverPrincipalID,
		&i.ApprovalReference,
		&i.ReasonCode,
		&i.PayloadFingerprint,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExecutedAt,
		&i.MembershipID,
	)
	return i, err
}

const recoveryCancelledBootstrapInvitation = `-- name: RecoveryCancelledBootstrapInvitation :one
SELECT EXISTS(SELECT 1 FROM tenant_invitations i JOIN tenant_bootstrap_operations o ON o.tenant_id=i.tenant_id AND o.id=i.bootstrap_operation_id
WHERE i.tenant_id=$1 AND i.id=$2 AND i.status='cancelled' AND i.version=$3
AND o.superseded_by=$4) AS valid
`

type RecoveryCancelledBootstrapInvitationParams struct {
	TenantID     uuid.UUID
	InvitationID uuid.UUID
	Version      int64
	RecoveryID   pgtype.UUID
}

func (q *Queries) RecoveryCancelledBootstrapInvitation(ctx context.Context, arg RecoveryCancelledBootstrapInvitationParams) (bool, error) {
	row := q.db.QueryRow(ctx, recoveryCancelledBootstrapInvitation,
		arg.TenantID,
		arg.InvitationID,
		arg.Version,
		arg.RecoveryID,
	)
	var valid bool
	err := row.Scan(&valid)
	return valid, err
}

const reserveBootstrapRecoveryApproval = `-- name: ReserveBootstrapRecoveryApproval :exec
INSERT INTO iam_recovery_approval_references(approval_reference,tenant_id,bootstrap_operation_id,created_at)
VALUES($1,$2,$3,$4)
`

type ReserveBootstrapRecoveryApprovalParams struct {
	ApprovalReference string
	TenantID          uuid.UUID
	OperationID       pgtype.UUID
	Now               pgtype.Timestamptz
}

func (q *Queries) ReserveBootstrapRecoveryApproval(ctx context.Context, arg ReserveBootstrapRecoveryApprovalParams) error {
	_, err := q.db.Exec(ctx, reserveBootstrapRecoveryApproval,
		arg.ApprovalReference,
		arg.TenantID,
		arg.OperationID,
		arg.Now,
	)
	return err
}

const supersedeTenantBootstrap = `-- name: SupersedeTenantBootstrap :execrows
UPDATE tenant_bootstrap_operations SET status='superseded',superseded_by=$1,version=version+1,updated_at=$2
WHERE tenant_id=$3 AND id=$4 AND version=$5
AND status IN ('pending','waiting_for_principal_verification','attention_required') AND superseded_by IS NULL
`

type SupersedeTenantBootstrapParams struct {
	RecoveryID      pgtype.UUID
	Now             pgtype.Timestamptz
	TenantID        uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) SupersedeTenantBootstrap(ctx context.Context, arg SupersedeTenantBootstrapParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeTenantBootstrap,
		arg.RecoveryID,
		arg.Now,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
