// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_invitations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTenantInvitationRole = `-- name: AddTenantInvitationRole :exec
INSERT INTO tenant_invitation_roles(tenant_id,invitation_id,role_id) VALUES($1,$2,$3)
`

type AddTenantInvitationRoleParams struct {
	TenantID     uuid.UUID
	InvitationID uuid.UUID
	RoleID       uuid.UUID
}

func (q *Queries) AddTenantInvitationRole(ctx context.Context, arg AddTenantInvitationRoleParams) error {
	_, err := q.db.Exec(ctx, addTenantInvitationRole, arg.TenantID, arg.InvitationID, arg.RoleID)
	return err
}

const cancelTenantInvitationDeliveries = `-- name: CancelTenantInvitationDeliveries :exec
UPDATE tenant_invitation_outbox SET status='cancelled',payload_key_version=NULL,payload_ciphertext=NULL,
    claimed_at=NULL,delivered_at=NULL,notification_id=NULL,version=version+1,updated_at=$1
WHERE tenant_id=$2 AND invitation_id=$3 AND status IN ('pending','claimed','attention_required')
`

type CancelTenantInvitationDeliveriesParams struct {
	UpdatedAt    pgtype.Timestamptz
	TenantID     uuid.UUID
	InvitationID uuid.UUID
}

func (q *Queries) CancelTenantInvitationDeliveries(ctx context.Context, arg CancelTenantInvitationDeliveriesParams) error {
	_, err := q.db.Exec(ctx, cancelTenantInvitationDeliveries, arg.UpdatedAt, arg.TenantID, arg.InvitationID)
	return err
}

const clearTenantInvitationRoles = `-- name: ClearTenantInvitationRoles :exec
DELETE FROM tenant_invitation_roles WHERE tenant_id=$1 AND invitation_id=$2
`

type ClearTenantInvitationRolesParams struct {
	TenantID     uuid.UUID
	InvitationID uuid.UUID
}

func (q *Queries) ClearTenantInvitationRoles(ctx context.Context, arg ClearTenantInvitationRolesParams) error {
	_, err := q.db.Exec(ctx, clearTenantInvitationRoles, arg.TenantID, arg.InvitationID)
	return err
}

const createTenantInvitation = `-- name: CreateTenantInvitation :exec
INSERT INTO tenant_invitations(tenant_id,id,normalized_email,role_ids,locale,status,token_digest,delivery_generation,expires_at,version,created_by,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,'pending',$6,1,$7,1,$8,$9,$9)
`

type CreateTenantInvitationParams struct {
	TenantID        uuid.UUID
	ID              uuid.UUID
	NormalizedEmail string
	RoleIds         []uuid.UUID
	Locale          string
	TokenDigest     []byte
	ExpiresAt       pgtype.Timestamptz
	CreatedBy       uuid.UUID
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateTenantInvitation(ctx context.Context, arg CreateTenantInvitationParams) error {
	_, err := q.db.Exec(ctx, createTenantInvitation,
		arg.TenantID,
		arg.ID,
		arg.NormalizedEmail,
		arg.RoleIds,
		arg.Locale,
		arg.TokenDigest,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const createTenantInvitationDelivery = `-- name: CreateTenantInvitationDelivery :exec
INSERT INTO tenant_invitation_outbox(tenant_id,id,invitation_id,delivery_generation,payload_key_version,payload_ciphertext,status,available_at,version,created_at,updated_at)
VALUES($1,$2,$3,$4,$5,$6,'pending',$7,1,$7,$7)
`

type CreateTenantInvitationDeliveryParams struct {
	TenantID           uuid.UUID
	ID                 uuid.UUID
	InvitationID       uuid.UUID
	DeliveryGeneration int64
	PayloadKeyVersion  pgtype.Text
	PayloadCiphertext  []byte
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateTenantInvitationDelivery(ctx context.Context, arg CreateTenantInvitationDeliveryParams) error {
	_, err := q.db.Exec(ctx, createTenantInvitationDelivery,
		arg.TenantID,
		arg.ID,
		arg.InvitationID,
		arg.DeliveryGeneration,
		arg.PayloadKeyVersion,
		arg.PayloadCiphertext,
		arg.CreatedAt,
	)
	return err
}

const findPendingTenantInvitation = `-- name: FindPendingTenantInvitation :one
SELECT tenant_id, id, normalized_email, role_ids, locale, status, token_digest, delivery_generation, expires_at, version, created_by, created_at, updated_at, accepted_membership_id, accepted_principal_id, bootstrap_operation_id FROM tenant_invitations WHERE tenant_id=$1 AND normalized_email=$2 AND status='pending'
`

type FindPendingTenantInvitationParams struct {
	TenantID        uuid.UUID
	NormalizedEmail string
}

func (q *Queries) FindPendingTenantInvitation(ctx context.Context, arg FindPendingTenantInvitationParams) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, findPendingTenantInvitation, arg.TenantID, arg.NormalizedEmail)
	var i TenantInvitation
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.NormalizedEmail,
		&i.RoleIds,
		&i.Locale,
		&i.Status,
		&i.TokenDigest,
		&i.DeliveryGeneration,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedMembershipID,
		&i.AcceptedPrincipalID,
		&i.BootstrapOperationID,
	)
	return i, err
}

const getTenantInvitation = `-- name: GetTenantInvitation :one
SELECT tenant_id, id, normalized_email, role_ids, locale, status, token_digest, delivery_generation, expires_at, version, created_by, created_at, updated_at, accepted_membership_id, accepted_principal_id, bootstrap_operation_id FROM tenant_invitations WHERE tenant_id=$1 AND id=$2
`

type GetTenantInvitationParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetTenantInvitation(ctx context.Context, arg GetTenantInvitationParams) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, getTenantInvitation, arg.TenantID, arg.ID)
	var i TenantInvitation
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.NormalizedEmail,
		&i.RoleIds,
		&i.Locale,
		&i.Status,
		&i.TokenDigest,
		&i.DeliveryGeneration,
		&i.ExpiresAt,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedMembershipID,
		&i.AcceptedPrincipalID,
		&i.BootstrapOperationID,
	)
	return i, err
}

const getTenantInvitationDelivery = `-- name: GetTenantInvitationDelivery :one
SELECT status,attempt_count FROM tenant_invitation_outbox
WHERE tenant_id=$1 AND invitation_id=$2 AND delivery_generation=$3
`

type GetTenantInvitationDeliveryParams struct {
	TenantID           uuid.UUID
	InvitationID       uuid.UUID
	DeliveryGeneration int64
}

type GetTenantInvitationDeliveryRow struct {
	Status       string
	AttemptCount int32
}

func (q *Queries) GetTenantInvitationDelivery(ctx context.Context, arg GetTenantInvitationDeliveryParams) (GetTenantInvitationDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getTenantInvitationDelivery, arg.TenantID, arg.InvitationID, arg.DeliveryGeneration)
	var i GetTenantInvitationDeliveryRow
	err := row.Scan(&i.Status, &i.AttemptCount)
	return i, err
}

const listExpiredTenantInvitationsForRole = `-- name: ListExpiredTenantInvitationsForRole :many
SELECT i.tenant_id, i.id, i.normalized_email, i.role_ids, i.locale, i.status, i.token_digest, i.delivery_generation, i.expires_at, i.version, i.created_by, i.created_at, i.updated_at, i.accepted_membership_id, i.accepted_principal_id, i.bootstrap_operation_id FROM tenant_invitations i JOIN tenant_invitation_roles r ON r.tenant_id=i.tenant_id AND r.invitation_id=i.id
WHERE i.tenant_id=$1 AND r.role_id=$2 AND i.status='pending' AND i.expires_at<=$3
ORDER BY i.id
`

type ListExpiredTenantInvitationsForRoleParams struct {
	TenantID uuid.UUID
	RoleID   uuid.UUID
	Now      pgtype.Timestamptz
}

func (q *Queries) ListExpiredTenantInvitationsForRole(ctx context.Context, arg ListExpiredTenantInvitationsForRoleParams) ([]TenantInvitation, error) {
	rows, err := q.db.Query(ctx, listExpiredTenantInvitationsForRole, arg.TenantID, arg.RoleID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantInvitation{}
	for rows.Next() {
		var i TenantInvitation
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.NormalizedEmail,
			&i.RoleIds,
			&i.Locale,
			&i.Status,
			&i.TokenDigest,
			&i.DeliveryGeneration,
			&i.ExpiresAt,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedMembershipID,
			&i.AcceptedPrincipalID,
			&i.BootstrapOperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantInvitations = `-- name: ListTenantInvitations :many
SELECT tenant_id, id, normalized_email, role_ids, locale, status, token_digest, delivery_generation, expires_at, version, created_by, created_at, updated_at, accepted_membership_id, accepted_principal_id, bootstrap_operation_id FROM tenant_invitations
WHERE tenant_id=$1 AND ($2::text='' OR
  CASE WHEN status='pending' AND expires_at<=$3 THEN 'expired' ELSE status END=$2)
AND ($4::uuid='00000000-0000-0000-0000-000000000000'::uuid OR id>$4)
ORDER BY id LIMIT $5
`

type ListTenantInvitationsParams struct {
	TenantID  uuid.UUID
	Status    string
	Now       pgtype.Timestamptz
	CursorID  uuid.UUID
	PageLimit int32
}

func (q *Queries) ListTenantInvitations(ctx context.Context, arg ListTenantInvitationsParams) ([]TenantInvitation, error) {
	rows, err := q.db.Query(ctx, listTenantInvitations,
		arg.TenantID,
		arg.Status,
		arg.Now,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantInvitation{}
	for rows.Next() {
		var i TenantInvitation
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.NormalizedEmail,
			&i.RoleIds,
			&i.Locale,
			&i.Status,
			&i.TokenDigest,
			&i.DeliveryGeneration,
			&i.ExpiresAt,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedMembershipID,
			&i.AcceptedPrincipalID,
			&i.BootstrapOperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resendTenantInvitation = `-- name: ResendTenantInvitation :execrows
UPDATE tenant_invitations SET status='pending',token_digest=$1,delivery_generation=delivery_generation+1,
    expires_at=$2,version=version+1,updated_at=$3
WHERE tenant_id=$4 AND id=$5 AND version=$6 AND status IN ('pending','expired')
`

type ResendTenantInvitationParams struct {
	TokenDigest     []byte
	ExpiresAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	TenantID        uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) ResendTenantInvitation(ctx context.Context, arg ResendTenantInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, resendTenantInvitation,
		arg.TokenDigest,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transitionTenantInvitationTerminal = `-- name: TransitionTenantInvitationTerminal :execrows
UPDATE tenant_invitations SET status=$1,version=version+1,updated_at=$2
WHERE tenant_id=$3 AND id=$4 AND version=$5 AND status='pending'
`

type TransitionTenantInvitationTerminalParams struct {
	Status          string
	UpdatedAt       pgtype.Timestamptz
	TenantID        uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) TransitionTenantInvitationTerminal(ctx context.Context, arg TransitionTenantInvitationTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionTenantInvitationTerminal,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
