// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workload_registry.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertWorkloadRegistryInstallation = `-- name: InsertWorkloadRegistryInstallation :exec
INSERT INTO workload_registry_installations
    (id, previous_sha256, installed_sha256, installed_by, installed_at)
VALUES ($1, $2, $3, current_user, $4)
`

type InsertWorkloadRegistryInstallationParams struct {
	ID              uuid.UUID
	PreviousSha256  []byte
	InstalledSha256 []byte
	InstalledAt     pgtype.Timestamptz
}

func (q *Queries) InsertWorkloadRegistryInstallation(ctx context.Context, arg InsertWorkloadRegistryInstallationParams) error {
	_, err := q.db.Exec(ctx, insertWorkloadRegistryInstallation,
		arg.ID,
		arg.PreviousSha256,
		arg.InstalledSha256,
		arg.InstalledAt,
	)
	return err
}

const insertWorkloadRegistryPermission = `-- name: InsertWorkloadRegistryPermission :exec
INSERT INTO permission_catalog (scope, resource, action)
VALUES ('tenant', $1, $2)
ON CONFLICT DO NOTHING
`

type InsertWorkloadRegistryPermissionParams struct {
	Resource string
	Action   string
}

func (q *Queries) InsertWorkloadRegistryPermission(ctx context.Context, arg InsertWorkloadRegistryPermissionParams) error {
	_, err := q.db.Exec(ctx, insertWorkloadRegistryPermission, arg.Resource, arg.Action)
	return err
}

const listWorkloadTargetRegistrations = `-- name: ListWorkloadTargetRegistrations :many
SELECT audience, operation, scope, target_sha256, bundle_sha256, enabled
FROM workload_target_registrations ORDER BY audience, operation
`

func (q *Queries) ListWorkloadTargetRegistrations(ctx context.Context) ([]WorkloadTargetRegistration, error) {
	rows, err := q.db.Query(ctx, listWorkloadTargetRegistrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadTargetRegistration{}
	for rows.Next() {
		var i WorkloadTargetRegistration
		if err := rows.Scan(
			&i.Audience,
			&i.Operation,
			&i.Scope,
			&i.TargetSha256,
			&i.BundleSha256,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkloadRegistryInstallation = `-- name: LockWorkloadRegistryInstallation :exec
SELECT pg_advisory_xact_lock(hashtextextended('iam.workload-target-registration.v1',0))
`

func (q *Queries) LockWorkloadRegistryInstallation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockWorkloadRegistryInstallation)
	return err
}

const upsertWorkloadTargetRegistration = `-- name: UpsertWorkloadTargetRegistration :exec
INSERT INTO workload_target_registrations
    (audience, operation, scope, target_sha256, bundle_sha256, enabled)
VALUES ($1, $2, $3,
        $4, $5, $6)
ON CONFLICT (audience, operation) DO UPDATE SET
    scope = EXCLUDED.scope,
    target_sha256 = EXCLUDED.target_sha256,
    bundle_sha256 = EXCLUDED.bundle_sha256,
    enabled = EXCLUDED.enabled
`

type UpsertWorkloadTargetRegistrationParams struct {
	Audience     string
	Operation    string
	Scope        string
	TargetSha256 []byte
	BundleSha256 []byte
	Enabled      bool
}

func (q *Queries) UpsertWorkloadTargetRegistration(ctx context.Context, arg UpsertWorkloadTargetRegistrationParams) error {
	_, err := q.db.Exec(ctx, upsertWorkloadTargetRegistration,
		arg.Audience,
		arg.Operation,
		arg.Scope,
		arg.TargetSha256,
		arg.BundleSha256,
		arg.Enabled,
	)
	return err
}
