// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workload_bootstrap.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkloadBootstrapEnvironmentReceipt = `-- name: GetWorkloadBootstrapEnvironmentReceipt :one
SELECT manifest_id FROM workload_bootstrap_receipts WHERE environment = $1
`

type GetWorkloadBootstrapEnvironmentReceiptParams struct {
	Environment string
}

func (q *Queries) GetWorkloadBootstrapEnvironmentReceipt(ctx context.Context, arg GetWorkloadBootstrapEnvironmentReceiptParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getWorkloadBootstrapEnvironmentReceipt, arg.Environment)
	var manifest_id uuid.UUID
	err := row.Scan(&manifest_id)
	return manifest_id, err
}

const getWorkloadBootstrapReceipt = `-- name: GetWorkloadBootstrapReceipt :one
SELECT intent_sha256, receipt FROM workload_bootstrap_receipts WHERE manifest_id = $1
`

type GetWorkloadBootstrapReceiptParams struct {
	ManifestID uuid.UUID
}

type GetWorkloadBootstrapReceiptRow struct {
	IntentSha256 []byte
	Receipt      []byte
}

func (q *Queries) GetWorkloadBootstrapReceipt(ctx context.Context, arg GetWorkloadBootstrapReceiptParams) (GetWorkloadBootstrapReceiptRow, error) {
	row := q.db.QueryRow(ctx, getWorkloadBootstrapReceipt, arg.ManifestID)
	var i GetWorkloadBootstrapReceiptRow
	err := row.Scan(&i.IntentSha256, &i.Receipt)
	return i, err
}

const insertBootstrapBinding = `-- name: InsertBootstrapBinding :exec
INSERT INTO workload_identity_bindings (id, principal_id, environment, trust_domain, identity_kind, identity_value, status, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'x509_dns', $5, 'active', 1, $6, $6)
`

type InsertBootstrapBindingParams struct {
	BindingID     uuid.UUID
	PrincipalID   uuid.UUID
	Environment   string
	TrustDomain   string
	IdentityValue string
	Now           pgtype.Timestamptz
}

func (q *Queries) InsertBootstrapBinding(ctx context.Context, arg InsertBootstrapBindingParams) error {
	_, err := q.db.Exec(ctx, insertBootstrapBinding,
		arg.BindingID,
		arg.PrincipalID,
		arg.Environment,
		arg.TrustDomain,
		arg.IdentityValue,
		arg.Now,
	)
	return err
}

const insertBootstrapGrant = `-- name: InsertBootstrapGrant :exec
INSERT INTO workload_grants (id, principal_id, environment, trust_domain, audience, operation, scope, status, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'active', 1, $8, $8)
`

type InsertBootstrapGrantParams struct {
	GrantID     uuid.UUID
	PrincipalID uuid.UUID
	Environment string
	TrustDomain string
	Audience    string
	Operation   string
	Scope       string
	Now         pgtype.Timestamptz
}

func (q *Queries) InsertBootstrapGrant(ctx context.Context, arg InsertBootstrapGrantParams) error {
	_, err := q.db.Exec(ctx, insertBootstrapGrant,
		arg.GrantID,
		arg.PrincipalID,
		arg.Environment,
		arg.TrustDomain,
		arg.Audience,
		arg.Operation,
		arg.Scope,
		arg.Now,
	)
	return err
}

const insertBootstrapPrincipal = `-- name: InsertBootstrapPrincipal :exec
INSERT INTO principals (id, principal_type, status, version, created_at, updated_at)
VALUES ($1, 'workload', 'active', 1, $2, $2)
`

type InsertBootstrapPrincipalParams struct {
	PrincipalID uuid.UUID
	Now         pgtype.Timestamptz
}

func (q *Queries) InsertBootstrapPrincipal(ctx context.Context, arg InsertBootstrapPrincipalParams) error {
	_, err := q.db.Exec(ctx, insertBootstrapPrincipal, arg.PrincipalID, arg.Now)
	return err
}

const insertBootstrapProfile = `-- name: InsertBootstrapProfile :exec
INSERT INTO workload_principals (principal_id, owner_type, name, normalized_name, environment, trust_domain, version, created_at, updated_at)
VALUES ($1, 'platform', $2, $2, $3, $4, 1, $5, $5)
`

type InsertBootstrapProfileParams struct {
	PrincipalID uuid.UUID
	Name        string
	Environment pgtype.Text
	TrustDomain pgtype.Text
	Now         pgtype.Timestamptz
}

func (q *Queries) InsertBootstrapProfile(ctx context.Context, arg InsertBootstrapProfileParams) error {
	_, err := q.db.Exec(ctx, insertBootstrapProfile,
		arg.PrincipalID,
		arg.Name,
		arg.Environment,
		arg.TrustDomain,
		arg.Now,
	)
	return err
}

const insertWorkloadBootstrapAudit = `-- name: InsertWorkloadBootstrapAudit :exec
INSERT INTO iam_audit_events (event_id, authentication_method, boundary, action, target_type, target_id, target_version, result, reason,
    request_id, correlation_id, decision_id, source_service, occurred_at, recorded_at, provisioner_role, bootstrap_manifest_id)
VALUES ($1, 'workload_provisioner', 'platform', 'workload.bootstrap', 'workload_bootstrap', $2, 1, 'succeeded', 'REVIEWED_MANIFEST_CONSUMED',
    $3, $3, $4, 'ani-iam-provisioner', $5, $5, current_user, $2)
`

type InsertWorkloadBootstrapAuditParams struct {
	EventID      uuid.UUID
	ManifestID   uuid.UUID
	RequestID    string
	IntentDigest string
	Now          pgtype.Timestamptz
}

func (q *Queries) InsertWorkloadBootstrapAudit(ctx context.Context, arg InsertWorkloadBootstrapAuditParams) error {
	_, err := q.db.Exec(ctx, insertWorkloadBootstrapAudit,
		arg.EventID,
		arg.ManifestID,
		arg.RequestID,
		arg.IntentDigest,
		arg.Now,
	)
	return err
}

const insertWorkloadBootstrapReceipt = `-- name: InsertWorkloadBootstrapReceipt :exec
INSERT INTO workload_bootstrap_receipts (manifest_id, environment, trust_domain, ca_sha256, intent_sha256, receipt, audit_event_id, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertWorkloadBootstrapReceiptParams struct {
	ManifestID   uuid.UUID
	Environment  string
	TrustDomain  string
	CaSha256     []byte
	IntentSha256 []byte
	Receipt      []byte
	AuditEventID uuid.UUID
	Now          pgtype.Timestamptz
}

func (q *Queries) InsertWorkloadBootstrapReceipt(ctx context.Context, arg InsertWorkloadBootstrapReceiptParams) error {
	_, err := q.db.Exec(ctx, insertWorkloadBootstrapReceipt,
		arg.ManifestID,
		arg.Environment,
		arg.TrustDomain,
		arg.CaSha256,
		arg.IntentSha256,
		arg.Receipt,
		arg.AuditEventID,
		arg.Now,
	)
	return err
}

const lockWorkloadBootstrap = `-- name: LockWorkloadBootstrap :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

type LockWorkloadBootstrapParams struct {
	Environment string
}

func (q *Queries) LockWorkloadBootstrap(ctx context.Context, arg LockWorkloadBootstrapParams) error {
	_, err := q.db.Exec(ctx, lockWorkloadBootstrap, arg.Environment)
	return err
}
