// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workload_authority.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const readWorkloadAuthorityGrant = `-- name: ReadWorkloadAuthorityGrant :one
SELECT authority.id, authority.version
FROM workload_grants AS authority
JOIN workload_target_registrations AS registration
  ON registration.audience=authority.audience AND registration.operation=authority.operation
 AND registration.scope=authority.scope
JOIN principals AS principal ON principal.id=authority.principal_id
JOIN workload_principals AS profile ON profile.principal_id=principal.id
JOIN workload_identity_bindings AS binding ON binding.principal_id=principal.id
WHERE authority.principal_id=$1
 AND authority.environment=$2 AND authority.trust_domain=$3
 AND authority.audience=$4 AND authority.operation=$5
 AND registration.enabled AND registration.target_sha256=$6
 AND authority.status='active'
 AND principal.principal_type='workload' AND principal.status='active'
 AND principal.version=$7 AND profile.owner_type='platform'
 AND binding.id=$8 AND binding.version=$9
 AND binding.status='active'
`

type ReadWorkloadAuthorityGrantParams struct {
	PrincipalID      uuid.UUID
	Environment      string
	TrustDomain      string
	Audience         string
	Operation        string
	TargetSha256     []byte
	PrincipalVersion int64
	BindingID        uuid.UUID
	BindingVersion   int64
}

type ReadWorkloadAuthorityGrantRow struct {
	ID      uuid.UUID
	Version int64
}

func (q *Queries) ReadWorkloadAuthorityGrant(ctx context.Context, arg ReadWorkloadAuthorityGrantParams) (ReadWorkloadAuthorityGrantRow, error) {
	row := q.db.QueryRow(ctx, readWorkloadAuthorityGrant,
		arg.PrincipalID,
		arg.Environment,
		arg.TrustDomain,
		arg.Audience,
		arg.Operation,
		arg.TargetSha256,
		arg.PrincipalVersion,
		arg.BindingID,
		arg.BindingVersion,
	)
	var i ReadWorkloadAuthorityGrantRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}
