// Code generated by internal/data/cmd/genoperationregistry; DO NOT EDIT.
package data

import "github.com/zhangzhe-ctrl/ani-iam/internal/biz"

const OwnerOpenAPISHA256 = "cad955dc23460f01e3f5c70ec9d642500623654254ff8d81a285c430ce340ca8"

var generatedOwnerTargetPolicies = []ownerTargetPolicy{
	{Audience: "ani-governance", Operation: "governance.tenant.lifecycle", Method: "POST", Path: "/v1/tenant-lifecycle", Policy: biz.AuthorizationPolicy{OperationID: "ChangeTenantLifecycle", Resource: "governance.tenants", Actions: []string{"change_lifecycle"}, Scope: biz.PermissionScopePlatform, CredentialKinds: []biz.CredentialKind{biz.CredentialKindAccessToken}, PrincipalKinds: []biz.PrincipalType{biz.PrincipalTypeHuman}}},
	{Audience: "ani-governance", Operation: "governance.tenant.create", Method: "POST", Path: "/v1/tenants", Policy: biz.AuthorizationPolicy{OperationID: "CreateTenant", Resource: "governance.tenants", Actions: []string{"create"}, Scope: biz.PermissionScopePlatform, CredentialKinds: []biz.CredentialKind{biz.CredentialKindAccessToken}, PrincipalKinds: []biz.PrincipalType{biz.PrincipalTypeHuman}}},
	{Audience: "ani-governance", Operation: "governance.operation.read", Method: "GET", Path: "/v1/tenant-operations", Policy: biz.AuthorizationPolicy{OperationID: "GetOperation", Resource: "governance.operations", Actions: []string{"read"}, Scope: biz.PermissionScopePlatform, CredentialKinds: []biz.CredentialKind{biz.CredentialKindAccessToken}, PrincipalKinds: []biz.PrincipalType{biz.PrincipalTypeHuman}}},
	{Audience: "ani-governance", Operation: "governance.tenant.inspect", Method: "GET", Path: "/v1/platform/tenants", Policy: biz.AuthorizationPolicy{OperationID: "GetPlatformTenant", Resource: "governance.tenants", Actions: []string{"inspect"}, Scope: biz.PermissionScopePlatform, CredentialKinds: []biz.CredentialKind{biz.CredentialKindAccessToken}, PrincipalKinds: []biz.PrincipalType{biz.PrincipalTypeHuman}}},
	{Audience: "ani-governance", Operation: "governance.tenant.read", Method: "GET", Path: "/v1/tenants", Policy: biz.AuthorizationPolicy{OperationID: "GetTenant", Resource: "governance.tenants", Actions: []string{"read"}, Scope: biz.PermissionScopeTenant, CredentialKinds: []biz.CredentialKind{biz.CredentialKindAccessToken}, PrincipalKinds: []biz.PrincipalType{biz.PrincipalTypeHuman}}},
}
