-- Code generated by internal/data/cmd/genoperationregistry; DO NOT EDIT.
-- Owner OpenAPI SHA-256: eee928a84a61874089f02d8ce0295e1279813b3abebcebe4e4bfe3f11fe2989b.
INSERT INTO permission_catalog (scope,resource,action) VALUES
('platform','governance.operations','read'),
('platform','governance.tenants','change_lifecycle'),
('platform','governance.tenants','create'),
('platform','governance.tenants','inspect'),
('tenant','governance.tenants','read')
ON CONFLICT (scope,resource,action) DO NOTHING;
