syntax = "proto3";

package ani.iam.conf;

option go_package = "github.com/zhangzhe-ctrl/ani-iam/internal/conf;conf";

import "google/protobuf/duration.proto";

message Bootstrap {
  string profile = 1;
  Server server = 2;
}

message Server {
  message GRPC {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }

  message Admin {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }

  GRPC grpc = 1;
  Admin admin = 2;
  google.protobuf.Duration shutdown_timeout = 3;
}
