go test ./...
go vet ./...
export DP2_ATLAS_BIN=/home/ubuntu/.local/share/ani-iam/bin/atlas
go test -json -race -tags integration ./tests/integration -run '^(TestWorkloadBootstrapTransactions|TestFormalWorkloadBootstrapCommand|TestWorkloadRuntimeFoundationUsesCurrentOwnerTrustAndEnforcesRelations|TestNoRLSPersistenceFoundation|TestFormalIAMWorkloadAndHumanRuntime)$' -count=1 -timeout=15m > ../bootstrap-final-tests.jsonl
