// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: reference.proto

package referencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStatusRequest) Reset() {
	*x = ReadStatusRequest{}
	mi := &file_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStatusRequest) ProtoMessage() {}

func (x *ReadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStatusRequest.ProtoReflect.Descriptor instead.
func (*ReadStatusRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{0}
}

type ReadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStatusResponse) Reset() {
	*x = ReadStatusResponse{}
	mi := &file_reference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStatusResponse) ProtoMessage() {}

func (x *ReadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStatusResponse.ProtoReflect.Descriptor instead.
func (*ReadStatusResponse) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{1}
}

func (x *ReadStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReadResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResourceRequest) Reset() {
	*x = ReadResourceRequest{}
	mi := &file_reference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResourceRequest) ProtoMessage() {}

func (x *ReadResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResourceRequest.ProtoReflect.Descriptor instead.
func (*ReadResourceRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{2}
}

func (x *ReadResourceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReadResourceRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ReadResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ReadResourceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReadResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResourceResponse) Reset() {
	*x = ReadResourceResponse{}
	mi := &file_reference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResourceResponse) ProtoMessage() {}

func (x *ReadResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResourceResponse.ProtoReflect.Descriptor instead.
func (*ReadResourceResponse) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResourceResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ReadResourceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_reference_proto protoreflect.FileDescriptor

const file_reference_proto_rawDesc = "" +
	"\n" +
	"\x0freference.proto\x12\freference.v1\"\x13\n" +
	"\x11ReadStatusRequest\",\n" +
	"\x12ReadStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x91\x01\n" +
	"\x13ReadResourceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"O\n" +
	"\x14ReadResourceResponse\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xba\x01\n" +
	"\x10InventoryService\x12O\n" +
	"\n" +
	"ReadStatus\x12\x1f.reference.v1.ReadStatusRequest\x1a .reference.v1.ReadStatusResponse\x12U\n" +
	"\fReadResource\x12!.reference.v1.ReadResourceRequest\x1a\".reference.v1.ReadResourceResponseBVZTgithub.com/zhangzhe-ctrl/ani-iam/examples/workload-grpc/api/reference/v1;referencev1b\x06proto3"

var (
	file_reference_proto_rawDescOnce sync.Once
	file_reference_proto_rawDescData []byte
)

func file_reference_proto_rawDescGZIP() []byte {
	file_reference_proto_rawDescOnce.Do(func() {
		file_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reference_proto_rawDesc), len(file_reference_proto_rawDesc)))
	})
	return file_reference_proto_rawDescData
}

var file_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reference_proto_goTypes = []any{
	(*ReadStatusRequest)(nil),    // 0: reference.v1.ReadStatusRequest
	(*ReadStatusResponse)(nil),   // 1: reference.v1.ReadStatusResponse
	(*ReadResourceRequest)(nil),  // 2: reference.v1.ReadResourceRequest
	(*ReadResourceResponse)(nil), // 3: reference.v1.ReadResourceResponse
}
var file_reference_proto_depIdxs = []int32{
	0, // 0: reference.v1.InventoryService.ReadStatus:input_type -> reference.v1.ReadStatusRequest
	2, // 1: reference.v1.InventoryService.ReadResource:input_type -> reference.v1.ReadResourceRequest
	1, // 2: reference.v1.InventoryService.ReadStatus:output_type -> reference.v1.ReadStatusResponse
	3, // 3: reference.v1.InventoryService.ReadResource:output_type -> reference.v1.ReadResourceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reference_proto_init() }
func file_reference_proto_init() {
	if File_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reference_proto_rawDesc), len(file_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reference_proto_goTypes,
		DependencyIndexes: file_reference_proto_depIdxs,
		MessageInfos:      file_reference_proto_msgTypes,
	}.Build()
	File_reference_proto = out.File
	file_reference_proto_goTypes = nil
	file_reference_proto_depIdxs = nil
}
