// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: authorization_service.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckPermissionRequest carries the raw credential and immutable operation-policy identity.
type CheckPermissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credential     *BearerCredential      `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	OperationId    string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	PolicyRevision string                 `protobuf:"bytes,3,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	Target         *AuthorizationTarget   `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_authorization_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_authorization_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPermissionRequest) GetCredential() *BearerCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CheckPermissionRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CheckPermissionRequest) GetPolicyRevision() string {
	if x != nil {
		return x.PolicyRevision
	}
	return ""
}

func (x *CheckPermissionRequest) GetTarget() *AuthorizationTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

// AuthorizationDecision is explicit: the zero value cannot encode allow.
type AuthorizationDecision struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Allowed        bool                       `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason         string                     `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DecisionId     string                     `protobuf:"bytes,3,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Principal      *PrincipalContext          `protobuf:"bytes,4,opt,name=principal,proto3" json:"principal,omitempty"`
	Obligations    []*AuthorizationObligation `protobuf:"bytes,5,rep,name=obligations,proto3" json:"obligations,omitempty"`
	PolicyRevision string                     `protobuf:"bytes,6,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorizationDecision) Reset() {
	*x = AuthorizationDecision{}
	mi := &file_authorization_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationDecision) ProtoMessage() {}

func (x *AuthorizationDecision) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationDecision.ProtoReflect.Descriptor instead.
func (*AuthorizationDecision) Descriptor() ([]byte, []int) {
	return file_authorization_service_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationDecision) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AuthorizationDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuthorizationDecision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *AuthorizationDecision) GetPrincipal() *PrincipalContext {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *AuthorizationDecision) GetObligations() []*AuthorizationObligation {
	if x != nil {
		return x.Obligations
	}
	return nil
}

func (x *AuthorizationDecision) GetPolicyRevision() string {
	if x != nil {
		return x.PolicyRevision
	}
	return ""
}

// CheckPermissionResponse contains exactly one authorization decision.
type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      *AuthorizationDecision `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_authorization_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_authorization_service_proto_rawDescGZIP(), []int{2}
}

func (x *CheckPermissionResponse) GetDecision() *AuthorizationDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

var File_authorization_service_proto protoreflect.FileDescriptor

const file_authorization_service_proto_rawDesc = "" +
	"\n" +
	"\x1bauthorization_service.proto\x12\x06iam.v1\x1a\x0econtract.proto\x1a\x0eworkload.proto\"\xd3\x01\n" +
	"\x16CheckPermissionRequest\x128\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x18.iam.v1.BearerCredentialR\n" +
	"credential\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12'\n" +
	"\x0fpolicy_revision\x18\x03 \x01(\tR\x0epolicyRevision\x123\n" +
	"\x06target\x18\x04 \x01(\v2\x1b.iam.v1.AuthorizationTargetR\x06target\"\x8e\x02\n" +
	"\x15AuthorizationDecision\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vdecision_id\x18\x03 \x01(\tR\n" +
	"decisionId\x126\n" +
	"\tprincipal\x18\x04 \x01(\v2\x18.iam.v1.PrincipalContextR\tprincipal\x12A\n" +
	"\vobligations\x18\x05 \x03(\v2\x1f.iam.v1.AuthorizationObligationR\vobligations\x12'\n" +
	"\x0fpolicy_revision\x18\x06 \x01(\tR\x0epolicyRevision\"T\n" +
	"\x17CheckPermissionResponse\x129\n" +
	"\bdecision\x18\x01 \x01(\v2\x1d.iam.v1.AuthorizationDecisionR\bdecision2\xcb\x02\n" +
	"\x14AuthorizationService\x12p\n" +
	"\x19VerifySessionContinuation\x12(.iam.v1.VerifySessionContinuationRequest\x1a).iam.v1.VerifySessionContinuationResponse\x12R\n" +
	"\x0fCheckPermission\x12\x1e.iam.v1.CheckPermissionRequest\x1a\x1f.iam.v1.CheckPermissionResponse\x12m\n" +
	"\x18VerifyWorkloadInvocation\x12'.iam.v1.VerifyWorkloadInvocationRequest\x1a(.iam.v1.VerifyWorkloadInvocationResponseB3Z1github.com/zhangzhe-ctrl/ani-iam/api/iam/v1;iamv1b\x06proto3"

var (
	file_authorization_service_proto_rawDescOnce sync.Once
	file_authorization_service_proto_rawDescData []byte
)

func file_authorization_service_proto_rawDescGZIP() []byte {
	file_authorization_service_proto_rawDescOnce.Do(func() {
		file_authorization_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authorization_service_proto_rawDesc), len(file_authorization_service_proto_rawDesc)))
	})
	return file_authorization_service_proto_rawDescData
}

var file_authorization_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_authorization_service_proto_goTypes = []any{
	(*CheckPermissionRequest)(nil),            // 0: iam.v1.CheckPermissionRequest
	(*AuthorizationDecision)(nil),             // 1: iam.v1.AuthorizationDecision
	(*CheckPermissionResponse)(nil),           // 2: iam.v1.CheckPermissionResponse
	(*BearerCredential)(nil),                  // 3: iam.v1.BearerCredential
	(*AuthorizationTarget)(nil),               // 4: iam.v1.AuthorizationTarget
	(*PrincipalContext)(nil),                  // 5: iam.v1.PrincipalContext
	(*AuthorizationObligation)(nil),           // 6: iam.v1.AuthorizationObligation
	(*VerifySessionContinuationRequest)(nil),  // 7: iam.v1.VerifySessionContinuationRequest
	(*VerifyWorkloadInvocationRequest)(nil),   // 8: iam.v1.VerifyWorkloadInvocationRequest
	(*VerifySessionContinuationResponse)(nil), // 9: iam.v1.VerifySessionContinuationResponse
	(*VerifyWorkloadInvocationResponse)(nil),  // 10: iam.v1.VerifyWorkloadInvocationResponse
}
var file_authorization_service_proto_depIdxs = []int32{
	3,  // 0: iam.v1.CheckPermissionRequest.credential:type_name -> iam.v1.BearerCredential
	4,  // 1: iam.v1.CheckPermissionRequest.target:type_name -> iam.v1.AuthorizationTarget
	5,  // 2: iam.v1.AuthorizationDecision.principal:type_name -> iam.v1.PrincipalContext
	6,  // 3: iam.v1.AuthorizationDecision.obligations:type_name -> iam.v1.AuthorizationObligation
	1,  // 4: iam.v1.CheckPermissionResponse.decision:type_name -> iam.v1.AuthorizationDecision
	7,  // 5: iam.v1.AuthorizationService.VerifySessionContinuation:input_type -> iam.v1.VerifySessionContinuationRequest
	0,  // 6: iam.v1.AuthorizationService.CheckPermission:input_type -> iam.v1.CheckPermissionRequest
	8,  // 7: iam.v1.AuthorizationService.VerifyWorkloadInvocation:input_type -> iam.v1.VerifyWorkloadInvocationRequest
	9,  // 8: iam.v1.AuthorizationService.VerifySessionContinuation:output_type -> iam.v1.VerifySessionContinuationResponse
	2,  // 9: iam.v1.AuthorizationService.CheckPermission:output_type -> iam.v1.CheckPermissionResponse
	10, // 10: iam.v1.AuthorizationService.VerifyWorkloadInvocation:output_type -> iam.v1.VerifyWorkloadInvocationResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_authorization_service_proto_init() }
func file_authorization_service_proto_init() {
	if File_authorization_service_proto != nil {
		return
	}
	file_contract_proto_init()
	file_workload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authorization_service_proto_rawDesc), len(file_authorization_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authorization_service_proto_goTypes,
		DependencyIndexes: file_authorization_service_proto_depIdxs,
		MessageInfos:      file_authorization_service_proto_msgTypes,
	}.Build()
	File_authorization_service_proto = out.File
	file_authorization_service_proto_goTypes = nil
	file_authorization_service_proto_depIdxs = nil
}
