// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tenant_bootstrap.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IAM owns this reliable asynchronous request. Receipt is not administrator
// readiness. The producer identity is established by broker authority, never by
// the producer field. No password, membership, role or credential is supplied.
type TenantBootstrapRequested struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaRevision string                 `protobuf:"bytes,1,opt,name=schema_revision,json=schemaRevision,proto3" json:"schema_revision,omitempty"`
	EventId        string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Producer       string                 `protobuf:"bytes,3,opt,name=producer,proto3" json:"producer,omitempty"`
	TenantId       string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OperationId    string                 `protobuf:"bytes,5,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// References the authoritative lifecycle fact needed by the worker. This
	// message does not advance the lifecycle sequence or repair its projection.
	SourceEpoch           string                        `protobuf:"bytes,7,opt,name=source_epoch,json=sourceEpoch,proto3" json:"source_epoch,omitempty"`
	LifecycleSequence     int64                         `protobuf:"varint,8,opt,name=lifecycle_sequence,json=lifecycleSequence,proto3" json:"lifecycle_sequence,omitempty"`
	IntendedAdministrator *TenantBootstrapAdministrator `protobuf:"bytes,9,opt,name=intended_administrator,json=intendedAdministrator,proto3" json:"intended_administrator,omitempty"`
	PayloadFingerprint    string                        `protobuf:"bytes,10,opt,name=payload_fingerprint,json=payloadFingerprint,proto3" json:"payload_fingerprint,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TenantBootstrapRequested) Reset() {
	*x = TenantBootstrapRequested{}
	mi := &file_tenant_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantBootstrapRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantBootstrapRequested) ProtoMessage() {}

func (x *TenantBootstrapRequested) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantBootstrapRequested.ProtoReflect.Descriptor instead.
func (*TenantBootstrapRequested) Descriptor() ([]byte, []int) {
	return file_tenant_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *TenantBootstrapRequested) GetSchemaRevision() string {
	if x != nil {
		return x.SchemaRevision
	}
	return ""
}

func (x *TenantBootstrapRequested) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TenantBootstrapRequested) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *TenantBootstrapRequested) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantBootstrapRequested) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *TenantBootstrapRequested) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TenantBootstrapRequested) GetSourceEpoch() string {
	if x != nil {
		return x.SourceEpoch
	}
	return ""
}

func (x *TenantBootstrapRequested) GetLifecycleSequence() int64 {
	if x != nil {
		return x.LifecycleSequence
	}
	return 0
}

func (x *TenantBootstrapRequested) GetIntendedAdministrator() *TenantBootstrapAdministrator {
	if x != nil {
		return x.IntendedAdministrator
	}
	return nil
}

func (x *TenantBootstrapRequested) GetPayloadFingerprint() string {
	if x != nil {
		return x.PayloadFingerprint
	}
	return ""
}

type TenantBootstrapAdministrator struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NormalizedEmail string                 `protobuf:"bytes,1,opt,name=normalized_email,json=normalizedEmail,proto3" json:"normalized_email,omitempty"`
	Locale          string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TenantBootstrapAdministrator) Reset() {
	*x = TenantBootstrapAdministrator{}
	mi := &file_tenant_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantBootstrapAdministrator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantBootstrapAdministrator) ProtoMessage() {}

func (x *TenantBootstrapAdministrator) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantBootstrapAdministrator.ProtoReflect.Descriptor instead.
func (*TenantBootstrapAdministrator) Descriptor() ([]byte, []int) {
	return file_tenant_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *TenantBootstrapAdministrator) GetNormalizedEmail() string {
	if x != nil {
		return x.NormalizedEmail
	}
	return ""
}

func (x *TenantBootstrapAdministrator) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

var File_tenant_bootstrap_proto protoreflect.FileDescriptor

const file_tenant_bootstrap_proto_rawDesc = "" +
	"\n" +
	"\x16tenant_bootstrap.proto\x12\x06iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x03\n" +
	"\x18TenantBootstrapRequested\x12'\n" +
	"\x0fschema_revision\x18\x01 \x01(\tR\x0eschemaRevision\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1a\n" +
	"\bproducer\x18\x03 \x01(\tR\bproducer\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12!\n" +
	"\foperation_id\x18\x05 \x01(\tR\voperationId\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12!\n" +
	"\fsource_epoch\x18\a \x01(\tR\vsourceEpoch\x12-\n" +
	"\x12lifecycle_sequence\x18\b \x01(\x03R\x11lifecycleSequence\x12[\n" +
	"\x16intended_administrator\x18\t \x01(\v2$.iam.v1.TenantBootstrapAdministratorR\x15intendedAdministrator\x12/\n" +
	"\x13payload_fingerprint\x18\n" +
	" \x01(\tR\x12payloadFingerprint\"a\n" +
	"\x1cTenantBootstrapAdministrator\x12)\n" +
	"\x10normalized_email\x18\x01 \x01(\tR\x0fnormalizedEmail\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06localeB3Z1github.com/zhangzhe-ctrl/ani-iam/api/iam/v1;iamv1b\x06proto3"

var (
	file_tenant_bootstrap_proto_rawDescOnce sync.Once
	file_tenant_bootstrap_proto_rawDescData []byte
)

func file_tenant_bootstrap_proto_rawDescGZIP() []byte {
	file_tenant_bootstrap_proto_rawDescOnce.Do(func() {
		file_tenant_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_bootstrap_proto_rawDesc), len(file_tenant_bootstrap_proto_rawDesc)))
	})
	return file_tenant_bootstrap_proto_rawDescData
}

var file_tenant_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tenant_bootstrap_proto_goTypes = []any{
	(*TenantBootstrapRequested)(nil),     // 0: iam.v1.TenantBootstrapRequested
	(*TenantBootstrapAdministrator)(nil), // 1: iam.v1.TenantBootstrapAdministrator
	(*timestamppb.Timestamp)(nil),        // 2: google.protobuf.Timestamp
}
var file_tenant_bootstrap_proto_depIdxs = []int32{
	2, // 0: iam.v1.TenantBootstrapRequested.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 1: iam.v1.TenantBootstrapRequested.intended_administrator:type_name -> iam.v1.TenantBootstrapAdministrator
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tenant_bootstrap_proto_init() }
func file_tenant_bootstrap_proto_init() {
	if File_tenant_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_bootstrap_proto_rawDesc), len(file_tenant_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tenant_bootstrap_proto_goTypes,
		DependencyIndexes: file_tenant_bootstrap_proto_depIdxs,
		MessageInfos:      file_tenant_bootstrap_proto_msgTypes,
	}.Build()
	File_tenant_bootstrap_proto = out.File
	file_tenant_bootstrap_proto_goTypes = nil
	file_tenant_bootstrap_proto_depIdxs = nil
}
