// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: workload.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InvocationBinding identifies the normalized business request, not authority.
// The request digest covers the entire actual owner DTO under the v1 contract.
type InvocationBinding struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Audience          string                 `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	OperationId       string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	RpcMethod         string                 `protobuf:"bytes,3,opt,name=rpc_method,json=rpcMethod,proto3" json:"rpc_method,omitempty"`
	SourceOperationId string                 `protobuf:"bytes,4,opt,name=source_operation_id,json=sourceOperationId,proto3" json:"source_operation_id,omitempty"`
	TenantId          string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SubjectId         string                 `protobuf:"bytes,6,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	ResourceId        string                 `protobuf:"bytes,7,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Mode              string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"`
	RequestSha256     []byte                 `protobuf:"bytes,9,opt,name=request_sha256,json=requestSha256,proto3" json:"request_sha256,omitempty"`
	PolicyRevision    string                 `protobuf:"bytes,10,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InvocationBinding) Reset() {
	*x = InvocationBinding{}
	mi := &file_workload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationBinding) ProtoMessage() {}

func (x *InvocationBinding) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationBinding.ProtoReflect.Descriptor instead.
func (*InvocationBinding) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{0}
}

func (x *InvocationBinding) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *InvocationBinding) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *InvocationBinding) GetRpcMethod() string {
	if x != nil {
		return x.RpcMethod
	}
	return ""
}

func (x *InvocationBinding) GetSourceOperationId() string {
	if x != nil {
		return x.SourceOperationId
	}
	return ""
}

func (x *InvocationBinding) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InvocationBinding) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *InvocationBinding) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *InvocationBinding) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *InvocationBinding) GetRequestSha256() []byte {
	if x != nil {
		return x.RequestSha256
	}
	return nil
}

func (x *InvocationBinding) GetPolicyRevision() string {
	if x != nil {
		return x.PolicyRevision
	}
	return ""
}

// WorkloadPeer is reported only by an authenticated receiver after mTLS
// verification. A business caller cannot self-assert these fields at ingress.
type WorkloadPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	TrustDomain   string                 `protobuf:"bytes,2,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	IdentityKind  string                 `protobuf:"bytes,3,opt,name=identity_kind,json=identityKind,proto3" json:"identity_kind,omitempty"`
	IdentityValue string                 `protobuf:"bytes,4,opt,name=identity_value,json=identityValue,proto3" json:"identity_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadPeer) Reset() {
	*x = WorkloadPeer{}
	mi := &file_workload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadPeer) ProtoMessage() {}

func (x *WorkloadPeer) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadPeer.ProtoReflect.Descriptor instead.
func (*WorkloadPeer) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadPeer) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *WorkloadPeer) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *WorkloadPeer) GetIdentityKind() string {
	if x != nil {
		return x.IdentityKind
	}
	return ""
}

func (x *WorkloadPeer) GetIdentityValue() string {
	if x != nil {
		return x.IdentityValue
	}
	return ""
}

// DirectWorkloadCaller is the current identity and authority for one hop.
type DirectWorkloadCaller struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId      string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	BindingId        string                 `protobuf:"bytes,2,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	PrincipalVersion int64                  `protobuf:"varint,3,opt,name=principal_version,json=principalVersion,proto3" json:"principal_version,omitempty"`
	BindingVersion   int64                  `protobuf:"varint,4,opt,name=binding_version,json=bindingVersion,proto3" json:"binding_version,omitempty"`
	GrantVersion     int64                  `protobuf:"varint,5,opt,name=grant_version,json=grantVersion,proto3" json:"grant_version,omitempty"`
	Peer             *WorkloadPeer          `protobuf:"bytes,6,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DirectWorkloadCaller) Reset() {
	*x = DirectWorkloadCaller{}
	mi := &file_workload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectWorkloadCaller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectWorkloadCaller) ProtoMessage() {}

func (x *DirectWorkloadCaller) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectWorkloadCaller.ProtoReflect.Descriptor instead.
func (*DirectWorkloadCaller) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{2}
}

func (x *DirectWorkloadCaller) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *DirectWorkloadCaller) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *DirectWorkloadCaller) GetPrincipalVersion() int64 {
	if x != nil {
		return x.PrincipalVersion
	}
	return 0
}

func (x *DirectWorkloadCaller) GetBindingVersion() int64 {
	if x != nil {
		return x.BindingVersion
	}
	return 0
}

func (x *DirectWorkloadCaller) GetGrantVersion() int64 {
	if x != nil {
		return x.GrantVersion
	}
	return 0
}

func (x *DirectWorkloadCaller) GetPeer() *WorkloadPeer {
	if x != nil {
		return x.Peer
	}
	return nil
}

// IssueDelegationRequest reauthorizes the actual subject for this exact request.
// The original credential is sent only to IAM, never to the business receiver.
type IssueDelegationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubjectCredential *BearerCredential      `protobuf:"bytes,1,opt,name=subject_credential,json=subjectCredential,proto3" json:"subject_credential,omitempty"`
	WorkloadToken     string                 `protobuf:"bytes,2,opt,name=workload_token,json=workloadToken,proto3" json:"workload_token,omitempty"`
	Binding           *InvocationBinding     `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IssueDelegationRequest) Reset() {
	*x = IssueDelegationRequest{}
	mi := &file_workload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueDelegationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueDelegationRequest) ProtoMessage() {}

func (x *IssueDelegationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueDelegationRequest.ProtoReflect.Descriptor instead.
func (*IssueDelegationRequest) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{3}
}

func (x *IssueDelegationRequest) GetSubjectCredential() *BearerCredential {
	if x != nil {
		return x.SubjectCredential
	}
	return nil
}

func (x *IssueDelegationRequest) GetWorkloadToken() string {
	if x != nil {
		return x.WorkloadToken
	}
	return ""
}

func (x *IssueDelegationRequest) GetBinding() *InvocationBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

// IssueDelegationResponse expires in at most sixty seconds and cannot refresh.
type IssueDelegationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegation    string                 `protobuf:"bytes,1,opt,name=delegation,proto3" json:"delegation,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueDelegationResponse) Reset() {
	*x = IssueDelegationResponse{}
	mi := &file_workload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueDelegationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueDelegationResponse) ProtoMessage() {}

func (x *IssueDelegationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueDelegationResponse.ProtoReflect.Descriptor instead.
func (*IssueDelegationResponse) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{4}
}

func (x *IssueDelegationResponse) GetDelegation() string {
	if x != nil {
		return x.Delegation
	}
	return ""
}

func (x *IssueDelegationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// VerifyWorkloadInvocationRequest is sent with the receiver's own mTLS identity
// and exact verification Grant. IAM reads current caller and subject authority.
type VerifyWorkloadInvocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadToken string                 `protobuf:"bytes,1,opt,name=workload_token,json=workloadToken,proto3" json:"workload_token,omitempty"`
	Delegation    string                 `protobuf:"bytes,2,opt,name=delegation,proto3" json:"delegation,omitempty"`
	Binding       *InvocationBinding     `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	ObservedPeer  *WorkloadPeer          `protobuf:"bytes,4,opt,name=observed_peer,json=observedPeer,proto3" json:"observed_peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWorkloadInvocationRequest) Reset() {
	*x = VerifyWorkloadInvocationRequest{}
	mi := &file_workload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWorkloadInvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWorkloadInvocationRequest) ProtoMessage() {}

func (x *VerifyWorkloadInvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWorkloadInvocationRequest.ProtoReflect.Descriptor instead.
func (*VerifyWorkloadInvocationRequest) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyWorkloadInvocationRequest) GetWorkloadToken() string {
	if x != nil {
		return x.WorkloadToken
	}
	return ""
}

func (x *VerifyWorkloadInvocationRequest) GetDelegation() string {
	if x != nil {
		return x.Delegation
	}
	return ""
}

func (x *VerifyWorkloadInvocationRequest) GetBinding() *InvocationBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *VerifyWorkloadInvocationRequest) GetObservedPeer() *WorkloadPeer {
	if x != nil {
		return x.ObservedPeer
	}
	return nil
}

// VerifyWorkloadInvocationResponse is typed, request-bound verification output.
// It is not a reusable credential or an authorization for another operation.
type VerifyWorkloadInvocationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque receiver-bound reference; only usable for online continuation checks.
	Continuation          string                 `protobuf:"bytes,5,opt,name=continuation,proto3" json:"continuation,omitempty"`
	ContinuationExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=continuation_expires_at,json=continuationExpiresAt,proto3" json:"continuation_expires_at,omitempty"`
	Caller                *DirectWorkloadCaller  `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Subject               *PrincipalContext      `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Binding               *InvocationBinding     `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	ExpiresAt             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VerifyWorkloadInvocationResponse) Reset() {
	*x = VerifyWorkloadInvocationResponse{}
	mi := &file_workload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWorkloadInvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWorkloadInvocationResponse) ProtoMessage() {}

func (x *VerifyWorkloadInvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWorkloadInvocationResponse.ProtoReflect.Descriptor instead.
func (*VerifyWorkloadInvocationResponse) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyWorkloadInvocationResponse) GetContinuation() string {
	if x != nil {
		return x.Continuation
	}
	return ""
}

func (x *VerifyWorkloadInvocationResponse) GetContinuationExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ContinuationExpiresAt
	}
	return nil
}

func (x *VerifyWorkloadInvocationResponse) GetCaller() *DirectWorkloadCaller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *VerifyWorkloadInvocationResponse) GetSubject() *PrincipalContext {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *VerifyWorkloadInvocationResponse) GetBinding() *InvocationBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *VerifyWorkloadInvocationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Receiver-only online recheck of a previously admitted request. This reference
// cannot mint a new delegation, WAT or Session, and is not renewable.
type VerifySessionContinuationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Continuation  string                 `protobuf:"bytes,1,opt,name=continuation,proto3" json:"continuation,omitempty"`
	Binding       *InvocationBinding     `protobuf:"bytes,2,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySessionContinuationRequest) Reset() {
	*x = VerifySessionContinuationRequest{}
	mi := &file_workload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySessionContinuationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySessionContinuationRequest) ProtoMessage() {}

func (x *VerifySessionContinuationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySessionContinuationRequest.ProtoReflect.Descriptor instead.
func (*VerifySessionContinuationRequest) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{7}
}

func (x *VerifySessionContinuationRequest) GetContinuation() string {
	if x != nil {
		return x.Continuation
	}
	return ""
}

func (x *VerifySessionContinuationRequest) GetBinding() *InvocationBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

type VerifySessionContinuationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        *DirectWorkloadCaller  `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Subject       *PrincipalContext      `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Binding       *InvocationBinding     `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySessionContinuationResponse) Reset() {
	*x = VerifySessionContinuationResponse{}
	mi := &file_workload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySessionContinuationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySessionContinuationResponse) ProtoMessage() {}

func (x *VerifySessionContinuationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySessionContinuationResponse.ProtoReflect.Descriptor instead.
func (*VerifySessionContinuationResponse) Descriptor() ([]byte, []int) {
	return file_workload_proto_rawDescGZIP(), []int{8}
}

func (x *VerifySessionContinuationResponse) GetCaller() *DirectWorkloadCaller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *VerifySessionContinuationResponse) GetSubject() *PrincipalContext {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *VerifySessionContinuationResponse) GetBinding() *InvocationBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *VerifySessionContinuationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_workload_proto protoreflect.FileDescriptor

const file_workload_proto_rawDesc = "" +
	"\n" +
	"\x0eworkload.proto\x12\x06iam.v1\x1a\x0econtract.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x02\n" +
	"\x11InvocationBinding\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x1d\n" +
	"\n" +
	"rpc_method\x18\x03 \x01(\tR\trpcMethod\x12.\n" +
	"\x13source_operation_id\x18\x04 \x01(\tR\x11sourceOperationId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x06 \x01(\tR\tsubjectId\x12\x1f\n" +
	"\vresource_id\x18\a \x01(\tR\n" +
	"resourceId\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\x12%\n" +
	"\x0erequest_sha256\x18\t \x01(\fR\rrequestSha256\x12'\n" +
	"\x0fpolicy_revision\x18\n" +
	" \x01(\tR\x0epolicyRevision\"\x9f\x01\n" +
	"\fWorkloadPeer\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x12!\n" +
	"\ftrust_domain\x18\x02 \x01(\tR\vtrustDomain\x12#\n" +
	"\ridentity_kind\x18\x03 \x01(\tR\fidentityKind\x12%\n" +
	"\x0eidentity_value\x18\x04 \x01(\tR\ridentityValue\"\xfd\x01\n" +
	"\x14DirectWorkloadCaller\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x02 \x01(\tR\tbindingId\x12+\n" +
	"\x11principal_version\x18\x03 \x01(\x03R\x10principalVersion\x12'\n" +
	"\x0fbinding_version\x18\x04 \x01(\x03R\x0ebindingVersion\x12#\n" +
	"\rgrant_version\x18\x05 \x01(\x03R\fgrantVersion\x12(\n" +
	"\x04peer\x18\x06 \x01(\v2\x14.iam.v1.WorkloadPeerR\x04peer\"\xbd\x01\n" +
	"\x16IssueDelegationRequest\x12G\n" +
	"\x12subject_credential\x18\x01 \x01(\v2\x18.iam.v1.BearerCredentialR\x11subjectCredential\x12%\n" +
	"\x0eworkload_token\x18\x02 \x01(\tR\rworkloadToken\x123\n" +
	"\abinding\x18\x03 \x01(\v2\x19.iam.v1.InvocationBindingR\abinding\"t\n" +
	"\x17IssueDelegationResponse\x12\x1e\n" +
	"\n" +
	"delegation\x18\x01 \x01(\tR\n" +
	"delegation\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xd8\x01\n" +
	"\x1fVerifyWorkloadInvocationRequest\x12%\n" +
	"\x0eworkload_token\x18\x01 \x01(\tR\rworkloadToken\x12\x1e\n" +
	"\n" +
	"delegation\x18\x02 \x01(\tR\n" +
	"delegation\x123\n" +
	"\abinding\x18\x03 \x01(\v2\x19.iam.v1.InvocationBindingR\abinding\x129\n" +
	"\robserved_peer\x18\x04 \x01(\v2\x14.iam.v1.WorkloadPeerR\fobservedPeer\"\xf4\x02\n" +
	" VerifyWorkloadInvocationResponse\x12\"\n" +
	"\fcontinuation\x18\x05 \x01(\tR\fcontinuation\x12R\n" +
	"\x17continuation_expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x15continuationExpiresAt\x124\n" +
	"\x06caller\x18\x01 \x01(\v2\x1c.iam.v1.DirectWorkloadCallerR\x06caller\x122\n" +
	"\asubject\x18\x02 \x01(\v2\x18.iam.v1.PrincipalContextR\asubject\x123\n" +
	"\abinding\x18\x03 \x01(\v2\x19.iam.v1.InvocationBindingR\abinding\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"{\n" +
	" VerifySessionContinuationRequest\x12\"\n" +
	"\fcontinuation\x18\x01 \x01(\tR\fcontinuation\x123\n" +
	"\abinding\x18\x02 \x01(\v2\x19.iam.v1.InvocationBindingR\abinding\"\xfd\x01\n" +
	"!VerifySessionContinuationResponse\x124\n" +
	"\x06caller\x18\x01 \x01(\v2\x1c.iam.v1.DirectWorkloadCallerR\x06caller\x122\n" +
	"\asubject\x18\x02 \x01(\v2\x18.iam.v1.PrincipalContextR\asubject\x123\n" +
	"\abinding\x18\x03 \x01(\v2\x19.iam.v1.InvocationBindingR\abinding\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtB3Z1github.com/zhangzhe-ctrl/ani-iam/api/iam/v1;iamv1b\x06proto3"

var (
	file_workload_proto_rawDescOnce sync.Once
	file_workload_proto_rawDescData []byte
)

func file_workload_proto_rawDescGZIP() []byte {
	file_workload_proto_rawDescOnce.Do(func() {
		file_workload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workload_proto_rawDesc), len(file_workload_proto_rawDesc)))
	})
	return file_workload_proto_rawDescData
}

var file_workload_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_workload_proto_goTypes = []any{
	(*InvocationBinding)(nil),                 // 0: iam.v1.InvocationBinding
	(*WorkloadPeer)(nil),                      // 1: iam.v1.WorkloadPeer
	(*DirectWorkloadCaller)(nil),              // 2: iam.v1.DirectWorkloadCaller
	(*IssueDelegationRequest)(nil),            // 3: iam.v1.IssueDelegationRequest
	(*IssueDelegationResponse)(nil),           // 4: iam.v1.IssueDelegationResponse
	(*VerifyWorkloadInvocationRequest)(nil),   // 5: iam.v1.VerifyWorkloadInvocationRequest
	(*VerifyWorkloadInvocationResponse)(nil),  // 6: iam.v1.VerifyWorkloadInvocationResponse
	(*VerifySessionContinuationRequest)(nil),  // 7: iam.v1.VerifySessionContinuationRequest
	(*VerifySessionContinuationResponse)(nil), // 8: iam.v1.VerifySessionContinuationResponse
	(*BearerCredential)(nil),                  // 9: iam.v1.BearerCredential
	(*timestamppb.Timestamp)(nil),             // 10: google.protobuf.Timestamp
	(*PrincipalContext)(nil),                  // 11: iam.v1.PrincipalContext
}
var file_workload_proto_depIdxs = []int32{
	1,  // 0: iam.v1.DirectWorkloadCaller.peer:type_name -> iam.v1.WorkloadPeer
	9,  // 1: iam.v1.IssueDelegationRequest.subject_credential:type_name -> iam.v1.BearerCredential
	0,  // 2: iam.v1.IssueDelegationRequest.binding:type_name -> iam.v1.InvocationBinding
	10, // 3: iam.v1.IssueDelegationResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 4: iam.v1.VerifyWorkloadInvocationRequest.binding:type_name -> iam.v1.InvocationBinding
	1,  // 5: iam.v1.VerifyWorkloadInvocationRequest.observed_peer:type_name -> iam.v1.WorkloadPeer
	10, // 6: iam.v1.VerifyWorkloadInvocationResponse.continuation_expires_at:type_name -> google.protobuf.Timestamp
	2,  // 7: iam.v1.VerifyWorkloadInvocationResponse.caller:type_name -> iam.v1.DirectWorkloadCaller
	11, // 8: iam.v1.VerifyWorkloadInvocationResponse.subject:type_name -> iam.v1.PrincipalContext
	0,  // 9: iam.v1.VerifyWorkloadInvocationResponse.binding:type_name -> iam.v1.InvocationBinding
	10, // 10: iam.v1.VerifyWorkloadInvocationResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 11: iam.v1.VerifySessionContinuationRequest.binding:type_name -> iam.v1.InvocationBinding
	2,  // 12: iam.v1.VerifySessionContinuationResponse.caller:type_name -> iam.v1.DirectWorkloadCaller
	11, // 13: iam.v1.VerifySessionContinuationResponse.subject:type_name -> iam.v1.PrincipalContext
	0,  // 14: iam.v1.VerifySessionContinuationResponse.binding:type_name -> iam.v1.InvocationBinding
	10, // 15: iam.v1.VerifySessionContinuationResponse.expires_at:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_workload_proto_init() }
func file_workload_proto_init() {
	if File_workload_proto != nil {
		return
	}
	file_contract_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workload_proto_rawDesc), len(file_workload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workload_proto_goTypes,
		DependencyIndexes: file_workload_proto_depIdxs,
		MessageInfos:      file_workload_proto_msgTypes,
	}.Build()
	File_workload_proto = out.File
	file_workload_proto_goTypes = nil
	file_workload_proto_depIdxs = nil
}
